### ISSUE TITLE
Call to undefined method Illuminate\Http\Response::view()

### ISSUE THREAD

**Issue by crazycodr** [laravel/docs#2388]
[Documentation](https://laravel.com/docs/5.2/responses#view-responses) states i should be able to

``` php
return response('You cannot access this page', 403)->view('error-view-name');
```

I tried and it doesn't work. I checked the Response class and indeed, no function in the whole dependency tree seems to make "view" be available in any way.

I did find out that by using:

``` php
return view('error-view-name', 403);
```

I think documentation should be updated to reflect this all pages
- https://laravel.com/docs/5.2/views
- https://laravel.com/docs/5.2/responses#view-responses

Sorry but i really don't have the time to work on that right now but at least i took the time to report it :)

**Comment by GrahamCampbell** [comment]
> I checked the Response class

You'll need to look at the response factory.

**Comment by GrahamCampbell** [comment]
Yeh, there is no bug here. The method does exist: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/ResponseFactory.php#L69.

**Comment by GrahamCampbell** [comment]
You can do `response()->view(...)`, but NOT what you have there.

**Comment by crazycodr** [comment]
My mistake on the second part too, framework induced me in error thinking i could pass 403 as a second param because it was complaining my view was not there...

But for the response()->view(), why isn't it working for me then?

I'm getting an undefined function exception!

**Comment by crynobone** [comment]
You should use it as `response()->view()` not `response('Text')->view()`.

**Comment by crazycodr** [comment]
Ok, so how to i pass back a specific view when i have an error response? Such as a 403 or 404...

**Comment by brunogaspar** [comment]
@crazycodr  See if the following works

```php
return response()->view('my.view', [], 404);
```

**Comment by crazycodr** [comment]
Yup that works... and it gets confusing that calling view() itself you cannot send back a status code but with response()->view() you can... I think it merits to be documented as i can't see it in any of the pages i specified...

**Comment by juukie** [comment]
As an alternative you could do `return response(view('my.view'), 404);` as well.

**Comment by carusogabriel** [comment]
@crazycodr Can you please close this issue due to inactivity?
