### ISSUE TITLE
Scheduling documentation incorrect

### ISSUE THREAD

**Issue by renedekat** [laravel/docs#2395]
According to the documentation this should run on hourly on weekdays, between 8 and 17h in the Chicago timezone. What actually happens is that it will run every hour as the resulting CRON expression is 0 \* \* \* \* *

The chaining order for scheduling CRON jobs is very important as some methods will completely override the expressions. Switching hourly and weekdays solves the issue.

```
$schedule->command('foo')
          ->weekdays()
          ->hourly()
          ->timezone('America/Chicago')
          ->when(function () {
                return date('H') >= 8 && date('H') <= 17;
          });
```

```
$schedule->command('foo')
          ->hourly()
          ->weekdays()
          ->timezone('America/Chicago')
          ->when(function () {
                return date('H') >= 8 && date('H') <= 17;
          });
```

**Comment by jhoff** [comment]
I created a pull request so the chaining order is **less** important and both of your examples should produce the same expected output.

**Comment by renedekat** [comment]
Your da man!

**Comment by carusogabriel** [comment]
@renedekat Can you please close this issue due to inactivity?
