### ISSUE TITLE
Required PHP Extensions - Zip Extension required

### ISSUE THREAD

**Issue by ghost** [laravel/docs#2397]
Following the installation instructions at https://laravel.com/docs/5.2 I discovered that the OpenSSL, PDO PHP, Mbstring, and Tokenizer extensions were not enough for laravel to run.

The Zip extension must also be enabled:
![zip-required](https://cloud.githubusercontent.com/assets/726102/16619328/aa55e93a-435b-11e6-92d7-e2d9db32ff47.png)

Perhaps the documentation should be updated.

**Comment by GrahamCampbell** [comment]
It's not a required extension to install laravel using composer, or run laravel.

**Comment by morloderex** [comment]
@anthonybartoli unfortunatly you are misaken here as @GrahamCampbell is saying. The reason for your exeception is that the laravel/installer is using zlib behind the screens when it tries to extract the downloaded zip file from their repository. It's not a required extension i would recommend trying to use the composer create-package way of installing the framework if you don't want o have zlib installed on your machine :)

I hope this explains your issue @anthonybartoli.

**Comment by frutality** [comment]
Current (5.5) Laravel needs zip extension if you are going to use Dusk for attaching files in forms.

I wasn't able to use `$browser->attach('photo', __DIR__.'/photos/me.png');` feature until done this at Ubuntu:

`sudo apt-get install php7.1-zip`

My suggestion is to add a quick note about it on https://laravel.com/docs/5.5/dusk#attaching-files

**Comment by laurencei** [comment]
@frutality - I've submitted a PR for your comment for Taylor to review.

I'm going to close this ticket here, as the original issue has been identified to be the installer, not Laravel itself.
