### ISSUE TITLE
Polymorphic Relationships (morphOne)

### ISSUE THREAD

**Issue by jlndk** [laravel/docs#2423]
As I read through the documentation for [Eloquent's Polymorphic relations](https://laravel.com/docs/5.2/eloquent-relationships#polymorphic-relationsl) i noticed that there only was examples for `morphMany`. 

If you go through [Eloquent's code](https://github.com/illuminate/database/tree/5.2/Eloquent/Relations) there's also [morphOne](https://github.com/illuminate/database/blob/5.2/Eloquent/Relations/MorphOne.php) and [morphOneOrMany](https://github.com/illuminate/database/blob/5.2/Eloquent/Relations/MorphOneOrMany.php) relationships which isn't covered in the documentation.

**Comment by carusogabriel** [comment]
@jlndk Can you please close this issue due to inactivity?

**Comment by laurencei** [comment]
I'm going to close this ticket, as I believe the docs have been updated since this was posted.

If you find something still missing please feel free to submit a PR with the changes, or to open a new ticket.
