### ISSUE TITLE
Collection::slice() has no 3 parameters option.

### ISSUE THREAD

**Issue by kt81** [laravel/docs#2428]
in: https://laravel.com/docs/5.2/collections#method-slice

Collection::slice() is introduced as it can be passed 3 parameters to preserve original keys or not.
But actually this method does not use 3rd parameter and always preserves original keys.

I found the related issue and PR below. Since these conversation, It seems the document should be corrected.
https://github.com/laravel/framework/issues/13692
https://github.com/laravel/framework/pull/13698

**Comment by jhoff** [comment]
Pull request created to update docs starting at 5.2 onward:

> The returned slice will preserve keys by default. If you do not wish to preserve the original keys, you can use the `values` method to reindex them.

**Comment by kt81** [comment]
@jhoff Thank you! 😃
