### ISSUE TITLE
wrong variable names

### ISSUE THREAD

**Issue by friedrichschoene** [laravel/docs#2435]
In https://laravel.com/docs/5.1/routing#route-parameters the variables in the uri and the function parameters diverge,

`Route::get('posts/{post}/comments/{comment}', function ($postId, $commentId) {`

**Comment by GrahamCampbell** [comment]
Thanks, but I don't think there's a bug here?

**Comment by jhoff** [comment]
I agree. Seems correct as is. Also, see https://github.com/laravel/docs/pull/2433#issuecomment-235789610

**Comment by daison12006013** [comment]
@friedrichschoene {post} and {comment} are just ways to indicate that there will be a data to be passed to be accepted under the route. Then we're passing the values in the callback itself which doesn't mean we really know the exact variable name, but we now the parameter locations as we are using call_user_func/array
