### ISSUE TITLE
Why artisan command shortcuts not in docs?

### ISSUE THREAD

**Issue by anishdcruz** [laravel/docs#2439]
Hi,

i m not sure, if every laravel developer is aware of the fact that there is shortcut for artisan commands.

For example:

`php artisan route:list`

can be run as `php artisan r:l`

Not only the built in commands but custom commands work the same way.

This should be in docs, i wasted lots of time creating aliases.

Thanks

**Comment by gmsantos** [comment]
Shortcuts came from Symfony's Console component and it is already documented in Symfony docs.

http://symfony.com/doc/current/components/console/usage.html#shortcut-syntax

Not sure if everything should be documented... maybe a reference for Symfony docs

**Comment by jhoff** [comment]
It looks like the only thing from that usage page that isn't in the docs or listed when using --help is the shortcuts. I think it's a nice feature that probably warrants a mention in the docs. I'll write up an example and blurb to add.

**Comment by anishdcruz** [comment]
@jhoff Thanks

**Comment by carusogabriel** [comment]
@anishdcruz Can you please close this issue due to inactivity?
