### ISSUE TITLE
Example argument mistake in providers.md

### ISSUE THREAD

**Issue by pedzed** [laravel/docs#2441]
Commit in question: https://github.com/laravel/docs/commit/8d41537f3863b477f86ffe17a06410c1f05ff78b#diff-e4e89291b70d87f38561eb87b31ad9deR53

`Connection::class` is used, but that doesn't work. `'connection'` does work though. That's also [what the API says](https://laravel.com/api/5.2/Illuminate/Foundation/Application.html#method_singleton).

``` php
void singleton( string|array $abstract, Closure|string|null $concrete = null)
```

**Comment by Jeroen-G** [comment]
But it does works. See for example Illuminate\Auth\AuthServiceProvider.php at line 70.

**Comment by DCzajkowski** [comment]
I think it should work since `::class` just returns a string with a fully qualified class name.

**Comment by pedzed** [comment]
> But it does works.

Did you try it?

> I think it should work

I wouldn't create an issue for something that I didn't test `¯\_(ツ)_/¯`

Try it for yourself if you want: https://github.com/pedzed/laravel-uploadcare/blob/master/src/UploadcareServiceProvider.php#L43

**Comment by Jeroen-G** [comment]
The way you write it in the singleton should be the same as in the provides function.

**Comment by pedzed** [comment]
> The way you write it in the singleton should be the same as in the provides function.

Thanks, but I know that. It did not work when I tried it :wink: 

If you can confirm that it works (by trying), that would be nice. If not, that's fine as well.

**Comment by DCzajkowski** [comment]
Ok, so what happens when you do this in the line 43?:
```php
$this->app->singleton(Uploadcare::class, function () {
```

**Comment by pedzed** [comment]
> The way you write it in the singleton should be the same as in the provides function.

.

> Ok, so what happens when you do this in the line 43?:
> 
> ```php
> $this->app->singleton(Uploadcare::class, function () {
> ```


Thanks, but I know that. It did not work when I tried it :wink: 

If you can confirm that it works (by trying), that would be nice. If not, that's fine as well.

**Comment by Jeroen-G** [comment]
In [my Flickr package](https://github.com/Jeroen-G/Flickr/blob/master/src/FlickrServiceProvider.php) I was able to change both `'flickr'` in the singleton and provides() with `Flickr::class` and get it to work when I did `app()->make(JeroenG\Flickr\Flickr::class);`

**Comment by laurencei** [comment]
I'm going to close this issue, as the latest documentation appears correct.

If you think there is still an issue, please let me know or open a new ticket.
