### ISSUE TITLE
Add example of authorizeResource in authorization.md

### ISSUE THREAD

**Issue by jackfruh** [laravel/docs#2444]
While browsing through a preview of Matt's new book I noticed he mentioned using `authorizeResource()` in the constructor of a controller as a replacement for  having to do `$this->authorize(...)` for each function in the controller.

Looks like a pretty awesome time saver and would be great to see it in the docs.

**Comment by morloderex** [comment]
@jackfruh I think it has been removed in 5.3 of i am not mistaken :)

**Comment by jackfruh** [comment]
Ahh, thanks @morloderex !  
Do you know if it was removed, or does the functionality get replaced by something else?

**Comment by morloderex** [comment]
@jackfruh not entirely sure of that :) 
I think we will have to wait and see :)

**Comment by Omranic** [comment]
@jackfruh @morloderex The `authorizeResource` method still exists in L5.3 & it's here to stay, hopefully 😄 PR #2671 submitted to document this nice feature. 

[Source Code Reference](https://github.com/laravel/framework/blob/7d116dc5a008e69c97f864af79ac46ab6a8d5895/src/Illuminate/Foundation/Auth/Access/AuthorizesRequests.php#L82)

**Comment by laurencei** [comment]
I'm going to close this issue, as a PR was submitted for the docs, and Taylor gave his answer there. Thanks all.
