### ISSUE TITLE
Fundamental changes to routing in 5.2.42 needs documentation to assist users of prior 5.2 versions

### ISSUE THREAD

**Issue by pixeleffect** [laravel/docs#2448]
> Updates to this issue below include the change from calling this an "upgrade" to calling it a "change" that users need to be aware of.  The documentation recommendation in this original post remains as a recommendation, but the location should change to either the Routing documentation or to a new document that could be named Revisions to 5.2 or Changes.

The upgrade from 5.2.41 to 5.2.42 introduced changes to the RouteServiceProvider that changes the way routes are processed.  So long as a user moves both their RouteServiceProvider and routes.php to the new project, functionality remains.  If, however, a user starts a new project, it is unclear (especially to newer users) that the change has occurred, resulting in the Web Middleware being processed twice on the same route.  This results in sessions that do not function properly (new sessions on every request, regular session variables being carried to the new sessions, while flashed variables are removed).

The documentation is not clear about this change occurring and should be changed to include verbiage noting the change and how to properly handle the change.  My suggestion would be the following:

<a name="upgrade-5.2.42"></a>
### Routing and Route Service Provider

The default `App\Providers\RouteServiceProvider` has been updated to process all routes in `routes.php` through `web` middleware group.  Previous versions of 5.2 used middleware groups in the `routes.php` file to determine middleware processing.  If you use middleware groups in your `routes.php` file, you may inadvertently process a route through the same middleware multiple times.  Processing the same route through the `StartSession` middleware multiple times can cause unexpected behavior when dealing sessions, particularly flashed data and session creation.  There are two methods that can be used for migration, detailed below.
#### Method 1: Remove `web` middleware group from  `RouteServiceProvider`

This method involves updating the `RouteServiceProvider` to revert the file to the previous functionality.  After using this method, you will need to explicitly call middleware for individual routes or groups of routes in your `routes.php` file.
1. Remove the `mapWebRoutes` method from the `RouteServiceProvider`
2. Update the `map` method in the `RouteServiceProvider` to:

``` php
public function map(Router $router)
{
    $router->group(['namespace' => $this->namespace], function ($router) {
        require app_path('Http/routes.php');
    });
}
```
#### Method 2: Update `routes.php` File

> **Note:** This method will not function as intended if you have routes that should not have any middleware applied.  This method maintains the new function of requiring all routes to be processed through the `web` middleware group, but indicates necessary updates to prevent routes from being processed through `web` middleware group multiple times.

This method involves removing references to the `web` middleware group from `routes.php` in addition to updating other middleware groups to remove the middleware that is already processed by the `web` middleware group.
1. Remove any references to the `web` middleware group from `routes.php`.
2. Check all other middleware groups to ensure that they do not call any of the middleware that is within the `web` middleware group.

**Comment by GrahamCampbell** [comment]
There is nothing to upgrade. Upgrading is on the framework repo. You are not meant to mimic changes in laravel/laravel. That's there for new projects.

**Comment by pixeleffect** [comment]
The issue is when you create a project and then go to reuse code (the way you have created routes before).  This issue doesn't throw an error making the issue harder to track down than other issues.  If upgrading isn't the right terminology, maybe changes is.

The problem isn't that the change occurred, it is that the change itself isn't documented outside the GitHub comments on the routes.php file and the RouteServiceProvider.php file.  The routes.php file doesn't even address in the coded comments that the routes contained in it are processed through the web middleware by default or that the default location for the middleware declaration is now RouteServiceProvider.php.

As the change is a essentially a fundamental change in the way routing works out of the box, the change should be documented somewhere other than the minor changes to the documentation made under Routing.   Maybe Routing is the correct location to note the change.  Maybe a new Changes part to the documentation would be appropriate.

I'm open to suggestions, but I think it would be nice to provide this information for users that may be creating a new project, but trying to reuse code from the app side of a previous project.

**Comment by GrahamCampbell** [comment]
The upgrading guide is not for laravel/laravel though?

**Comment by pixeleffect** [comment]
Did I not just say that maybe Upgrades isn't the correct location for it, but maybe under the Routing documentation or creating a new document Changes?  The Laravel documentation overall does include laravel/laravel and making the documentation clearer when changes occur to laravel/laravel in the same minor version would help the entire community use Laravel better.  In all honesty, there should be a document maintained that spells out every change that is made to laravel/laravel in revisions to minor versions that can affect existing code currently being used within that minor version.

I am more than happy to assist with creating this document, but simply responding (twice now) that it doesn't belong in Upgrades doesn't assist anyone.

Documentation should be about helping people use the framework and eliminating as many roadblocks to that as possible.

**Comment by carusogabriel** [comment]
@pixeleffect Can you please close this issue due to inactivity?

**Comment by laurencei** [comment]
I'm going to close this ticket.

The upgrade guides for 5.4 and up all now make reference to "misc" changes in `laravel/laravel`. It is up to you if you want to mimic those changes across into your application. But they are not required (unless expicility mentioned).
