### ISSUE TITLE
Model Observer Documentation Missing

### ISSUE THREAD

**Issue by mdavis1982** [laravel/docs#2452]
The documentation for model observers is included up until Laravel 5.0: [5.0 Docs](https://laravel.com/docs/5.0/eloquent#model-observers)

The same documentation is not available in 5.1 or 5.2, but the code to enable the model observer functionality still exists in the `Model` class and observers still work.

Is this intentional (maybe the model observer functionality is going away?) or is it an oversight? If it's the latter I can submit a PR to add the documentation back.

**Comment by lagbox** [comment]
Lots of things go missing from the docs from version to version, could not tell you the answer why. I can only guess.

**Comment by laurencei** [comment]
I'm going to close this issue, as the new version of the documentation is quite comprehensive and contains all the sections of the Laravel Framework.

If you identify any further issues please let us know. Thanks!
