### ISSUE TITLE
Will 4.2 documentation remain online?

### ISSUE THREAD

**Issue by mpadev** [laravel/docs#2456]
Having a couple of projects in 4.2 active, and needing to look up things in the docs, I was wondering how long the 4.2 docs will remain online?

**Comment by sede2** [comment]
download it, just in case

**Comment by GrahamCampbell** [comment]
I'll always be in the docs repo anyway. :)

**Comment by carusogabriel** [comment]
@mpadev Can you please close this issue due to inactivity?
