### ISSUE TITLE
Tip: proces .env file in homestead doc

### ISSUE THREAD

**Issue by geoffreyvd** [laravel/docs#2476]
Hey guys, thanks for the awesome documentation!

I wanted to share my thanks with a contribution.

It is about the homestead documentation, I think it would be a good idea to talk about setting up multiple databases for multiple sites and to edit the .env file for each site to connect to the appropiate database. 

Well, I would have liked that information in that quickstart homestead doc, because i had to search for this information and it took a bit longer and i think this information would make the documentation complete.

Hope you guys appreciate it,

greetz

**Comment by svpernova09** [comment]
Is there something lacking here? https://laravel.com/docs/5.3/configuration#environment-configuration

If you're running multiple sites in the same homestead vagrant you should use the default values in `.env` and just need to change the database name in each `.env`.
