### ISSUE TITLE
Instructions for setting up Mail conflict when setting driver to ses.

### ISSUE THREAD

**Issue by tomdtn** [laravel/docs#2482]
When pulling in the Mail facade to a Lumen application, the config files `services.php` and `mail.php` have to be manually placed into the directory.

This is expected, but using the current [mail.php file](https://github.com/laravel/laravel/blob/v5.2.31/config/mail.php) is confusing and produces unexpected results when you set a username and password, but also have the ses key and secret key (you can technically get both from AWS). From what I can tell, you only need to setup the username, password, port and encryption properties in `mail.php` when using just SMTP and not any other driver.

I'm not sure if there is a bug in the code or something that I was missing, but setting both caused unexpected results (connection errors when deployed, silent errors other times). Whereas setting up the `services.php`with the ses driver, and limiting the `mail.php` file to only contain the driver and from properties (with address and name) gave the expected results.

**Comment by carusogabriel** [comment]
@tomdtn Can you please close this issue due to inactivity?
