### ISSUE TITLE
URL in accessing routes/api.php

### ISSUE THREAD

**Issue by noprobz09** [laravel/docs#2503]
Hello,

May I know on how to access or what is the URL to access the routes/api.php. I tried to access like http://localhost/{application_name}/api, it shows me "Sorry, the page you are looking for could not found". Thanks in advance :)

**Comment by HenryDinhh** [comment]
Because of `auth:api` middleware, you need an `api_token` coulumn in `users` Table include random string. You can access this by http://localhost/{application_name}/api?api_token={api_token} (or POST METHOD)

**Comment by lagbox** [comment]
Its just a file that defines routes. Use the 'uri' you setup in your routes to reach your routes.

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
