### ISSUE TITLE
Installing the passport frontend is missing the npm install / gulp steps

### ISSUE THREAD

**Issue by axyr** [laravel/docs#2520]
Reading the frontend quickstart, it seems like the copy pasters of the Vue components is all that is needed to get the frontend up and running, but that is not the case.

One needs to run `npm install` and run `gulp` to pack the app.js.

Also a clean install of 5.3 requires to include the app.js file in the welcome.blade.php by default, so this might be a recommended step as well.

Edit: maybe also suggest to run the `php artisan auth:make` and creating a User to allow creating clients and tokens?

**Comment by laurencei** [comment]
I'm going to close this ticket, as the new version of the documentation is now correct. Thanks.
