### ISSUE TITLE
The date validation rule does not accept values like "now"

### ISSUE THREAD

**Issue by jodiedunlop** [laravel/docs#2542]
According to the documentation the `date` validation rule accepts a value compatible with strtotime:

[date](https://laravel.com/docs/5.2/validation#rule-date)

> The field under validation must be a valid date according to the strtotime PHP function.

However, strtotime() will handle "now", but I find that in 5.2 the date validation rule does not consider this valid.

**Comment by laurencei** [comment]
Hi,

I've tested this, and it works as expected for Laravel 5.5 and above.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.

**Comment by afraca** [comment]
@laurencei  , perhaps reopen this, as it does fail with 'yesterday' for example. It's easy to see the problem:

https://github.com/laravel/framework/blob/v5.7.16/src/Illuminate/Validation/Concerns/ValidatesAttributes.php#L377-L383

This would be happening:
https://ideone.com/KD5YAN

in:
```
<?php
 
var_dump(strtotime('yesterday'));
 
var_dump(date_parse('yesterday'));
```
out:
```
int(1544400000)
array(13) {
  ["year"]=>
  bool(false)
  ["month"]=>
  bool(false)
  ["day"]=>
  bool(false)
  ["hour"]=>
  int(0)
  ["minute"]=>
  int(0)
  ["second"]=>
  int(0)
  ["fraction"]=>
  float(0)
  ["warning_count"]=>
  int(0)
  ["warnings"]=>
  array(0) {
  }
  ["error_count"]=>
  int(0)
  ["errors"]=>
  array(0) {
  }
  ["is_localtime"]=>
  bool(false)
  ["relative"]=>
  array(6) {
    ["year"]=>
    int(0)
    ["month"]=>
    int(0)
    ["day"]=>
    int(-1)
    ["hour"]=>
    int(0)
    ["minute"]=>
    int(0)
    ["second"]=>
    int(0)
  }
```
