### ISSUE TITLE
Upgrade guide 5.3 daemon

### ISSUE THREAD

**Issue by halaei** [laravel/docs#2566]
I have some details that you may consider putting them indo upgrade guide
1. The default 60 seconds timeout for daemon workers and how to change it in forge.
2. The fact that daemon workers don't work if PCNTL is not available.
3. Resource considerations in [this section](https://laravel.com/docs/5.3/queues#running-the-queue-worker) should be removed since the fork thing. Instead it should be noted that no file-description/db or cache connection should be opened in laravel boot process which is a very bad idea even if you don't need queues.
4. A note (if you think is needed) about Redis version which should be >= 2.6.0.

Thanks

**Comment by GrahamCampbell** [comment]
Daemon workers do work. You just need to set the timeout to 0.

**Comment by GrahamCampbell** [comment]
That means no timeout.

**Comment by halaei** [comment]
I think with forge UI, timeout can't be set for daemon workers. And may be
good to mention the default is 60.

On Aug 24, 2016 9:39 PM, "Graham Campbell" <notifications@github.com> wrote:

That means no timeout.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/docs/issues/2566#issuecomment-242139719>, or mute
the thread

**Comment by GrahamCampbell** [comment]
Timeout can be set for daemons if you have the extension.

**Comment by halaei** [comment]
Yes you can set "Maximum Seconds Per Job" to 10 and check "Run Worker As Daemon (Laravel 4.2+)"  in forge queue workers panel. But here is the resulting process: **no --timeout=10** in the ps aux output:

    php /home/forge/.../artisan queue:work sync --sleep=10 --daemon --quiet --tries=2 --queue=test_daemon

Please consider this with more attention! Thanks!

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
