### ISSUE TITLE
Update Doc mentioning to remove ThrottlesLogins

### ISSUE THREAD

**Issue by VinceG** [laravel/docs#2569]
In the upgrade notes it should state that in 5.3 unlike 5.2 the ThrottlesLogins trait is already included in Illuminate\Foundation\Auth\AuthenticatesUsers therefore should be removed form the AuthController.

Otherwise this will show:

```
Trait method hasTooManyLoginAttempts has not been applied, because there are collisions with other trait methods
```

**Comment by laurencei** [comment]
This is covered in the upgrade guide, as it says 

> the easiest way to upgrade your application to the new authentication controllers is to grab a fresh copy of each controller from GitHub and place them into your application

There are numerous other changes, so it doesnt make sense to list them individually.
