### ISSUE TITLE
Broadcasting docs should mention changing default driver to 'null'

### ISSUE THREAD

**Issue by rossbearman** [laravel/docs#2586]
This might be a bit of an edge case, but when upgrading a 5.2 application to 5.3 I ran into the following error when running the `ide-helper` commands, which parse many of the application files (always a good way to find broken imports after an upgrade!):

>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Class 'Pusher' not found

Prior to 5.3 the broadcasting.php config file had the default driver set to 'Pusher', even if you didn't have the Pusher libraries. Copying the config file from the repository resolved this (the driver now defaults to 'null'), but it's not mentioned in the docs and it would probably make sense to recommend copying the config in regardless of whether or not it already exists, as it would be present in a clean 5.3 install.

**Comment by laurencei** [comment]
Hi,

I've submitted a PR with these changes. Thanks for bringing it to our attention.
