### ISSUE TITLE
Document on Custom Validation Attributes

### ISSUE THREAD

**Issue by dionysiosarvanitis** [laravel/docs#2593]
Is this somewhere documented except for validation.php lang file?

````php
    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */
```

**Comment by paulodealmeida** [comment]
Look this https://laravel.com/docs/5.2/validation#localization

**Comment by dionysiosarvanitis** [comment]
@paulodealmeida the difference is that this one describes the way of translating the message of a rule (based on a specific attribute) but not the attribute itself.

**Comment by paulodealmeida** [comment]
@dionysiosarvanitis I can't understand your doubt.
I use this custom messages as the docs describes and it works. You just need to create a file named validation in resources/lang/en/validation.php.
How can we improve the documentation for other users?

**Comment by dionysiosarvanitis** [comment]
@paulodealmeida I am talking about the difference between [custom](https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L98) and [attributes](https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L115)?

**Comment by paulodealmeida** [comment]
good question...

**Comment by bobbybouwmann** [comment]
Custom is used for custom messages per rule. So if you want to change the the message for a the required rule for only the email field you do something like this
```
'custom' => [
        'email' => [
                'required' => ':attribute is required you silly user!',
        ],
],
```

Attributes are used to translate the name of the field to a human readable field. So lets say your column is called `end_date` then your validation message will look like this "The end_date field is required". You can then use the attributes array to change that
```
'attributes' => [
        'end_date' => 'End Date',
],
```
This will result in this "The End Date field is required"

**Comment by bobbybouwmann** [comment]
Created a PR for this ;)

**Comment by dionysiosarvanitis** [comment]
Issue can be closed since https://github.com/laravel/docs/pull/2658 merged.
