### ISSUE TITLE
Routing patterns

### ISSUE THREAD

**Issue by caiquecastro** [laravel/docs#2615]
In the docs for 5.2, there was a section for Global Constraints on the routing page: https://laravel.com/docs/5.2/routing.

But there is no docs for this feature on 5.3 docs.

```
/**
 * Define your route model bindings, pattern filters, etc.
 *
 * @return void
 */
public function boot()
{
        Route::pattern('resource', '[0-9]+');

        parent::boot();
}
```

or the where attribute for a single route.

```
Route::get('user/{name}', function ($name) {
    //
})
->where('name', '[A-Za-z]+');
```

**Comment by jlem** [comment]
This seems to keep happening.

@taylorotwell  nuked them initially here:
https://github.com/laravel/docs/commit/fa6e3c104238955c53fb37b1173c503d9411f640

Then @shssoichiro restored them here:
https://github.com/laravel/docs/commit/80b0aec7fb1ea2b893b0029c983c24edc27a303f

Then @taylorotwell nuked them again here, also prompting @BartHuis to ask why
https://github.com/laravel/docs/commit/40328f1c695228cc0a4244bd946592a631e19d77

Not sure why. This keeps happening. Could be Taylor is using a bad version of the docs for some reason, or really doesn't like this (very useful) feature.

**Comment by reedmaniac** [comment]
One of my developers noticed today and since we are migrating a Lumen 5.1 to Laravel 5.3, it would be *really* great if we knew what the status of this feature was.

**Comment by bobbybouwmann** [comment]
@reedmaniac As far as I know it's not deprecated, it's just not documented anymore! You can ask around on the laravel slack if this is feature that will be kept or not

**Comment by reedmaniac** [comment]
Well, I posted here.  I also asked @laravel on Twitter.  And it has been removed from the Docs twice by Taylor, who does have a habit of removing functionality that he no longer wishes to support.  Kind of hard to put any faith in it sticking around until I see it back in the Docs or Taylor speaks.

**Comment by taylorotwell** [comment]
It’s supported as far as I’m concerned. Feel free to PR the docs. Sometimes I remove stuff when heavy re-writing like I did for 5.2 and 5.3 and it could have been overlooked going back in.

**Comment by reedmaniac** [comment]
Thanks, @taylorotwell.  Will notify my team.
