### ISSUE TITLE
Missing section in Laravel 5.3 Event docs

### ISSUE THREAD

**Issue by jasonmccreary** [laravel/docs#2650]
The _Manually Registering Events_ link is broken within the [Events section](https://laravel.com/docs/5.3/events#manually-registering-events) of the Laravel Docs because the section itself is missing.

Not sure if it is missing or was removed without removing the link from the table of contents. Either way, there's an issue.

**Comment by bobbybouwmann** [comment]
The section exists in the Laravel 5.2 docs: https://laravel.com/docs/5.2/events#registering-events-and-listeners

I think it's removed to keep the documentation clear and showing the best practices. The functionality for manually creating events still exists as far as I know. 

I will do a PR to the 5.3 documentation ;)

**Comment by laurencei** [comment]
Closing as this issue has been resolved.
