### ISSUE TITLE
Notifications: MailMessage greeting() method doesn't exist

### ISSUE THREAD

**Issue by gilbitron** [laravel/docs#2662]
The 5.3 docs mention a `greeting()` method:

```
return (new MailMessage)
                ->greeting('Hello!')
                ->line('One of your invoices has been paid!')
                ->action('View Invoice', $url)
                ->line('Thank you for using our application!');
```

However the actual method doesn't seem to exist.

**Comment by michaeldyrynda** [comment]
The `greeting` method exists on the `SimpleMessage` class, which `MailMessage` extends.

**Comment by gilbitron** [comment]
I have v5.3.4 installed and it is definitely missing from the `SimpleMessage` class. It must have been added in a later release.

**Comment by michaeldyrynda** [comment]
Looks like it was tagged in [5.3.5](https://github.com/laravel/framework/commit/cef70172b02f20b38281b3360069a951df2baedc#diff-cadeb6a5af67fbe7fdcb57050bb64edf) 👍
