### ISSUE TITLE
Could eloquent model convention for table names include a multiple-word example?

### ISSUE THREAD

**Issue by rosswintle** [laravel/docs#2679]
Note: My first Laravel issue, and I'm a realative Laravel beginner... please be nice. Happy to pull-request if needed, but could do with some input first.

In eloquent.md's Eloquent Model Conventions section the convention by which model class names are converted to database table names isn't clear and would benefit hugely from having a multiple-word example as the current example used is "Flight" -> "flights".

Given that the "Flight" model is used throughout the document, I don't propose changing that, but perhaps we could add in a second example as such:

> Note that we did not tell Eloquent which table to use for our Flight model. By convention, the "snake case", plural name of the class will be used as the table name unless another name is explicitly specified. So, in this case, Eloquent will assume the Flight model stores records in the flights table. As another example, a `BoardingPass` model class would be assumed to be using the table `boarding_passes`.

This choice of additional example may be interesting.  Another note: is Eloquent clever enough to pluralise "Pass" to "passes"?

**Comment by michaeldyrynda** [comment]
> Another note: is Eloquent clever enough to pluralise "Pass" to "passes"?

It certainly is. Eloquent uses a [Doctrine library](https://github.com/doctrine/inflector) to handle pluralisation. 

```
>>> str_plural('boarding_pass', 2);
=> "boarding_passes"
```

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and the Eloquent section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
