### ISSUE TITLE
[question] How do I efficiently tear through facades when looking for info in Laravel API docs?

### ISSUE THREAD

**Issue by rulatir** [laravel/docs#2698]
This is only an example: suppose I found a code snippet that uses the `DB::statement()` idiom. I want to  find the documentation of the `DB::statement()` thing in Laravel API docs, but I am encountering an obstacle: <strong>`DB` is a facade</strong>. Typing `DB` into the search field on the API documentation site takes me to the documentation for `\Illuminate\Support\Facades\DB`, but that page only contains the documentation of `Facade` methods. The documentation for the `statement()` method can certainly be found on the documentation page of the class that "hides" under the DB facade, but I know no viable method of determining what that implementing class is. The trail is lost at this point.

Is there a general, simple (O(1)), human-executable method for tearing through facades in Laravel API documentation?

**Comment by lagbox** [comment]
There is a facade class reference directly in the docs.

[Facade Class Reference](https://laravel.com/docs/5.3/facades#facade-class-reference)
