### ISSUE TITLE
Validation - active_url

### ISSUE THREAD

**Issue by a3020** [laravel/docs#2705]
According to https://laravel.com/docs/5.3/validation#rule-active-url:

> The field under validation must be a valid URL according to the checkdnsrr PHP function. 

However, `dns_get_record` is used instead of the `checkdnsrr` function: https://github.com/illuminate/validation/blob/master/Validator.php#L1637

Seems to have changed in this PR: https://github.com/laravel/framework/pull/11246/files

**Comment by laurencei** [comment]
Closing as this issue has been resolved.
