### ISSUE TITLE
Envoy: Should the hostname in the very first example have array brackets?

### ISSUE THREAD

**Issue by jamesggordon** [laravel/docs#2715]
The very first task example in the Envoy docs defines a host as follows:

```
@servers(['web' => ['user@192.168.1.1']])
```

Whilst this works when running tasks, if you issue `envoy ssh web` then you get this error:

_Array to string conversion in /Users/name/.composer/vendor/laravel/envoy/src/Console/SshCommand.php on line 38_

Removing the brackets from the hostname so that the line reads like this, works:

```
@servers(['web' => 'user@192.168.1.1'])
```

I noticed that none of the other examples include the brackets, so I can only assume that they are not supposed to be there in this instance either.

**Comment by bobbybouwmann** [comment]
Created a PR for you ;)

**Comment by jamesggordon** [comment]
Thanks @bobbybouwmann!

**Comment by laurencei** [comment]
Closing as this issue was discussed in the PR.
