### ISSUE TITLE
Artisan documented function does not exist

### ISSUE THREAD

**Issue by several27** [laravel/docs#2718]
I believe that the function `arguments()` is either missing from the codebase or was documented by mistake.

Exactly, I'm taking here about the https://github.com/laravel/docs/blob/5.3/artisan.md file at lines 269-271. 

```
If you need to retrieve all of the arguments as an `array`, call the `arguments` method:

    $arguments = $this->arguments();
```

The alternative working function is `getArguments()`.

(First time submitting an issue here, sorry if have made any mistake, can submit a PR if it is indeed a bug either in docs or code)

**Comment by chay22** [comment]
Judging from source, [`arguments()`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Console/Command.php#L235) does exists in Laravel 5.3. Take a look at the version you're using. It's probably 5.2 or something.

**Comment by several27** [comment]
I was using 5.2 indeed. Sorry about that.
