### ISSUE TITLE
Incorrect view script names

### ISSUE THREAD

**Issue by wojtekn** [laravel/docs#2729]
Hello,

I've started working on my first Laravel project and I've got stuck quickly - on view rendering. I couldn't make view rendered, it just kept displaying variable name. 

After looking for some google resources and playing with documentation examples I think docs may show incorrect view script name:

```
 resources/views/greeting.php
```

It works when I change it to following:

```
resources/views/greeting.blade.php
```

This is the affected documentation page:

https://github.com/laravel/docs/blob/5.3/views.md

If it's bug, I can submit PR.

Wojtek

**Comment by bobbybouwmann** [comment]
Well it's documentation, I don't think you can call it a bug ;)

However you are right. It should be `greeting.blade.php` and also `profile.blade.php`

I already created the PR for you ;)

**Comment by wojtekn** [comment]
@bobbybouwmann it's docs repository so it's docs bug :-) Thanks for fixing this!
