### ISSUE TITLE
kernel middleware changed, not changed in docs

### ISSUE THREAD

**Issue by BartHuis** [laravel/docs#2733]
if you look at the docs about middleware, its mentioning a chunk of code from the kernel.php, but the kernel.php is changed:
https://github.com/laravel/laravel/blob/master/app/Http/Kernel.php
because the api part in $middlewareGroups had other basic middleware than mentioned in the docs.
Of course i can send in a pull request with the new code, but can someone please explain in that part of the docs whát middleware is exactly attached to the api by default?
Thanks,
Bart

**Comment by BartHuis** [comment]
?

**Comment by Jeroen-G** [comment]
I don't get your question. I think you can just send a PR changing it.

**Comment by seanmangar** [comment]
Seems like it matches the documentation at https://laravel.com/docs/5.3/middleware ?

**Comment by BartHuis** [comment]
hmm, i see, i think it was an old one then...
