### ISSUE TITLE
Highlight Current Page Link

### ISSUE THREAD

**Issue by alberto1el** [laravel/docs#2738]
When visiting a page on the documentation, the navigation does not visually reflect which page is being displayed (the current page link is not highlighted).

On bootstrap and other css frameworks that is achievable with the 'active' class on the li element.

I have seen a few examples for doing that with javascript 
[here](http://stackoverflow.com/questions/11533542/twitter-bootstrap-add-active-class-to-li) , [here](http://stackoverflow.com/questions/24626353/toggle-active-class-between-li-by-bootstrap) (for bootstrap), although I am not fully aware of the build process for the documentation and the css or javascript libraries that it uses.

**Comment by laurencei** [comment]
Closing as this issue has been resolved.
