### ISSUE TITLE
Link vue component broken

### ISSUE THREAD

**Issue by Wit3** [laravel/docs#2740]
The Frontend page ( https://laravel.com/docs/5.3/frontend ) has a broken link near this chapter 

> Writing Vue Components
> 
> By default, fresh Laravel applications contain an Example.vue Vue component located in the resources/assets/js/components directory. The Example.vue file is an example of a single file Vue component which defines its JavaScript and HTML template in the same file. Single file components provide a very convenient approach to building JavaScript driven applications. The example component is registered in your app.js file:

link broken : https://vuejs.org/guide/application.html#Single-File-Components

new link from vuejs : http://vuejs.org/guide/single-file-components.html

**Comment by laurencei** [comment]
Closing as issue has been fixed.
