### ISSUE TITLE
signature of 'has' of Illuminate/Support/MessageBag has been changed in 5.3

### ISSUE THREAD

**Issue by fieteboerner** [laravel/docs#2742]
The `has` method now (5.3) requires a parameter (no longer an optional parameter). After researching in the api docs I have found the `hasAny`, which do what I want.

It would be nice if this change will be listed in the [Upgrade Guide](https://laravel.com/docs/5.3/upgrade) form 5.2 to 5.3.

Thanks.

**Comment by Jeroen-G** [comment]
The upgrade guide seems to be for major changes, everything else should be listed in the changelog I think.

**Comment by fieteboerner** [comment]
I thougt the upgrade guide is a checklist for a developer to upgrade an application which is using the common functionality of Laravel, without any special adjustments, core adaptions and fancy plugins. 
And I would appreciate if changes of signatures of common used methods will be mentioned. And I think that the `MessageBag` is a common used class in template files.

A long  paragraph is not necassary, but a simple one-liner would be nice.

**Comment by Jeroen-G** [comment]
Then send a PR 😄
