### ISSUE TITLE
[Task Scheduling] Include mention of effect of maintenance mode

### ISSUE THREAD

**Issue by afraca** [laravel/docs#2745]
Just bumped into this. Not insanely important, but it was quite annoying why our scheduled commands were not running. We have some applications in 'maintenance' for a long time, so there's still quite a lot going on there. 

This would affect:
https://laravel.com/docs/5.3/scheduling

**Comment by afraca** [comment]
In addition to this: it's nowhere clear how the developer can affect this:
https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/Scheduling/Event.php#L55

**Comment by Jeroen-G** [comment]
How exactly is scheduling affected?

**Comment by afraca** [comment]
Nothing that is scheduled will execute.
