### ISSUE TITLE
Issue With Form Request laravel 5.2

### ISSUE THREAD

**Issue by sanchitpuri13** [laravel/docs#2770]
Hi,
I am developing rest services and using Form request to validate the request data. I have defined the required rules in the rules function of the particular form request class as shown below:-

public function rules()
    {
        return [
            'email' => ["required", "email"],
            'password' => ["required"]
        ];
    }

Inside My controller action i have injected this Form request class instead of default Request class.

Now when i am hitting the web service and passing both the param's in request it is working fine but if i am not passing any of the param in service as shown below in Json then an exception is occurred without any exception message as i have modified the handler to handle exception and response a string that contains exception code, message, line and file which is also shown below

Incomplete Request Body:- (Without password key and value)
{
    "email" : "xxxx@example.org",
}

Code in Handler.php

if ($request->ajax()) {
              return response()->json([
                      'success' => false,
                      'data' => 'Exception',
                      'messages' => "Code = ".$e->getCode(). " msg = ".$e->getMessage()." At ". $e>getLine()." in ". $e->getFile(),
                ]);
        }

Server Response:-
{
  "success": false,
  "data": "Exception",
  **"messages": "Code = 0 msg =  At 107 in Path\to\ProjectFolder\vendor\laravel\framework\src\Illuminate\Foundation\Http\FormRequest.php"**
}

Kindly provide you valuable inputs. Thanks in Advance

**Comment by laurencei** [comment]
Hi there,

Welcome to Laravel and we are glad to have you as part of the community.

Unfortunately this GitHub area is not a support area for general application issues. This is only for issues/bugs with the framework code itself.

Can I suggest closing your issue ticket here? Instead try asking your question on one of the many great community support areas that will likely give you a better answer more quickly:

- Laravel Slack (https://larachat.co/) 
- Laravel.io Forum (https://laravel.io/forum)
- Laracasts Forum (https://laracasts.com/discuss)
- StackOverflow (http://stackoverflow.com/questions/tagged/laravel)

Thanks in advance.
