### ISSUE TITLE
`whereLoose` removed without mention?

### ISSUE THREAD

**Issue by martindilling** [laravel/docs#2773]
I'm really not a writer for this kind of nice documentation :/

But in the 5.3 upgrade guide about the collections `where` method using loose comparison by default
https://github.com/laravel/docs/blob/5.3/upgrade.md#collection-where-comparison-methods-are-loose-by-default
you might want to mention that the `whereLoose` method is just plain removed without mention anywhere :)
And it was a bit annoying to find as I was searching for `where(` to find the instances I needed to check ;)

https://github.com/laravel/framework/pull/12470

**Comment by paulofreitas** [comment]
This was fixed by #3129. 👍
