### ISSUE TITLE
[5.3] Passport: Creating A Password Grant Client

### ISSUE THREAD

**Issue by davycheung** [laravel/docs#2775]
On the passport page (https://laravel.com/docs/master/passport#password-grant-tokens), the command listed to create a password grant token is: 

`php artisan passport:client --password`

Looking through the source code the actual command is:

`php artisan passport:client --personal`

**Comment by michaeldyrynda** [comment]
Aren't `--password` and `--personal` two different grant types? Reading through the docs and the source code, it seems correct as it is to me.

**Comment by bobbybouwmann** [comment]
> Creating A Password Grant Client

> Creating A Personal Access Client

Two different things ;)

**Comment by davycheung** [comment]
I had Laravel Framework 5.3.9 installed. Whenever I tried to run:

`php artisan passport:client --password`

I get the following exception:

`[Symfony\Component\Console\Exception\RuntimeException] `
`The "--password" option does not exist.`

On laravel 5.3.18  its working fine though, looks like its documented properly, I'm closing this.
