### ISSUE TITLE
Multi-vagrant setup

### ISSUE THREAD

**Issue by MunGell** [laravel/docs#2792]
Hi there,

I am using Homestead on daily basis and created a simple tool to help me manage multiple Homesteads and other VMs on my local machine: https://github.com/MunGell/vgm

It could be helpful for other developers as well, although I am not sure if it is worth mentioning in Homestead docs in "Daily Usage" section. At the moment it advises to use a Bash function for global installations.

I can create a PR if there will be any interest in it.

**Comment by svpernova09** [comment]
Sorry for the delay. Multi vagrant isn't something we'd want to have to support with Vagrant and I'd rather leave it to the user to set up and configure.

Thanks!
