### ISSUE TITLE
Using Homestead on a Windows machine

### ISSUE THREAD

**Issue by orrd** [laravel/docs#2805]
The Homestead documentation mentions specific instructions for Windows in several sections, but the crucial "Installing Homestead" section gives instructions that won't work on a Windows machine.  There are several discussions on online forums from people who got stuck at that same step.

There are several different techniques that can be used to install Homestead under Windows, but the simplest is using Git Bash.  Should I submit a pull request to add a note about how to install Homestead under Windows in the "Installing Homestead" section of that documentation page?

**Comment by svpernova09** [comment]
Hi @orrd 

Any docs that explain the windows process would certainly help if the existing docs are unclear. I'm also interested in making sure we're able to install Homestead as easy on Windows as we can on Linux and OS X. I'd much rather solve the problem in the Homestead repo/app than having to add docs that is a workaround.
