### ISSUE TITLE
5.2 to 5.3 upgrade doesn't mention routes moved

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [laravel/docs#2818]
Unless I missed it, the 5.2 to 5.3 upgrade guide doesn't mention that routes have been moved to a routes directory.

**Comment by michaeldyrynda** [comment]
If you're doing an upgrade, it doesn't really matter. Your `RouteServiceProvider` is still pointing to the old ones. Moving to a `routes` directory structure is entirely up to you.

**Comment by ChrisThompsonTLDR** [comment]
Then the upgrade guide maybe shouldn't reference the stock `routes/web.php` that needs to be updated?

> You should also make sure that you are calling the Auth::routes() method in your routes/web.php file. This method will register the proper routes for the new authentication controllers.

**Comment by devanes** [comment]
I also think it should be mentioned. If only to inform people and to give them the choice whether they want to implement the new system.

**Comment by laurencei** [comment]
The upgrade guides for 5.4 and up all now make reference to "misc" changes in the `laravel/laravel` repo that you can optionally choose to bring across to your project. But they are not required as part of the upgrade - it is an optional decision for you to make.

**Comment by michaeldyrynda** [comment]
`make:auth` is intended as a scaffold operation, which wouldn't ordinarily happen as part of an upgrade between versions, imo

**Comment by rbrisita** [comment]
Ideally, yes.

Quick Guide for those interested:

Copy v5.3 files:

* `app/Providers/RouteServiceProvider.php`
* `app/Http/Kernel.php`

Copy v5.2 `routes.php` file to `web.php` file:

* `cp app/Http/routes.php routes/web.php`

Make sure `app/Http/Middleware/VerifyCsrfToken.php` contains endpoints that don't need web route protection by populating the `$except` member.

Test routes and feel free to delete `app/Http/routes.php` when satisfied with the outcome.
