### ISSUE TITLE
Contribution guide could mention howto setup a laravel development environment

### ISSUE THREAD

**Issue by tback** [laravel/docs#2838]
I never tried contributing to laravel, but I just tried to get started not knowing if this will ever result in a contribution or not. 

Anyhow:
It'd be great if the contribution guide could mention how to setup an environment for hacking on Laravel. If this happens to be homestead or valet this is done in a sentence and gives peace of mind to the starting contributor. It'd also be great if this would explain howto run the testsuite locally.

**Comment by svpernova09** [comment]
Homestead would certainly be a viable option for local development environment. Especially if you're not on MacOS
