### ISSUE TITLE
Document what Composer settings are needed to use the Eloquent ORM

### ISSUE THREAD

**Issue by kevinburke** [laravel/docs#2854]
I'm trying to use the Eloquent ORM in my project. Reading this page: https://laravel.com/docs/5.0/eloquent

It's unclear which settings I need in my composer.json to install Eloquent.

**Comment by michaeldyrynda** [comment]
You don't need anything in your `composer.json` to install Eloquent - it's included out of the box with a Laravel installation.

Are you trying to use Eloquent in a standalone project? If so, the documentation is in the [component repository](https://github.com/illuminate/database)

**Comment by kevinburke** [comment]
Yes - I'm trying to use it in a standalone project. I guess the problem is that I wasn't sure how or where to find that documentation, from the page I linked.

**Comment by michaeldyrynda** [comment]
The components are mostly documented in their own repos, but it's not clear from the main docs this is possible. I'm not sure that the Laravel docs ought to show how to use the components independently, though, as they're more around using the full stack framework.

It'll come down to @taylorotwell's preference as to where best - if at all - to house this info, even if that's just linking off to [Torch](https://github.com/mattstauffer/torch).

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
