### ISSUE TITLE
app.blade.php snippet in Blade template docs missing a @endsection?

### ISSUE THREAD

**Issue by imabug** [laravel/docs#2862]
Is the app.blade.php template snippet (in the Template Inheritance section) missing a @endsection, maybe instead of @show is or after that if @show is part of the template?

```
<!-- Stored in resources/views/layouts/app.blade.php -->

<html>
    <head>
        <title>App Name - @yield('title')</title>
    </head>
    <body>
        @section('sidebar')
            This is the master sidebar.
        @show
        @endsection <----- needed @endsection?
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>
```

**Comment by brayniverse** [comment]
I can't find anything documented, but I think `@show` closes the section and immediately yields it. This allows you to have whatever you declare in your master template as the "default" content, and have it overwritable.

See the [Blade Compiler](https://github.com/laravel/framework/blob/5.3/src/Illuminate/View/Compilers/BladeCompiler.php#L448) to see it actually closes (yields) the section.
