### ISSUE TITLE
Document how to convert a DB::select result set to a Eloquent Model instance

### ISSUE THREAD

**Issue by kevinburke** [laravel/docs#2867]
I need to make a raw database query using Laravel:

```php
    $results = DB::select("SELECT * FROM members 
        INNER JOIN (several other tables) 
        WHERE (horribly complicated thing) 
        LIMIT 1");
```

I get back a plain PHP StdClass Object with fields for the properties on the members table. I'd like to convert that to a Member (an Eloquent model instance), which looks like this:

```php
    use Illuminate\Database\Eloquent\Model;

    class Member extends Model {
    }
```

I'm not sure how to do it since a Member doesn't have any fields set on it, and I'm worried I will not initialize it properly. What is the best way to achieve that?

The Eloquent documentation doesn't explain how to do this. 

(I'm also interested in the answer to this, not just seeing it documented - I also asked here: http://stackoverflow.com/q/40855116/329700)

**Comment by michaeldyrynda** [comment]
You ought to be able to just new them up;

```php
$members = collect();

foreach ($results as $result) {
    $members->push(new Member($result));
}
```

You will, however, need to be mindful of guarded properties on your model, which will trigger a `MassAssignmenException`

**Comment by ejunker** [comment]
Also take a look at `hydrate()` https://laravel.com/api/5.3/Illuminate/Database/Eloquent/Model.html#method_hydrate

**Comment by saidbakr** [comment]
The following example from a model named `Job` and its relation with model named `Cavity` demonstrates in the commented code the ordinary situation using `belongsToMany` method, but the  conditional clauses in the `belongsToMany` chained methods has limitations, so I use `DB::select` to execute custom query.
I need to get the same collection from my custom query like the `belongsToMany` i.e I get collection of related Cavity models.
```php
public function currentCavities($startDate = null, $endDate = null)
    {
        if (is_null($startDate)){
            $startDate = $this->started;
        }
        if (is_null($endDate)){
            $endDate = ((is_null($this->completed))? \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',date('Y-m-d H:i:s')):$this->completed);
        }
       //dd($startDate,$endDate);
       /* return $this->belongsToMany(Cavity::class,'cavity_actions','job_id','cavity_id')
                ->wherePivot('action_id',config('fox.actions')['installCavity'])
                ->wherePivot('created_at','>=',$startDate)
                ->wherePivot('created_at','<=',$endDate);*/
        $sql = 'SELECT cavities.*, cavity_actions.created_at, cavity_actions.closed, cavity_actions.notes FROM cavities LEFT JOIN cavity_actions ON cavities.id = cavity_actions.cavity_id
                WHERE cavity_actions.job_id = :jobId
                AND cavity_actions.action_id = :actionId
                AND IFNULL(cavity_actions.closed,:endDate1) >= :endDate2
                AND cavity_actions.created_at <= :startDate';
        $data = ['jobId' => $this->id, 'actionId' => config('fox.actions')['installCavity'], 'endDate1' => $endDate, 'endDate2' => $endDate, 'startDate' => $startDate];
        $query = \DB::select($sql, $data);
        $collection = new \Illuminate\Support\Collection($query);
        dd($collection);
    }
```  
The following is the output of `dd($collection);`:
```
Collection {#551 ▼
  #items: array:6 [▼
    0 => {#819 ▶}
    1 => {#810 ▶}
    2 => {#803 ▶}
    3 => {#809 ▶}
    4 => {#799 ▶}
    5 => {#806 ▶}
  ]
}
```

**Comment by laurencei** [comment]
I'm going to close this issue.

The docs have been updated significantly since this was posted, and the Eloquent section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
