### ISSUE TITLE
Document $keyType parameter on model

### ISSUE THREAD

**Issue by kevinburke** [laravel/docs#2869]
I am using a UUID as a primary key in an Eloquent model, but getting funky results. I filed https://github.com/laravel/framework/issues/16576, and was told I should be setting `$keyType = 'string'` in my Eloquent model.

Unfortunately this parameter is undocumented - it's not present on the https://laravel.com/docs/5.3/eloquent page.

**Comment by RRorg** [comment]
Bumping this up. Only found the `$keyType` attribute by chance.

**Comment by decadence** [comment]
Do a PR, nobody cares about issues on this repo.

**Comment by RRorg** [comment]
oh well, will try to get around this some time soon ¯\_(ツ)_/¯

**Comment by laurencei** [comment]
Closing as this issue has been fixed.
