### ISSUE TITLE
Document Schedule withoutOverlapping requiring name

### ISSUE THREAD

**Issue by alexbowers** [laravel/docs#2884]
`name()` must be called on a schedule `call` before `withoutOverlapping` can be called, otherwise you get a `LogicException`.

**Comment by laurencei** [comment]
I think this is an edge case that probably would be confusing in the docs. If/when people run into this edge case, the Logic Exception provides a clear solution to the problem.

I'm going to close this ticket, but if you think you can write a PR for how we could add it to the docs without being overwhelming, you are welcome to do so.

Thanks.
