### ISSUE TITLE
Get fully qualified class name with ::class instead of using string

### ISSUE THREAD

**Issue by leonfancy** [laravel/docs#2952]
A lot of sections in this documentation instructs using string when a fully qualified class name is needed, such as defining a Eloquent relationship:

```
$this->belongsTo('App\User');
```

I recommend to use `App\User::class` here instead. You will get two be benefits:

- Syntax highlight and syntax check if you have typo in the class name.
- Easier refactor the class name with the help of IDE such as PhpStorm.

**Comment by rossjcooper** [comment]
I also prefer to use this way of getting class names but I think this is more down to personal preference.

**Comment by royduin** [comment]
There where some PRs for this:
- https://github.com/laravel/docs/pull/2095
- https://github.com/laravel/docs/pull/2098
- https://github.com/laravel/docs/pull/2150
- https://github.com/laravel/docs/pull/2220

Which are all closed. @taylorotwell his comments:

> It makes it ambiguous that you have to pass the fully qualified namespace when new users view the docs.

> I would have to show the imports on each example otherwise people would be confused why they couldn't just copy and paste it.

**Comment by laurencei** [comment]
I'm going to close this issue.

Taylor's position on this is pretty clear.
