### ISSUE TITLE
Routing - Implicit Model Binding

### ISSUE THREAD

**Issue by Juddling** [laravel/docs#2955]
https://github.com/laravel/docs/blame/5.3/routing.md#L236

> In this example, since the Eloquent `$user` variable defined on the route matches the `{user}` segment in the route's URI, Laravel will automatically inject the model instance that has an ID matching the corresponding value from the request URI.

I found this explanation to be quite confusing, because as far as I am aware, the reason the model instance is injected is because the parameter is type-hinted.

**Comment by GrahamCampbell** [comment]
Right, so:

> In this example, since the Eloquent $user variable defined on the route matches the {user} segment in the route's URI,

This is true of all model binding, so is very important.

> I found this explanation to be quite confusing, because as far as I am aware, the reason the model instance is injected is because the parameter is type-hinted.

This part is only true of the implicit model binding.

---

Thanks for the report. Please feel free to send a PR to the docs to make these 2 things clear. :)

**Comment by Juddling** [comment]
https://github.com/laravel/docs/pull/3110

**Comment by laurencei** [comment]
I'm closing this issue, as a PR was done.
