### ISSUE TITLE
Review per-project homestead instructions for homestead

### ISSUE THREAD

**Issue by seanmangar** [laravel/docs#2957]
I'm proposing a small change to the per-project homestead instructions.

Recently after running `composer update`, my homestead updated from 3.0.2 to 3.1.* and my vagrant box could no longer start up. I initially had no idea the homestead update was causing this as the error was thrown by vagrant. Turns out this happened because I had initially followed the per-project homestead instructions, but was using an outdated box.

Environment:
**Vagrant box**: laravel/homestead   (virtualbox, 0.5.0)
**PHP version in box**: PHP 7.0.3-13
**Laravel framework**: 5.2.45 
**Homestead**: 3.1.0

Some suggestions would be:
1. To run `composer require laravel/homestead --dev` with the right version for the vagrant box being used. E.g  `composer require laravel/homestead:3.0.* --dev`. The reason being that this can lead to unexpected errors if used with outdated vagrant boxes as happened in my case. 
2. Make it clearer that there are compatibilities to be followed depending on the vagrant box being used. https://laravel.com/docs/5.3/homestead#old-versions . We could also add a row that box 0.5.0 is only compatible with homestead 3.0.2.

Let me know what you guys think.
@taylorotwell: I would like your input on this please.

**Comment by svpernova09** [comment]
Sorry for the ridiculous delay in responding.

You should always run the most recent version. I just opened a PR to remove the old version documentation because now that Homestead supports all current supported PHP versions, there should be no need to use older Homestead versions or Base boxes.

Thanks.
