### ISSUE TITLE
Clarify where to put app logic.

### ISSUE THREAD

**Issue by andrisi** [laravel/docs#2964]
https://laravel.com/docs/5.3/structure#the-http-directory says "Think of the Console and Http directories as providing an API into the core of your application. The HTTP protocol and CLI are both mechanisms to interact with your application, but do not actually contain application logic."

Ok, so HTTP and CLI are just entry points, but not places to implement app logic. Then when explaining the HTTP directory, it says "The Http directory contains your controllers, middleware, and form requests. Almost all of the logic to handle requests entering your application will be placed in this directory.".

What's missing is a clear explanation of where to put the actual application logic. Not one related to handle HTTP requests, or Console commands, or queue Jobs - but the actual place to implement them.

**Comment by CurosMJ** [comment]
Your application logic would be your controllers, views and models, out of which controllers are a part of the Http layer, while views reside in resource folder, and models reside in the app/ directory.

And, It is completely okay to have your own structure inside the app directory. 

I don't see any ambiguity in the docs.

**Comment by andrisi** [comment]
If controllers are part of the HTTP layer, than they're not the answer, as HTTP is just one way to invoke application logic, beside console commands, queued jobs, etc. So we created an app\Core folder and put app logic (or more like functionality) there.

**Comment by CurosMJ** [comment]
I think I should put it this way : the app/ folder contains the business
logic, while Console/ and Http/ folders contain Console and Http specific
logic.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.

**Comment by mscharlton** [comment]
@laurencei  - mind putting a reference link to resolve this particular thread?  it would help others who have found this via a Google search, like myself lol.  I was wondering the exact same thing as I am writing a console/arstisan command and trying to be "clean" in Laravel, which is still new to me.

**Comment by laurencei** [comment]
There's no one specific answer to this topic. The logic can go anywhere, it really depends on your app and a number of other factors.

The entire docs have been re-written, and "hints" to where certain logic can go is scattered throughout the docs depending on the topic/situation.

This can be one starting point as well: https://laravel.com/docs/5.6/structure
