### ISSUE TITLE
5.2 to 5.3 does not mention change in routeMiddleware 'auth'

### ISSUE THREAD

**Issue by eborio** [laravel/docs#3001]
Following the process of migration from 5.2 to 5.3 does not mean that it should be changed in ```Kernel.php```

```php
protected $routeMiddleware = [
     'auth' => \App\Http\Middleware\Authenticate::class,
    ...
];
```
to
```php
protected $routeMiddleware = [
     'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
    ...
 ];
```
Failure to perform the mentioned change results in null when using Passport to obtain the user corresponding to the token

**Comment by laurencei** [comment]
The `\App\Http\Middleware\Authenticate::class` should still be in your local application though aftger the upgrade, so I dont see why this change is required?
