### ISSUE TITLE
Inaccuracy/incomplete info about Laravel Passport token lifetimes

### ISSUE THREAD

**Issue by brunen9** [laravel/docs#3049]
[Here](https://github.com/laravel/docs/blob/5.4/passport.md#token-lifetimes) docs says:

> By default, Passport issues long-lived access tokens that never need to be refreshed

But it is not right since Nov 2016, and at present default TTL is only 1 year.

**Comment by laurencei** [comment]
Thanks @brunen9,

I've submitted a PR for this to be fixed.
