### ISSUE TITLE
[Suggestion] Adding documentation about the usage of Illuminate\Support\Manager

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/docs#3061]
The `Illuminate\Support\Manager` class is quite useful in some situation and i think adding documentation will be helpful.

**Comment by lagbox** [comment]
What documentation would you want for it? 
Also the docs are open to PR if you think it should be documented. :-)

**Comment by laurencei** [comment]
Hi @arcanedev-maroc,

I'm going to close this ticket, as there is no specific issue with the documentation.

If you would like to write some documentation for the `Manager` and how it can be used, feel free to submit a PR and it can be considered by Taylor.
