### ISSUE TITLE
Gate example differs with recommendation

### ISSUE THREAD

**Issue by bkilshaw** [laravel/docs#3077]
Not a huge issue, but under authorisation:

> Gates are most applicable to actions which are not related to any model or resource, such as viewing an administrator dashboard. In contrast, policies should be used when you wish to authorize an action for a particular model or resource.

It recommends you use a Policy for actions related to models or resources, and Gates for other permissions. However, the code example for Gates creates a permission to update a post, which should be a policy.

```
    Gate::define('update-post', function ($user, $post) {
        return $user->id == $post->user_id;
    });
```

The code example can be misleading for someone trying to figure out where they should be using Gates vs Policies.

**Comment by laurencei** [comment]
I've submitted a PR for this to be changed. It's up to Taylor if it is accepted or not.
