### ISSUE TITLE
Suggestion: add a deprecated function/class lists on document page

### ISSUE THREAD

**Issue by skys215** [laravel/docs#3083]
Hi, 

Laravel 5.4 has [removed several function](https://github.com/laravel/framework/issues/17640) in the BladeCompiler.php, I believe that there's more function has been deprecated in 5.4. So how about make a list of deprecated function/class in the [Upgrade Guide](https://github.com/laravel/docs/blob/5.4/upgrade.md)? At least while the user are upgrading there code, they can notice to those function/classes.
Just a suggestion.

Regards,

**Comment by Kyslik** [comment]
I would also like to see not only deprecated function/class lists but also renamed function/class list.

Example of undocumented change  5.3 -> 5.4 https://github.com/laravel/docs/issues/3017.

**Comment by laurencei** [comment]
If you find any undocumented changes, please feel free to submit a specific PR or issue, so it can be addressed.

Recent upgrade guides also make mention of classes that are going to be depreciated. Once again, if you find a specific issue please feel free to submit a PR so it can be fixed.
