### ISSUE TITLE
Error running dusk with upgraded application

### ISSUE THREAD

**Issue by leewillis77** [laravel/docs#3084]
I have an application that I've upgraded from Laravel 5.3 to 5.4. I've followed the steps in the upgrade guide, but found that wasn't sufficient to get Dusk up and running.

Specifically, I hit the following error:

`PHP Fatal error:  Class 'Tests\DuskTestCase' not found in /www/sites/myhillblog-repo/tests/Browser/ExampleTest.php on line 9`

In addition to the instructions under "Installing Dusk In An Upgraded Application" on https://laravel.com/docs/5.4/upgrade I had to make the following change to my `composer.json` and rebuild with `composer dumpautoload` in order to get the classes autoloaded properly. 

Change:
```json
"autoload-dev": {
    "classmap": [
        "tests/TestCase.php"
    ]
}
```
to
```json
"autoload-dev": {
    "psr-4": {
        "Tests\\": "tests/"
   }
}
```

**Comment by tnylea** [comment]
Thanks man, exactly what I needed :)

**Comment by aguirreg** [comment]
@leewillis77 My `composer.json ` file matches yours but I am still receiving the error `PHP Fatal error:  Class 'Tests\DuskTestCase' not found in /tests/Browser/ExampleTest.php` after I run `phpunit ExampleTest.php` Do you know what might be causing this?

**Comment by leewillis77** [comment]
Have you followed all of the other steps in the upgrade guide? After changing the composer.json as advised above have you rebuilt the autoloader with?

```composer dumpautoload```

**Comment by turtlegood** [comment]
Great shoot!

**Comment by sotoz** [comment]
Yeap, I can confirm that this is happening and what @leewillis77 mentions here works.

**Comment by savaged** [comment]
I have upgraded from 5.3 to 5.4 on Homestead and am trying to use Dusk. After running `php artisan dusk` the process runs until it times out. All old BrowserKit tests are working and the new basic tests, but not Dusk. See https://github.com/laravel/dusk/issues/81
