### ISSUE TITLE
[5.4][UPGRADE DOC] PUSHER ENV key changes

### ISSUE THREAD

**Issue by yajra** [laravel/docs#3114]
Maybe it's worth documenting on upgrade guide that PUSHER key has changed from:

```php
PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=
```

TO

```php
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
```

I've been receiving this error and have wasted almost 3hrs finding the solution just to find out that the key name has changed. :( 

```
BroadcastException in PusherBroadcaster.php line 106:
auth_key should be a valid app key
```

Thanks!

**Comment by noder123** [comment]
Bump. 
A fresh installation of Laravel 5.4 generates the correct keys in .env file, but I'm still getting this exception.

**Comment by laurencei** [comment]
This would only affect your upgrade if you changed your local `app/broadcasting.php` file.

Meanwhile a change was made to `laravel/laravel` that fixed new installations with this problem, so the issue is now resolved.

Thanks
