### ISSUE TITLE
mix.styles -> mix.combine

### ISSUE THREAD

**Issue by dmarman** [laravel/docs#3145]
In mix.md Plain CSS, mix.styles is deprecated. Should be mix.combine!

**Comment by BadChoice** [comment]
as well as `mix.scripts` => should be called `mix.combine`

**Comment by JeffreyWay** [comment]
`mix.scripts()` and `mix.styles()` are not deprecated.

**Comment by BadChoice** [comment]
`mix.scripts` doesn't work on last version

**Comment by JeffreyWay** [comment]
@BadChoice Yes it does. You probably have an older version of Mix installed. Make sure you have v0.8.8 installed.

**Comment by BadChoice** [comment]
@JeffreyWay it looks like your are right ;)

in yarn.lock I have

`laravel-mix@^0.7.2:`

but it was the one that came with a fresh laravel install a few days ago,
how can we update it?

**Comment by JeffreyWay** [comment]
You can delete yarn.lock and re-run `yarn`.

**Comment by BadChoice** [comment]
Sorry for my incompetence here.. but where should `yarn` command be?

**Comment by JeffreyWay** [comment]
Oh, if you're not using Yarn, then yarn.lock is irrelevant. 

Just open package.json, and make sure that the "laravel-mix" dependency looks like this: https://github.com/laravel/laravel/blob/master/package.json#L14

Then do:

```
rm -rf node_modules && npm install
```

**Comment by BadChoice** [comment]
Oh yeah!! that looks a way better now and it works ;)
Thank you so much
