### ISSUE TITLE
Installation: $PATH

### ISSUE THREAD

**Issue by ano95** [laravel/docs#3147]
Hello,

after installing laravel (https://github.com/laravel/docs/blob/5.4/installation.md), there is note, to include 
`$HOME/.composer/vendor/bin` into $PATH, but on my installation of composer, it was in `$HOME/.config/composer/vendor/bin`.
Is this problem with my installation?

**Comment by wwwhq199** [comment]
just try it,on my win10 os,the path is "C:\Users\wwwhq\AppData\Roaming\Composer\vendor\bin"

**Comment by laurencei** [comment]
Closing as this issue appears resolved.
