### ISSUE TITLE
updateOrCreate not exists

### ISSUE THREAD

**Issue by IbraheemAlnabriss** [laravel/docs#3168]
Hello
in documentation 
[laravel Eloquent Doc](https://laravel.com/docs/master/eloquent)
there is a function called `updateOrCreate` but actually in `Illuminate\Database\Query\Builder`
it's not exists so it's fail silently, Instead there is `updateOrInsert`
i would suggest updating the documentation.

**Comment by lagbox** [comment]
`updateOrCreate` is defined on `Illuminate\Database\Eloquent\Builder`, which is what Eloquent Model's use.
https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Builder.php#L394
