### ISSUE TITLE
Document the config variable 'app.faker_locale'

### ISSUE THREAD

**Issue by vpratfr** [laravel/docs#3172]
See PR that got closed: https://github.com/laravel/laravel/pull/4161

> At some point in time, Laravel allowed to change the locale used by Faker. However that configuration variable has remained undocumented and people are probably still doing it with a custom provider binding.
> 
> Hence I just added the variable to the default project's app.php file.
> 
> See also: http://stackoverflow.com/questions/34496720/change-faker-locale-in-laravel-5-2

**Comment by windows1087** [comment]
Whats the problem to document this?!

**Comment by laurencei** [comment]
Thanks @vpratfr - I've done a PR for this for Taylor's consideration.

**Comment by vpratfr** [comment]
I had already submitted a PR which got closed...

**Comment by laurencei** [comment]
I meant a PR for the docs to be included there.
