### ISSUE TITLE
Broadcasting: It's not safe to use socket.io library from Laravel Echo Server directly

### ISSUE THREAD

**Issue by kkomelin** [laravel/docs#3173]
See [the corresponding issue](https://github.com/tlaverdure/laravel-echo-server/issues/132) in the Laravel Echo Server issue queue.

Therefore, I believe some corrections to the ["Driver Prerequisites - Socket.IO"](https://github.com/laravel/docs/blob/5.4/broadcasting.md#socketio) section of the broadcasting.md are necessary.

**Comment by barryvdh** [comment]
I actually recently submitted this change to the docs (https://github.com/laravel/docs/pull/3004)
And coincidentally the socket went down for like a week or so, last week: https://github.com/socketio/socket.io/issues/2883
Which would have resulted in the same problem, but for everyone using the CDN instead of just people where the socket is not running.

It could perhaps be described better, but usually your socket should be always running, and checking if `io` is defined is an easy way to see if it *is* running. Otherwise you would get continuous polling to the SocketIO server, without being aware that connect failed/socket is down.

**Comment by kkomelin** [comment]
Thanks for your comment @barryvdh. 

I think users should be warned about consequences of the situation when Socket.io server (Laravel Echo Server) stops for some reasons. It will result in a complete failure of all JS code which follows the code:
```
    window.Echo = new Echo({
        broadcaster: 'socket.io',
        host: window.location.hostname + ':6001'
    });
```
and since this code is in the bootstrap.js (at the top), everything will fails.

> It could perhaps be described better, but usually your socket should be always running, and checking if io is defined is an easy way to see if it is running.

Firstly, you can't hope that your socket.io server will be always available.
Secondly, a realtime component is usually a minor part of an app and it should not become [a single point of failure](https://en.wikipedia.org/wiki/Single_point_of_failure) for the entire Laravel app.
Thirdly, from my experience, if a piece of code is included to the official documentation or to the default Laravel installation, users tend to trust the code. 
From my point of view, the checking for `io` existence should be included in the documentation and the default Laravel installation because it's a serious issue.

In [my article](https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks#laravel-echo-server-fails) I suggested two solutions that can work together or separately:

1) Copy Socket.io lib to your public/js folder (e.g. via Webpack) and add it to your main page template:
```
<script src="{{ asset('js/socket.io.min.js') }}"></script>
```
2) Always check if `io` object exists before using Echo:
```
if(typeof io !== 'undefined') {
  window.Echo = new Echo({
      broadcaster: 'socket.io',
      host: window.location.hostname + ':6001'
  });
}
```

**Comment by kkomelin** [comment]
Or even better, any method of the frontend Echo class cand check for `io` existence before using it.

**Comment by barryvdh** [comment]
When using webpack, you could just require the package with npm instead of copying, right?

Checking io would be okay, but you would need additional checks in the rest of your code, because now `windows.Echo` is undefined further along.

(A benefit from using the socketio client from the server is that it always matches your server code, but with semver that doesn't have to be a problem).

**Comment by kkomelin** [comment]
> When using webpack, you could just require the package with npm instead of copying, right?
Yes, I meant exactly that but wanted to cover all configurations, including those when people don't use Webpack.

With Webpack:
```javascript
mix.copy('node_modules/socket.io-client/dist/socket.io.min.js','public/js');
```

> Checking io would be okay, but you would need additional checks in the rest of your code, because now windows.Echo is undefined further along.

Yes, and because of that I published [my last comment](https://github.com/laravel/docs/issues/3173#issuecomment-284671839) right before you published your last one ) It's actually Echo client responsibility to check for `io` existence because it isolates any direct io calls from users.

> (A benefit from using the socketio client from the server is that it always matches your server code, but with semver that doesn't have to be a problem).

I understand the advantage but we should also take into account its drawback.

**Comment by kkomelin** [comment]
On top of that, if our app doesn't use Echo on every page it's not necessary to bundle socket.io lib to the main JS file. Instead, we can only include it where it's necessary.

**Comment by jonnywilliamson** [comment]
>(A benefit from using the socketio client from the server is that it always matches your server code, but with semver that doesn't have to be a problem).

>I understand the advantage but we should also take into account its drawback.

This is a really interesting conversation. My website "went down" last week because of the socket CDN server being affected...so this has a high priority for me!

@kkomelin What are the drawbacks from using the actual socket server to serve `socket.io.min.js`?

**Comment by barryvdh** [comment]
The exact same issue, when your not checking if io exists.

If you're using CDN and CDN is down: crashes app
If you're using the socket server, but server is down: crashes app

So 2 options:
 1. Use a local version of the socket-io client (with bower/npm/webpack etc)
 2. Use the server but check if the script was loaded (eg. `io` exists), but needs to be everywhere in your code where you want to use io or Echo.
3. Adapt Echo to fail softly when io not exists, but emit a console warning or something.

1 has downside that it's an extra step to setup.
2 has downside that it requires some extra for the developer
3 would have to be implemented in echo, but would require some rewriting.

(But when running laravel-echo-server with Supervisor, I didn't encounter any instability yet, but only running for a month or so now).

**Comment by jonnywilliamson** [comment]
@barryvdh Thank you for breaking that down clearly.

Yeah, I'm been running echo server with Supervisor for well over 5/6 months and it's never caused me any problems!

There were some people suggesting to use `PM2` as a node script monitor, but I haven't bothered to take a look at it...however I'm wondering if anyone knows if I'm missing out on any benefits by not using it?

https://github.com/tlaverdure/laravel-echo-server/issues/65#issuecomment-258872299
https://github.com/tlaverdure/laravel-echo-server/issues/80#issuecomment-263048098

**Comment by barryvdh** [comment]
@kkomelin This seems to work for me with Webpack:

``` 
yarn add socket.io-client
```

```js
import Echo from "laravel-echo"

window.io = require('socket.io-client');

window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001'
});
```

But again, having the Socket running is still important, as this will keep polling every second before the server comes back online.

**Comment by kkomelin** [comment]
@barryvdh,

Thank you for summarizing the problem for @jonnywilliamson. I couldn't have explained it better.

> (But when running laravel-echo-server with Supervisor, I didn't encounter any instability yet, but only running for a month or so now).

I also run laravel-echo-server through Supervisor but it doesn't mean I can be 100% sure that node.js, socket.io and other its components have no bugs and can't fail one day. Temporary failure is probably not a big problem for a personal blog but for a serious application it can cost money.

To sum up, the task of protecting the app from such failure is much cheaper than potential lose caused by the failure, so I prefer insuring myself if I can.

> @kkomelin This seems to work for me with Webpack:

Thank you for the code snippet. I will consider using it instead of copying and including socket.io.js through HTML if need it on every page.

> But again, having the Socket running is still important, as this will keep polling every second before the server comes back online.

Yes, it will. May this issue be also improved on the Echo client library level?

**Comment by zhenzihui** [comment]
啷个弄？

**Comment by laurencei** [comment]
@kkomelin @barryvdh ,

What is the TLDR of this? Do we need to update the docs, or can this issue be closed?

**Comment by laurencei** [comment]
ping @kkomelin @barryvdh - can you please confirm the status of this? Thanks

**Comment by kkomelin** [comment]
@laurencei 
I summarized the problem and three possible solutions in my post https://komelin.com/articles/realtime-apps-laravel-echo-tips-and-tricks#laravel-echo-server-fails
The fourth solution is that Echo client should check the availability of socket.io itself because it's its dependency.
And yes Laravel docs still need an update.

**Comment by laurencei** [comment]
@kkomelin - so for the docs, if we changed:

```diff
- window.Echo = new Echo({
-     broadcaster: 'pusher',
-     key: 'your-pusher-key'
- });
+ if (typeof io !== 'undefined') {
+   window.Echo = new Echo({
+       broadcaster: 'pusher',
+       key: 'your-pusher-key'
+   });
+ }
```

is that sufficient for the docs?

**Comment by kkomelin** [comment]
@laurencei I don't think so. That solution is just a workaround and it highlights the issue in the Echo client which doesn't properly check its dependencies. Such check should be inside the Echo client.

I think we should make Socket.io section of the doc similar to Pusher one:
```js
import Echo from "laravel-echo"

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key'
});
```
as @barryvdh suggested here https://github.com/laravel/docs/issues/3173#issuecomment-284708455
It would be better.

**Comment by kkomelin** [comment]
@laurencei But again, Laravel Echo client library must check itself whether its dependencies are available before using them.

**Comment by laurencei** [comment]
@kkomelin - can you review PR https://github.com/laravel/docs/pull/4098 and let me know?

It's up the maintainer for the Echo client what changes they make there. This repo is only for the documentation of how it performs now.

**Comment by kkomelin** [comment]
> It's up the maintainer for the Echo client what changes they make there. This repo is only for the documentation of how it performs now.

Right. And if you close this issue, it's likely that the maintainer of the Echo client will never know about the issue.

**Comment by kkomelin** [comment]
@laurencei I strongly believe that the Larvel Echo client developer(s) should also review its docs.

**Comment by laurencei** [comment]
@kkomelin - that is another repo created by the community. They dont have anything to do with the Laravel docs. If you feel there should be some changes in the docs there, it would be best if you open a PR on that repo with the changes you think are needed.

@tlaverdure is the developer there who maintains it. Once he/she sees your PR, they can decide if it should be merged into those docs as well.

I dont disagree with what you are saying, but having the issue open here wont draw it to the attention of the other package - they are run seperately.

**Comment by kkomelin** [comment]
> @kkomelin - that is another repo created by the community. They dont have anything to do with the Laravel docs. If you feel there should be some changes in the docs there, it would be best if you open a PR on that repo with the changes you think are needed.

@laurencei [Laravel Echo client library project](https://github.com/laravel/echo) is created by @taylorotwell, and the readme says that http://laravel.com/docs/broadcasting is the official documentation for it. So, in fact, you're now working on the official documentation of the Laravel Echo library.

> @tlaverdure is the developer there who maintains it. Once he/she sees your PR, they can decide if it should be merged into those docs as well.

@tlaverdure is the developer of the Laravel Echo Server https://github.com/tlaverdure/laravel-echo-server (not client), and he is aware of the issue https://github.com/tlaverdure/laravel-echo-server/issues/132

**Comment by laurencei** [comment]
Ok, sorry - I now understand what you are saying - I thought you were talking about the other repo.

So the PR I've submitted is always reviewed by Taylor, so he will see the PR and decide if the docs should be merged in or not (it's not up to me).

If you have other idea(s) on changes that can be made, you are welcome to submit a PR for Taylor to review as well.

**Comment by kkomelin** [comment]
Thank you @laurencei.

**Comment by laurencei** [comment]
@kkomelin - are you able to submit a PR with what you think the changes should be? At this stage it is difficult for me to replicate what you are saying.

**Comment by kkomelin** [comment]
@laurencei Done https://github.com/laravel/docs/pull/4156
I used your previous PR as a basis, just improved the npm install command. 
Tested.

**Comment by kkomelin** [comment]
The Broadcasting documentation has just been updated (https://github.com/laravel/docs/pull/4156) according to the best proposed solution https://laravel.com/docs/5.6/broadcasting#driver-prerequisites.

Thanks to everyone involved! We've done a great job.
