### ISSUE TITLE
Why is creating Eloquent event handlers with anonymous functions no longer documented?

### ISSUE THREAD

**Issue by orrd** [laravel/docs#3191]
As of Laravel 5.3, the Eloquent documentation no longer mentions the simple anonymous function way of responding to Eloquent events with something like self::creating(function ($user) { ... } using anonymous functions to easily define event handlers without having to create a new class in a separate PHP script.  

The documentation does mention the $events option, and "Observers" way of doing events.  But those both require creating new separate classes and aren't suitable for a lot of situations where adding separate classes causes complications (in my particular situation, I'm creating a trait that automatically logs Eloquent activity to a log file).

I'm concerned that while the closure technique way still works, it was removed from the documentation. Should we be concerned that the closure technique of defining event handlers could go away? Why is it no longer in the documentation?  Should I create a pull request that restores a mention of that technique to the Eloquent docs?

I think it's important that Laravel devs know that there is a simpler way to respond to Eloquent events for scenarios where it is unnecessarily complicated to create external classes to handle the events.

**Comment by decadence** [comment]
Good point.
Does anybody actually look in issues of this repo? Many issues without any attention. Seems like only way is making PR.

**Comment by orrd** [comment]
I'm not sure it's worth doing the work to make a PR since it's now looking like Taylor most likely wouldn't accept it anyway.  I submitted https://github.com/laravel/docs/pull/3293 which is an ever more clear example of a case where the original simpler way of doing things is often preferable for multiple reasons, but he refused to re-include the simpler approach in the documentation without offering an explanation.  

He seems to be shifting his design philosophy away from the original focus of Laravel on powerful simplicity, towards a more dogmatic approach that enforces a requirement that developers create separate classes for every task, even if there isn't a justifiable benefit to the added complexity in most cases.  This seems to be the opposite of the original focus Laravel had on making everything as simple as possible.

**Comment by decadence** [comment]
That's strange too because many people found using `Mail::send` much simplier.
But you will never know until try PR. Maybe he thinks about deprecating this way (I hope he doesn't).

**Comment by laurencei** [comment]
Essentially you could use Closures almost anywhere in the Laravel framework. Many functions and options actually accept them. However documenting this can lead developers down the wrong path, and imply that it is the "correct" behaviour.

The reality is most cases a class would be a better option for events like this.

**Comment by orrd** [comment]
I'm not sure you really understand why the simpler approach is preferred for most cases.  There aren't as many cases where adding a whole new class just to handle a model event would be preferred.  The added complexity often isn't worth the advantage of code separation.  It's reasonable to expect that the definition of a model class includes defining how that model responds to events.

There's a reason why the major appeal of Laravel is that it makes thinks simple, and not documenting the simple way to do this goes against the Laravel ethos of not making things more complicated than they need to be.  

When a simpler (and arguably better) solution exists in the framework, it should be documented.

**Comment by laurencei** [comment]
Your welcome to submit a PR with an example of how you propose the docs can be modified to include it, and Taylor can decide if he wants to accept it or not 😄
