### ISSUE TITLE
Log::getMonolog() in 5.4

### ISSUE THREAD

**Issue by Huggyduggy** [laravel/docs#3197]
As of Laravel 5.4, it seems like getMonolog is not available by the Log:: Facade anymore - yet it's still documented at the very bottom of https://laravel.com/docs/5.4/errors. For me, I've resolved the issue by using the Log::pushHandler($handler) function directly, without requesting its underlying monolog instance first. As I don't know if there's a better way to do it, I'd rather not provide a bad PR 😨

**Comment by sede2** [comment]
It worked for me on a fresh install

**Comment by Huggyduggy** [comment]
Thanks @sede2 - maybe some changes within the framework broke it for us, I'll digg into it. I'll close the issue, as it might be related to our code only 👍
