### ISSUE TITLE
Laravel Mix doc incorrectly says "you have two choices" under Custom Webpack Configuration

### ISSUE THREAD

**Issue by joeldbirch** [laravel/docs#3201]
The page at 
https://laravel.com/docs/5.4/mix#working-with-scripts incorrectly says "you have two choices:" under Custom Webpack Configuration, but then only describes one, ie "Merging".

**Comment by jhoff** [comment]
Fixed in https://github.com/laravel/docs/commit/514dfc6f65a44142eebfa02ede2d25d06320f695
