### ISSUE TITLE
[Proposal] Add a Trademark and Brand Guidelines page

### ISSUE THREAD

**Issue by httpoz** [laravel/docs#3219]
To draw the line for other devs out there with so much love for Laravel that we often use the name Laravel or the Laravel logo in our app names and logos. Also Taylor gets these questions every now and then on Twitter.

I see the page sitting below the API Documentation link.

Examples: 
[Microsoft](https://www.microsoft.com/en-us/legal/IntellectualProperty/Trademarks/Usage/General.aspx)

**Comment by laurencei** [comment]
The laravel artwork is publically available at: https://github.com/laravel/art

**Comment by yoshiokatsuneo** [comment]
I cannot see any license, guideline or usage of the logo on the https://github.com/laravel/art repository.
Can I use the logo in the blogs or books ?
