### ISSUE TITLE
Upgrade guide to 5.4 and make method

### ISSUE THREAD

**Issue by mickaelpch** [laravel/docs#3250]
Hi,
As written in the upgrade guide to 5.4, the `Container::make` method does not accept a second array of parameters.

> **make Method Parameters**
> The container's make method no longer accepts a second array of parameters. This feature typically indicates a code smell. Typically, you can always construct the object in another way that is more intuitive.

Since version 5.4.16, the new method `Container::makeWith` basically offers the old behaviour of `Container::make`.

As the drop of the second parameter for `Container::make` can cause some pretty deep code modifications, may I suggest to add the existence of the new `Container::makeWith` method in the upgrade guide, maybe someting like this : 
> **make Method Parameters**
> The container's `make `method no longer accepts a second array of parameters. This feature typically indicates a code smell. Typically, you can always construct the object in another way that is more intuitive.
> However, version 5.4.16 introduces a new `makeWith ` method to the container that accepts a second array of parameters.

**Comment by laurencei** [comment]
Thanks @mickaelpch - I've submitted a PR with this idea for Taylor's consideration.
