### ISSUE TITLE
Clarify or warn on Queue Naming

### ISSUE THREAD

**Issue by silverskysoft** [laravel/docs#3256]
This is more a clarification that will prevent people from getting into issues once they start to use Redis queues in a more advanced way. 
Current queues.md:

> Some applications may not need to ever push jobs onto multiple queues, instead preferring to have one simple queue. However, pushing jobs to multiple queues can be especially useful for applications that wish to prioritize or segment how jobs are processed, since the Laravel queue worker allows you to specify which queues it should process by priority. For example, if you push jobs to a high queue, you may run a worker that gives them higher processing priority:

Suggested change : Please add a caution/warning something on the lines as below:
`In Redis queue driver, when installing multiple apps in a single server,  for correct execution, each app should use a unique queue name across all apps or use a different database ID per app`

This is because, queue jobs are stored under the queue name as the key.  Simply using untagged names like "default" or "emails" will cause queue worker from another app  pull work as though it were its own and possibly fail. 

Even better would be if Laravel framework can provide a way to tag the queue names automatically like Redis Cache.

**Comment by laurencei** [comment]
There is now a prefix option for redis - so each application can define it's own prefix to prevent clashes.
