### ISSUE TITLE
Queues failed() method - Incorrect signature

### ISSUE THREAD

**Issue by Numline1** [laravel/docs#3257]
The failed() methods in 5.4 docs seems to have incorrect signature.

This is how failed() method is called:

```
    public function failed($e)
    {
        $this->markAsFailed();
        $payload = $this->payload();
        list($class, $method) = JobName::parse($payload['job']);
        if (method_exists($this->instance = $this->resolve($class), 'failed')) {
            $this->instance->failed($payload['data'], $e);
        }
```

In 5.4 docs, it says only \Exception parameter should be passed, however, it seems that the payload is required as well, hence it should say failed($payload, \Exception $e).

I may be wrong, but this is how it works in my code.

**Comment by ghunti** [comment]
Hi @Numline1 I think i was having the same issue, but I've figured out that I was using the `failed` method of an event listener and reading the docs for the Queue Job...
I have to admit that the concepts are mingle, and thus can cause confusion, maybe you are facing the same problem

**Comment by laurencei** [comment]
I'm going to close this issue, as the current documentation looks correct. It is possible the issue was resolved since you posted this ticket.

Let me know if you run into any further issues.
