### ISSUE TITLE
hasManyThrough requires relevant table's name

### ISSUE THREAD

**Issue by srph** [laravel/docs#3267]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.6 InnoDB

### Description
For `hasManyThrough` relationships, you need to provide the relevant table's name like the following:

```php
$country->posts->where('posts.name', 'LIKE', "%{$query}")->get();
```
Otherwise, a SQL error will be thrown:

> `SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous`

### Suggestion
I think the documentation should mention this for clarity.

-----

Putting this up because I didn't find any related issues, and a way of asking for approval if I can send a PR for this. Let me know if I missed anything.

**Comment by laurencei** [comment]
I've looked at this a couple of times. At the moment there is no example of using `->where()` in that example.

The error message is quite obvious if someone does encounter it.

If anyone has a good way to update the docs to make this fit cleanly with the rest of the documentation, please feel free to submit a PR for Taylor to review.
