### ISSUE TITLE
New docs menu is collapsed on Cmd key

### ISSUE THREAD

**Issue by chimit** [laravel/docs#3277]
The new docs menu is cool, but has a problem: when I want to open an item in a tab I press Cmd button on my Mac, and the basic menu item is collapsed.

For example, I click on "The Basics" - it is expanded. Then I press Cmd key on my keyboard and the Basics submenu is collapsed back. The Apple Magic Mouse doesn't have the third button, so it's the only way to open links in new tabs (except the context menu, which is obviously inconvenient).

Not only the Cmd key collapses submenu items. Shift, Option, and Control have the same effect.

P.S. I'm not sure it's the right place to report such problems. The website repository has issues disabled.

**Comment by Kyslik** [comment]
I can confirm, any modifier key collapses menu if in focus.

I personally do not like the change, since I was used to `cmd+f` and search for whatever I was interested, now menu is hidden and search results are empty. This is IMHO step back; + site worked without **JS** now it is required... (excluding search).

**Comment by Alexgmin** [comment]
In the meantime, you can create a stylish for the docs with this:
```css
    .sidebar > ul > li > ul{
       display:block;
    }
```

I hope the sidebar styles are changed back to the old ones soon.

**Comment by Kyslik** [comment]
Ping @taylorotwell

**Comment by shadoWalker89** [comment]
May be the docs will be by default expanded with the a `collapse / expand` button

**Comment by panckreous** [comment]
Having all the menus closed now make it unnecessary hard to find what we're looking for. Please, please revert. This is a documentation site

**Comment by bbashy** [comment]
This is plain annoying now. Who thought it was a good idea to collapse the menus?

**Comment by vlakoff** [comment]
Another strong +1 for reverting this.

**Comment by introwit** [comment]
@taylorotwell @themsaid this is seriously annoying. Collapsing menu in the docs is a super bad idea. Please revert this change.

**Comment by gocanto** [comment]
I do not like it either, but it seems, we gotta deal with it. ✌🏼

**Comment by introwit** [comment]
@chimit @Kyslik @Alexgmin @shadoWalker89 @panckreous @bbashy @vlakoff @gocanto created an issue in the Internals for the same: https://github.com/laravel/internals/issues/626

**Comment by taylorotwell** [comment]
Hit `/` key on your board, use the robust, fully-featured fuzzy search. Even better than Cmd+F. Enjoy.

**Comment by chimit** [comment]
@taylorotwell but what about the problem with menu collapsing on Cmd button press when I want to open a page in a new window?
