### ISSUE TITLE
Bring back old docs!

### ISSUE THREAD

**Issue by markdegrootnl** [laravel/docs#3281]
Like @Kyslik said in #3277: 
>This is IMHO step back

>Observed drawbacks of new docs navigation:
>- can not search using native browser `super+f` / `ctrl+f`
>- requires JS (excluding search)
>- jumping navigation, lets say I am reading something in **The Basics**, and I am interested in **Testing**, after clicking on Testing menu, navigation slightly jumps and I have to move mouse in un-natural way (**upwards** instead of downwards).

**Comment by Kyslik** [comment]
Maybe migrate this to [internals](https://github.com/laravel/internals), I was going to wait until at least 10 👍.

**Comment by panckreous** [comment]
Having all the menus closed now make it unnecessary hard to find what we're looking for. Please, please revert.

**Comment by inverse** [comment]
@panckreous can't you open them all using the arrow? AFAIK that works and persists.

**Comment by Kyslik** [comment]
@inverse That was added because of our motion... twitter pressure and all that. This should be closed @markdegrootnl.

**Comment by markdegrootnl** [comment]
Excellent!
