### ISSUE TITLE
Supervisor configuration example : numprocs parameter to 8

### ISSUE THREAD

**Issue by benoitjupille** [laravel/docs#3294]
I don't understand why the ```numprocs``` parameter is set to 8 in the "Supervisor Configuration" section. 

For me, it just launched 8 times my jobs on queue, and it took me some time to figure it out. 

The thing is that I discovered Supervisor with Laravel documentation. So I just copy/paste the supervisor conf example :)

Maybe it should be set to 1, no ? 

What do you think ?

**Comment by Kyslik** [comment]
It means that supervisor spawns 8 workers. I don't think jobs were done 8 times per worker.

**Comment by benoitjupille** [comment]
Yes it's weird because that's what happened. Maybe I did a mistake in the worker parameters :/ (I think about timeout)

But it was clear : the aim of the job was to send an email, and I was receiving 8 times my emails. So I change the numprocs parameter to 1, and it was fine.

**Comment by uzwebline** [comment]
exactly the same issue

**Comment by laurencei** [comment]
I'm going to close this issue.

The documentation is correct, the spawning of 8 workers is a valid choice and should work. If you are experiencing issues with simulatenous jobs running, that is another issue.
