### ISSUE TITLE
Need more description of tables created by Passport

### ISSUE THREAD

**Issue by vladyslavstartsev** [laravel/docs#3302]
I think there should be more info about tables and columns that they use. In the docs we only have that you should add passport service provider and then run `artisan migrate`, but what it does and why is mystery for me. 
Also it will be nice to have some diagram show how auth process looks like with Passport and how is it different from basic auth with tokens that we have.

**Comment by DCzajkowski** [comment]
Definitely! I find Passport docs pretty bad. I'll work on some rewrite when I find some time :)

**Comment by laurencei** [comment]
Hi @vladyslavstartsev,

I'm going to close this issue. You are welcome to submit a PR with extra documentation on the passport docs in the areas you believe it can be improved.

Thanks
