### ISSUE TITLE
Epub versions of the documentation

### ISSUE THREAD

**Issue by driade** [laravel/docs#3317]
Hi, hello, good evening.

I've made a program to convert Laravel documentation into epub

https://github.com/driade/laravel-book

Would it be useful for the official documentation?

PD: it's possible the ebooks still need a few fixes

**Comment by michaeldyrynda** [comment]
I think that the best part of having them online is that they're easy to update (as the framework is updated often) and easy to search.

Having them as a `mobi`/`epub` makes it easy for them to get out of date - not necessarily from a generation point of view (that can be automated), but more so from having to download updated versions every time the docs change.

That said, it could be useful for some people, but I wouldn't think they'll get added in the official docs.

**Comment by driade** [comment]
Hi @michaeldyrynda 

I may agree the utility is limited, but still when working offline this docs are really helpful. Also epub readers usually let you use extended functions, such as taking notes, dark mode, etc.

The distribution of the updated versions may be handled via an small service, quite easy to set up, or using a publishing platform (fe, Leanpub).

Symfony offers a PDF version of their docs to download.

**Comment by driade** [comment]
Added mobi and pdf formats

**Comment by driade** [comment]
It seems it's not interesting, closing the issue. I'll upload them to LeanPub, GumRoad or Lektu I suppose.

**Comment by davidangel** [comment]
I've recently been trying to read through all of the docs. An ebook version of the docs actually sounds really nice. I understand they could become dated at any point, and that it may just be better to do this with a tablet instead of an e-reader.

**Comment by driade** [comment]
Hi @davidangel , I'd suggest you to check Leanpub. There're people already offering Laravel documentation un ebook.

**Comment by driade** [comment]
I decided to reopen the issue, maybe more people would find it interesting to have the docs in ebook.

**Comment by driade** [comment]
Added docs for 5.5 and 5.6.

**Comment by laurencei** [comment]
Hi @driade - please create a PR with a suggestion on including the link. Taylor will then decide to include it or not.

I'll close the issue here and let you do the PR. Thnks.
