### ISSUE TITLE
Custom Filesystems !!!

### ISSUE THREAD

**Issue by laravelish** [laravel/docs#3324]
The Custom Filesystems docs here https://laravel.com/docs/5.4/filesystem#custom-filesystems doesnt tell you how we can create our custom filesystem, instead it show us how to install FREAKmurze's own implementation ! please update the docs because laravel docs is not a place to advertise others peoples package

this is way better https://laravel.com/docs/5.3/filesystem#custom-filesystems and it shows us the basics how we can create a filesystem !

**Comment by ludo237** [comment]
It's a community mantainer project for a custom filesystem, no need to freak out for the `subtle reference`

**Comment by chrisforrence** [comment]
I'm looking at the difference between the 5.3 and 5.4 docs, and the only change essentially swaps out `league/flysystem-dropbox` for `spatie/flysystem-dropbox`. That's for good reason; the League's original adapter relied on Dropbox's v1 API, which got turned off a few days ago. They now redirect users to install `spatie/flysystem-dropbox`.

That's the only related change I see in those versions of the docs. Are you advocating there be a link to (how to create a Flysystem adapter)[http://flysystem.thephpleague.com/creating-an-adapter/] in the documentation?

**Comment by laurencei** [comment]
I'm going to close this issue.

You are welcome to submit a PR for how to write a custom filesystem for Taylor to review if you like.
