### ISSUE TITLE
Document how to add a custom attribute to Eloquent model

### ISSUE THREAD

**Issue by kirtangajjar** [laravel/docs#3348]
Well I was searching online for this problem and found the following [answer](https://stackoverflow.com/questions/17232714/add-a-custom-attribute-to-a-laravel-eloquent-model-on-load) on stackoverflow

I think the use of `appends` variable should be documented somewhere in the laravel docs. Maybe at the [Eloquent Mutators](https://laravel.com/docs/5.4/eloquent-mutators) section?

**Comment by michaeldyrynda** [comment]
It's already documented [here](https://laravel.com/docs/5.4/eloquent-serialization#appending-values-to-json)

**Comment by kirtangajjar** [comment]
Oh! Thanks. I thought it was't documented.
