### ISSUE TITLE
$dateFormat is misleading?

### ISSUE THREAD

**Issue by snapey** [laravel/docs#3357]
Docs under Eloquent conventions:

_If you need to customize the format of your timestamps, set the $dateFormat property on your model. This property **determines how date attributes are stored in the database**, as well as their format when the model is serialized to an array or JSON:_

My understanding is that the $dateFormat alters how dates are interacted with the Model and not how they are stored in the database?  They are still stored as timestamp irrespective of the $dateFormat ?

**Comment by rossjcooper** [comment]
I have also always found the description a bit misleading and hard to understand.

**Comment by kevdotbadger** [comment]
Rewrite it and make a PR. I've made minor tweaks to the docs and they've got pulled pretty quickly.

**Comment by snapey** [comment]
Testing today, I think I'm mistaken.  If $dateFormat is set, and does not work for the database then the saving of models fails.
