### ISSUE TITLE
If i'll translate docs to Russian, will you apply it to the main site?

### ISSUE THREAD

**Issue by dkonovenschi** [laravel/docs#3369]

**Comment by diego1araujo** [comment]
as this is a question, i think it should be migrated to [laravel/internals](https://github.com/laravel/internals/) maybe?

**Comment by DCzajkowski** [comment]
1. It should be in laravel/internals as @diego1araujo mentioned
2. I really don't think so. The documentation has to be the best and most current thing. Whenever there is a PR to the main documentation, there must be a PR to the X language version to the site too. Also, Taylor needs to approve everything that lands on the site, and he would have no control over what is written in X language. As you can easily imagine all of the versions would very quickly go out of sync, and that would be a big _no, no_.
3. If you want, you can fork the site and translate it to Russian, and then host it yourself. Something like laravel-ru.com. But I really don't suggest that. That is a lot of work and a big pain in the ass...

**Comment by laurencei** [comment]
I'm going to close this ticket.

As others have mentioned, if there were different languages, it would be difficult to maintain, as every single PR would need a corresponding translation.

But you are welcome to do a translation and host your own version for others to share and benefit from.
