### ISSUE TITLE
laravel new  --- issue

### ISSUE THREAD

**Issue by piaohan** [laravel/docs#3384]
Excuse me,How to use `laravel new xxx` Specifies the version number

```
1.   composer global require "laravel/installer"
2. laravel new blog
```

larval use version 5.4.
I think use 5.1,use this command,How to do?

**Comment by m1guelpf** [comment]
You can do laravel new blog --lts when https://github.com/laravel/installer/pull/65 gets merged

**Comment by piaohan** [comment]
![err](http://i2.muimg.com/1949/116b95301b6e04e8.png)

**Comment by m1guelpf** [comment]
@piaohan You have to wait until my pull request is merged

**Comment by piaohan** [comment]
^_^  , OK

**Comment by piaohan** [comment]
I look at the pull , Why not join 5.2 and 5.3  version?

**Comment by m1guelpf** [comment]
@piaohan Because 5.2 & 5.3 are no longer supported.

**Comment by piaohan** [comment]
@m1guelpf 
Well sorry,
 only use
```shell
composer create-project --prefer-dist laravel/laravel blog 5.2.*
```
