### ISSUE TITLE
Storage::putFile and Illuminate\Http\File indicated in documentation, don't seem to exist

### ISSUE THREAD

**Issue by ChristianTheMinery** [laravel/docs#3414]
_Laravel 5.4 Documentation_

I followed the documentation precisely about using the Storage facade with S3 and encountered a few errors that lead me to believe the documentation is out-of-date.

https://laravel.com/docs/5.4/filesystem#storing-files

Firstly, the line: `use Illuminate\Http\File;` If one then instantiates a `new File`, Laravel will return a Class Not Found error. The namespace appears to be incorrect.

Secondly, the method `putFile()`. I installed the appropriate dependency with composer (`composer require league/flysystem-aws-s3-v3 ~1.0`), updated my `filesystem.php` config appropriately, and methods like `get()` and `put()` work correctly, however `putFile()` returns a `BadMethodCallException in PluggableTrait.php` error, indicating it does not exist in FlySystem. I checked with FlySystem to see if this behaviour was expected and the reply was:

```
That's not part of Flysystem and should be fixed ok [sic] Laravel's end. Perhaps it was added later?
```

So it seems the Laravel documentation is incorrect in this case.

**Comment by carusogabriel** [comment]
1º: Wrong, the [`Illuminate\Http\File`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Http/File.php) exists :sweat_smile: 

2º The [`putFile`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/FilesystemAdapter.php#L191) and [`putFileAs`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Filesystem/FilesystemAdapter.php#L205) methods coming from `Illuminate\Filesystem\FilesystemAdapter`. If you see [the documentation about `Facades`](https://laravel.com/docs/5.5/facades#facade-class-reference), this is the class that `Illuminate\Support\Facades\Storage` returns :innocent:

**Comment by laurencei** [comment]
Hi there,

I'm going to close this ticket as this issue seems resolved. If you believe there are still errors in the current docs, please let me know or feel free to open a new ticket. 

Thanks!
