### ISSUE TITLE
Change Cashier's $plan argument example on newSubscription($subscription, $plan) 

### ISSUE THREAD

**Issue by danhardman** [laravel/docs#3416]
**Laravel 5.4 Documentation**

The current example for creating a new subscription with Cashier is:

```php
$user = User::find(1);

$user->newSubscription('main', 'monthly')->create($stripeToken);
```
https://laravel.com/docs/5.4/billing#subscriptions

Using `monthly` as the `$plan` argument is confusing, suggesting it should be used for interval. I suggest we update it to something along the lines of how [Stripe](https://stripe.com/docs/api#create_plan) shows an example Plan ID like `quartz-startup` or `gold-membership`.

**Comment by inverse** [comment]
I guess this should be closed now.
