### ISSUE TITLE
Laravel Passport Incorrect Axios information

### ISSUE THREAD

**Issue by jordanramstad** [laravel/docs#3478]
The following section under "Consuming Your API With JavaScript" is currently misleading.

When using this method of authentication, Axios will automatically send the `X-CSRF-TOKEN` header. In addition, the default Laravel JavaScript scaffolding instructs Axios to send the `X-Requested-With` header:

```
window.axios.defaults.headers.common = {
    'X-Requested-With': 'XMLHttpRequest',
};
```
I came to finding out about this issue after seeing 
https://stackoverflow.com/questions/42030727/laravel-5-4-passport-axios-always-returns-unauthenticated/42032593#42032593

Witch did lead to some discussions to fix this in passport and laravel and although I welcome that I think that in the meantime some sort of message to point people to the problem if they notice it (unauthenticated errors due to token mismatch). Trying to track down the issue took me hours personally because I trusted in the docs saying that axios was adding the token automatically, and also seeing it there in the request (although as XSRF not CSRF, but the difference did not dawn on me).

The message could be as simple as:
```
Note: Some versions of Axios may use an incorrect header, if you run into 401 responses, ensure the correct `X-CSRF-TOKEN` header is set.
```

Anyway just a suggestion since I don't think there is any true "bug" here hence me suggesting an edit to the docs.

**Comment by laurencei** [comment]
Hi there,

FYI - I'm going to close this issue.

The docs have been updated significantly since this was posted, and that section has been re-written.

If you believe there are still improvements that can be made, please feel free to submit a PR with the changes, or open a new ticket with the details of the problem.

Thanks.
