### ISSUE TITLE
Undocumented breaking change on L5.4

### ISSUE THREAD

**Issue by iget-master** [laravel/docs#3494]
I've noticed that L5.4 change the signature translator helper classes:

**trans()** helper changes from [this](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/helpers.php#L773) to [this](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L786)

and

**trans_choice()** helper changes from [this](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/helpers.php#L794) to [this](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L806)

The changes also applies to translator methods signature. I think that this should be on docs, since it causes a breaking change for who uses the `$locale` parameter, not uncommon.

**Comment by DCzajkowski** [comment]
Can be closed when #3513 and #3514 are merged.
