### ISSUE TITLE
Bcrypt work factor

### ISSUE THREAD

**Issue by kevinfoley** [laravel/docs#3508]
According to the docs: 

> Bcrypt is a great choice for hashing passwords because its "work factor" is adjustable, which means that the time it takes to generate a hash can be increased as hardware power increases.

That's great, but then you don't explain _how_ to adjust the work factor, or mention what the default work factor setting is. The [API docs aren't any more helpful](https://laravel.com/api/5.4/Illuminate/Contracts/Hashing/Hasher.html).

**Comment by DCzajkowski** [comment]
Can be closed as of https://laravel.com/docs/5.5/hashing. :)
