### ISSUE TITLE
Missing tip in collection forPage doc

### ISSUE THREAD

**Issue by srobati** [laravel/docs#3523]
Hi,
I wanted to return the paginated items from eloquent, so i read the `forPage` docs and did the following:
```php
$result = $collection->forPage($page, $size)->all();
//return $result
```
but json response for `$page > 1` was json object instead of array!!!
after some try i found that the following code is the correct way to return paginated result:
```php
$result = $collection->forPage($page, $size)->values()->all();
//return $result
```

It is better to mention  that the `forPage` preserve keys and the json result may be object instead of array and for array result `values` must be used after `forPage`.

**Comment by carusogabriel** [comment]
Could you please give an example? I can't see `forPage` return `JSON` :thinking:

**Comment by laurencei** [comment]
Testing the examples in the documentation, I've not been able to reproduce this issue.

If anyone finds a problem with the provided examples, feel free to open a new issue with further details of the problem.

**Comment by BehroozBvk** [comment]
tanks for code values()

**Comment by MikeSheward** [comment]
Thanks this helped! Sometimes it would return an array, and another an object!
