### ISSUE TITLE
Changing .app TLD references

### ISSUE THREAD

**Issue by inverse** [laravel/docs#3526]
Since Google is in the process of [registering the .app TLD][0] should the documentation be changed to not use .app and use one of the RFC 2606 advised TLD's for testing?

See: https://tools.ietf.org/html/rfc2606#section-2

[0]: https://www.registry.google/about/domains.html

**Comment by jakebathman** [comment]
So there's another issue with this change: Homestead uses `.app` as a configuration default, not just in the documentation. So we'd have to revise those defaults for Homestead here: https://github.com/laravel/homestead/blob/7007b45c56a09d2afc8c1019854a2ea26b771ff0/src/Settings/HomesteadSettings.php#L103-L108

For quick reference, here's all of the *.app local TLD references in the docs that would need revising:

**homestead.md:140:**homestead.app
**homestead.md:149:**homestead.app
**homestead.md:153:**http://homestead.app
**homestead.md:181:**http://homestead.app
**homestead.md:181:**homestead.app
**homestead.md:250:**homestead.app
**homestead.md:252:**another.app
**homestead.md:257:**homestead.app
**homestead.md:258:**another.app
**homestead.md:268:**symfony2.app
**homestead.md:280:**homestead.app
**homestead.md:294:**homestead.app
**homestead.md:328:**homestead.app
**homestead.md:328:**homestead.app
**homestead.md:328:**homestead.app
**homestead.md:330:**homestead.app
**homestead.md:334:**homestead.app
**homestead.md:346:**homestead.app
**localization.md:139:**messages.app
**pagination.md:137:**http://laravel.app
**valet.md:81:***.app

**Comment by inverse** [comment]
@jakebathman do you feel this change makes sense though?

**Comment by jakebathman** [comment]
Definitely there should be a change away from .app if it's going to be a valid TLD suffix.

I'm not a _huge_ fan of the RFC 2606 options, though. I think the `.dev` or `.local` may be better defaults (seems like a more well-used convention) but that could be discussed in internals.

In the mean time, you can probably submit a PR for the non-homestead docs.

**Comment by inverse** [comment]
I would advise against using `.dev`. See: https://icannwiki.org/.dev

As for `.local` that could work, however looks like it's deemed more for private networks.

**Comment by jakebathman** [comment]
Our shop's convention is `.local` for our own machines and `.dev` for "stage" environments, but I agree that the former is better than the latter.

**Comment by jonnybarnes** [comment]
RFC 2606 specifically reserves `.localhost` for this purpose. Obviously a self-hosted version of the app, and will never be a registered TLD

**Comment by jakebathman** [comment]
Makes sense to me, so `.localhost` should probably be the convention.

**Comment by inverse** [comment]
Closing as deemed not important by maintainers
