### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by P9Q** [laravel/docs#3532]
Please add a dark theme switch if it's possible, reading the docs at night cause eye strain because of white and high contrast colors, thank you.

**Comment by Kyslik** [comment]
you may use https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by P9Q** [comment]
@Kyslik, I already use [Invert Page Colors](https://chrome.google.com/webstore/detail/invert-page-colors/hjhdnhiofjddcapmffbllcpaodjmdphn?hl=en) on PC, but unfortunately, mobile browsers don't support extensions :pensive:

**Comment by laurencei** [comment]
Thanks - I've submitted a PR for a dark theme here: https://github.com/laravel/laravel.com/pull/175

It is up to Taylor if it gets accepted or not.
