### ISSUE TITLE
What's different about assertSeeLink with assertSeeLink?

### ISSUE THREAD

**Issue by springjk** [laravel/docs#3552]
> `$browser->assertSeeLink($linkText)`  |  Assert the given link is present on the page.
>`$browser->assertDontSeeLink($linkText)`  |  Assert the given link is not present on the page.
>`$browser->assertSeeLink($link)`  |  Determine if the given link is visible.

I see two `assertSeeLink` method in Dusk doc, what's the diff? Dose the function check $link and do diff thing?

**Comment by davycheung** [comment]
I see what @springjk  is talking about on [documentation](https://laravel.com/docs/master/dusk) , looks like a typo to me. 

**Based on the dusk code comments:** 
```    
/**
     * Determine if the given link is visible.
     *
     * @param  string  $link
     * @return bool
     */
    public function seeLink($link)
    {
```

**Documentation should be changed to:**
`$browser->seeLink($link) | Determine if the given link is visible.`

**Comment by davycheung** [comment]
fixed [removed duplicate](https://github.com/laravel/docs/commit/25ea346fef12a2a472fc01dd2c77ab32cc1552af)

**Comment by springjk** [comment]
Thank you for answering my confusion。
