### ISSUE TITLE
Simplify homestead install docs

### ISSUE THREAD

**Issue by ShikherVerma** [laravel/docs#3571]
Instead of  "You can find the latest stable version on the GitHub Release Page"  
you could use `git describe --tags --abbrev=0` to get the latest tag.

Or you could directly do `git checkout $(git describe --tags --abbrev=0)`

**Comment by svpernova09** [comment]
Thanks for the suggestion. I'm kinda torn on the best way to do this. I hate having to constantly update the version, but I also like assuming `master` is the wild west / unstable.

Honestly I need to create a develop branch and merge that to master when I'm happy, then we can just tag off master and master will always be the released version.

**Comment by DojoGeekRA** [comment]
@ShikherVerma i actually tried something similar in https://github.com/laravel/docs/pull/3769 but it was rejected.

And i'm excited with your idea @svpernova09 , where master is always the stable release 🤘
