### ISSUE TITLE
Incorrect service container binding for Artisan

### ISSUE THREAD

**Issue by ockle** [laravel/docs#3572]
In the [reference table](https://laravel.com/docs/5.4/facades#facade-class-reference) of Facades and their associated service container bindings, it lists Artisan as being bound in the container as `artisan`. However, unless I'm mistaken, it isn't. It's bound as `Illuminate\Contracts\Console\Kernel`, and has been since 5.0.

**Comment by carusogabriel** [comment]
If you see the [`Class` column](https://laravel.com/docs/5.5/facades#facade-class-reference), it says `Illuminate\Contracts\Console\Kernel` as you said :sweat_smile:
