### ISSUE TITLE
More guidance for Horizon dashboard authentication

### ISSUE THREAD

**Issue by kamui545** [laravel/docs#3590]
In the documentation, we got the following section:

# Dashboard Authentication

Horizon exposes a dashboard at /horizon. By default, you will only be able to access this dashboard in the local environment. To define a more specific access policy for the dashboard, you should use the Horizon::auth method. The auth method accepts a callback which should return true or false, indicating whether the user should have access to the Horizon dashboard:

```php
Horizon::auth(function ($request) {
    // return true / false;
});
```

--

What do you think about adding some advices on **where** exactly you would **recommend** to drop this snippet? Personally I've put it in `AppServiceProvider::boot()` but maybe there's a more suitable place and more guidance may be appreciated for newcomers who could be lost?

**Comment by chrislentz** [comment]
Has anyone found anymore info on this question?

**Comment by browner12** [comment]
there is no "right" answer, but your `AppServiceProvider` is a decent solution. You could also make your own custom Service Provider.

I think adding a suggestion is a good idea.

**Comment by acidjazz** [comment]
@browner12 Placing the Auth facade and running `Auth::check()` results in a false even when a user is logged in in `boot()`, you sure this is good place to put this?

**Comment by browner12** [comment]
the session is probably not populated yet at this point, so that's why it doesn't see a user yet. What you actually want to do is register a callback with `Horizon:auth()` to be checked later on in the lifecycle.  Try this:

```php
/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    //horizon authentication
    Horizon::auth(function(Request $request){
        return $this->app->environment('local') || ($request->user() && $request->user()->id === 1);
    });
}
```

This will register the closure, and when it is called, the `Request` will be passed in.

**Comment by leadranger** [comment]
I put it in my web.php routes file, seems to work fine.

**Comment by sebastiansulinski** [comment]
If you check default `HorizonServiceProvider` you'll see the method, which registers horizon's routes

```php
protected function registerRoutes()
{
    Route::group([
        'prefix' => config('horizon.uri', 'horizon'),
        'namespace' => 'Laravel\Horizon\Http\Controllers',
        'middleware' => config('horizon.middleware', 'web'),
    ], function () {
        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');
    });
}
```

You can see there that it associates the middleware from the horizon's config file - entry `middleware`, which by default does not exist within the published config file - and if it cannot find this entry, it will use the default `web` middleware. You could either add and register new middleware or do as you did - use the `web.php` route file which is also fetched as per the above route group.

**Comment by SirLamer** [comment]
Just to add to this, it would be better to set the 'middleware' option as so:
```php
// ...

'middleware' => ['web', 'horizon'],

// ...
```

... and then not double-up on the web middleware hooks in the 'horizon' group as well. Keep them separate.

**Comment by sebastiansulinski** [comment]
Good idea @SirLamer - thanks!

**Comment by ramoncardena** [comment]
Thanks, @sebastiansulinski, that worked perfectly!

**Comment by umairali** [comment]
@sebastiansulinski i am trying with your code its working in case of auth login user but if user is not login its showing 

`Symfony \ Component \ HttpKernel \ Exception \ HttpException
No message`

**Comment by umairali** [comment]
I think simple solution is just to add this line to config/horizon file

`'middleware' => ['web', 'auth'],`

**Comment by sebastiansulinski** [comment]
@umairali - that's right, when you return `false` from within `Horizon::auth` closure, Horizon will throw `Symfony\Component\HttpKernel\Exception\HttpException` - personally I'd probably throw `Illuminate\Auth\AuthenticationException`, this is why my workaround to this was to handle this exception from within `App\Exceptions\Handler::render()` method, like so:

```php
namespace App\Exceptions;

use Exception;
use Illuminate\Auth\AuthenticationException;
use Symfony\Component\HttpKernel\Exception\HttpException;

class Handler extends ExceptionHandler
{

	// ...
	
	public function render($request, Exception $exception)
	{
	    if ($exception instanceof HttpException && $request->segment(1) === 'horizon') {
	        throw new AuthenticationException;
	    }
	
	    return parent::render($request, $exception);
	}
	
	protected function unauthenticated($request, AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        }

        $route = $request->segment(1) === 'admin'
            ? route('admin.login')
            : route('front.login');

        return redirect()->guest($route);
    }
	
}
```

What I did, was simply convert the `Symfony\Component\HttpKernel\Exception\HttpException` to `Illuminate\Auth\AuthenticationException`, which is handled by `unauthenticated()` method.

Hope this helps.

**Comment by laurencei** [comment]
Hi everyone,

This is now in the docs as part of the auth Horizon section.

**Comment by jlsjonas** [comment]
@laurencei and is completely ignoring the last comments 🤦‍♂️

**Comment by laurencei** [comment]
@jlsjonas - sorry, what do you mean? Taylor added some extra instructions there. Do you have a better option in the way it can be done?

**Comment by jlsjonas** [comment]
>@umairali - that's right, when you return false from within Horizon::auth closure, Horizon will throw Symfony\Component\HttpKernel\Exception\HttpException

sounds like an issue with the ::auth() method (or discrepancy at least)

regardless... the documentation felt quite lacking; as in "how do I actually check"

an example as provided by @browner12 could help a lot https://github.com/laravel/docs/issues/3590#issuecomment-339531720
