### ISSUE TITLE
Adding After Hooks To Form Requests documentation is confusing

### ISSUE THREAD

**Issue by gms8994** [laravel/docs#3594]
The documentation provided for [Adding After Hooks To Form Requests](https://github.com/laravel/docs/blob/4c81b4fdbde81e6aafb84a68381ab918ad1fe077/validation.md#adding-after-hooks-to-form-requests) is confusing, to say the least. It's an "after" hook that runs "before" validation rules are evaluated?

Does this mean that it's running the closure after the data validation, but you place it in your code somewhere before the validation is begun?

**Comment by johnsky007** [comment]
I agree with you absolutely, te documentation is very confusing in this case and I did get the point!

**Comment by AdolphYu** [comment]
为什么不是在rules 执行之后执行呢？不符合先基础验证后业务验证这个先后顺序

**Comment by laurencei** [comment]
Ok - so to clarify - you can call the validator BEFORE it runs, and attach AFTER rules for when it is complete.

See my PR that Taylor closed for more info.

If anyone has a better way to write this, please feel free to submit a PR :)
