### ISSUE TITLE
optional() helper method

### ISSUE THREAD

**Issue by jakewtaylor** [laravel/docs#3601]
There is nothing in the docs for the `optional()` helper method. I would make a PR but I won't be able to word it well enough, so I'll leave that to someone else.

**Comment by th3no0b** [comment]
It's mentioned in the Laracasts [video](https://laracasts.com/series/whats-new-in-laravel-5-5/episodes/20) on Laravel 5.5 resources.

Basically it just stops `cannot get property 'x' of undefined` type errors. I wouldn't have known it existed if not for that video.

**Comment by unstoppablecarl** [comment]
Where in the framework is it used? I couldn't find it anywhere.

**Comment by jakewtaylor** [comment]
Not sure. Does it have to be? I'm sure not all the helper functions are actually used within the framework itself, they're there for users, no?

**Comment by unstoppablecarl** [comment]
I could not find usage of the `Optional` class or `optional()` helper function.

**Comment by jakewtaylor** [comment]
Oh, did you watch the video I mentioned?

Example:
```PHP
$user = User::find(1);
$post = optional($user->posts)->first();
```

`$post` will be the first post if `$user->posts` exists, or something along those lines. Easier than checking if `$user->posts` is valid and then getting the first post.

**Comment by davycheung** [comment]
This is an interesting find, the helper function basically creates an instance of this:
https://laravel.com/api/5.5/Illuminate/Support/Optional.html

This will make life easier for below situations:
```
//optional helper
optional(User::find(1))->name

//without helper
$user = User::find(1);
$name = $user ? $user->name : null;
```

**Comment by micbenner** [comment]
@unstoppablecarl it's irrelevant if the framework uses it or not - the framework provides a functionality that should be documented with the other functionality it provides...

**Comment by davycheung** [comment]
this can be closed now.
