### ISSUE TITLE
Upgrade 5.4 to 5.5 guide does not contain BelongsToMany class changes

### ISSUE THREAD

**Issue by aleksandrlat** [laravel/docs#3631]
There are changes in public methods
- [constructor](https://github.com/laravel/framework/commit/3aa2adc7574b0ff6f4f3b3a75de4b3f9c19a9737#diff-fac59ee2778e54567a539e9140a1a42cR120) has more required params now
- getQualifiedForeignKeyName renamed to getQualifiedForeign**Pivot**KeyName [link](https://github.com/laravel/framework/commit/3aa2adc7574b0ff6f4f3b3a75de4b3f9c19a9737#diff-fac59ee2778e54567a539e9140a1a42cR896)
- getQualifiedRelatedKeyName renamed to getQualifiedRelated**Pivot**KeyName [link](https://github.com/laravel/framework/commit/3aa2adc7574b0ff6f4f3b3a75de4b3f9c19a9737#diff-fac59ee2778e54567a539e9140a1a42cR906)

If any of these methods are used in code they must be updated.

**Comment by carusogabriel** [comment]
There were already changed in #3731 :smile:
