### ISSUE TITLE
specify Mysql Only in the comment() column modifier

### ISSUE THREAD

**Issue by ruzguz** [laravel/docs#3637]
In the documentation for versions prior to 5.5, it is shown that the comment () column modifier works in all databases, but does not work in postgreSQL

by example 

```
Schema::create('someTable', function (Blueprint $table) {
            $table->increments('id')->comment('this is the id');
        });
```

create a table "someTable" with the "id" attribute, but do not add the comment

**Comment by carusogabriel** [comment]
If you see [inside the parentheses in the documentation](https://laravel.com/docs/5.5/migrations#column-modifiers), it says `(MySQL)` :smile:

**Comment by laurencei** [comment]
I'm going to close this ticket, as the documentation seems correct as pointed out by @carusogabriel
