### ISSUE TITLE
ssh-keygen instructions missing from Homestead 5.5 docs

### ISSUE THREAD

**Issue by sianglim** [laravel/docs#3644]
Hi all,

I was following Homestead instructions for 5.5, and noticed that the "Setting your SSH key" section is missing.

Happy to put in pull requests for the appropriate branches, but thought I'd check if there's been a change in the Homestead setup and it's no longer needed. On my end, I still had to generate a SSH key to get things running.

It's also missing for 5.4, 5.3 and 5.2 docs.  

Cheers,
Siang

**Comment by svpernova09** [comment]
Hi! Sorry for the delay in response. 

We expect your SSH key to already be set in `~/.ssh` so that's why the `Homestead.yaml` defaults there. We also assume if your OS doesn't like `~/` you'd know to update that to `C:\Users\User\.ssh`

Sorry for any confusion

**Comment by sianglim** [comment]
Hi @svpernova09,

thanks for the reply. That's probably why the section is no longer on newer docs.

I wasn't clear in my first post, but the part that I would suggest adding back is the "Don't have a SSH key?" section, which would be helpful to those new to setting up Homestead.

It's in the [5.0 docs](https://laravel.com/docs/5.0/homestead) under the "Setting your SSH key" section.

**Comment by svpernova09** [comment]
Gotcha, I'll let @taylorotwell give any feedback on that idea.
