### ISSUE TITLE
The upgrade guide to 5.5 should mention package discovery

### ISSUE THREAD

**Issue by M165437** [laravel/docs#3645]
Developers who upgraded without adding

```
"scripts": {
    ....
    "post-autoload-dump": [
        ...
        "@php artisan package:discover"
    ],
}
```

to their composer.json will have trouble installing packages that rely on package discovery (and open issues asking about the `'ServiceProvider' not found` error).

**Comment by Kyslik** [comment]
Its done, you may close this.

https://laravel.com/docs/5.5/upgrade#upgrade-5.5.0

**Comment by M165437** [comment]
Great, thank you!
