### ISSUE TITLE
Upgrade step missing? Trusted Proxies

### ISSUE THREAD

**Issue by 1e4** [laravel/docs#3671]
Hi everyone,

I was just upgrading my app and noticed that if you intend to configure trusted proxies you do need to include that package, as going from 5.4.* to 5.5.* doesn't include this for you.

Not sure where this belongs, is it an upgrade step or should it just be noted on the documentation that Trusted proxies requires a package if upgrading?

Simply running `composer require fideloper/proxy` will solve this.

**Comment by michaeldyrynda** [comment]
I don't think it's a missing step, necessarily. It's newly added to the framework, not something that was changed from a previous version.

It *might* be worth adding a note to the [configuring trusted proxies](https://laravel.com/docs/5.5/requests#configuring-trusted-proxies) docs - but even that assumes the presence of the `TrustedProxies` middleware at 5.5.
