### ISSUE TITLE
Syntax error on 5.5 cache page

### ISSUE THREAD

**Issue by phpguru** [laravel/docs#3683]
https://laravel.com/docs/5.5/cache#cache-usage

Parse error: syntax error, unexpected '\Encryptio', expecting '{' in /home/forge/laravel.com/bootstrap/cache/compiled.php on line 13504

**Comment by laurencei** [comment]
Hi @phpguru,

I cant see the syntax error? It might be that the problem has already been fixed.

If you find another error please feel free to open a new issue and we'll look into it.
