### ISSUE TITLE
csrf doc seems outdated for 5.5

### ISSUE THREAD

**Issue by persianphilosopher** [laravel/docs#3729]
Hope I am not mistaken but it seems that the documentation on csrf does not mesh with 5.5. 

It refers to the "class VerifyCsrfToken extends BaseVerifier", instead of "class VerifyCsrfToken extends Middleware".

**Comment by browner12** [comment]
all of the import aliases were renamed here: https://github.com/laravel/laravel/commit/e23a1d284f134bfce258cf736ea8667a407ba50c

not super important, since they both work, but you could PR if you'd like

**Comment by almeidafranci** [comment]
This can now be closed since #3729 was merged.
