### ISSUE TITLE
Addition to Passport -> Deploying Passport section

### ISSUE THREAD

**Issue by bhulsman** [laravel/docs#3733]
'Deploying Passport' currently only mentions running `php artisan passport:keys`, but for certain hostingproviders like fortrabbit/heroku, it should be added to the `post-autoload-dump` section of composer.json.

**Comment by laurencei** [comment]
@bhulsman - can you explain this a bit further? Why would you want to re-generate the keys after a autoload dump? It should only be called once AFAIK?

**Comment by bhulsman** [comment]
This is a little while ago, but as far as I can remember the problem is the deployment strategy. These hostingproviders will deploy from a git-repo which replaces the application code base. But this might simply be a deployment related issue, not so much something to put in the Passport docs.

**Comment by laurencei** [comment]
Hmmm... ok. Given there's been no other issues raised - I'm going to close this for now.

If other people raise the issue we can look to amend the docs, but for now it seems like an edge case.

Thanks.
