### ISSUE TITLE
Server minimal PHP requirement outdated

### ISSUE THREAD

**Issue by daniel-de-wit** [laravel/docs#3745]
The Laravel 5.5 documentation states the PHP requirement is > 7.0.0 however installing a fresh copy will use symphony sub-dependencies like `symphony/console` that now require PHP > ^5.5.9|>=7.0.8

For example:
https://github.com/symfony/console/commit/0ad1066cad7323d64b93343c8cf3294949961ffb#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

I guess the documentation and maybe even Laravel should update it's minimal requirement or constrain the symphony package requirements a bit.

**Comment by browner12** [comment]
are you suggesting we bump to >7.0.8?

**Comment by daniel-de-wit** [comment]
Well yes, because Php > 7.0.0 simply doesn't work anymore

**Comment by sisve** [comment]
Are you sure? I could still run laravel/framework on PHP 7.0.0 with symfony/console v3.3.6 which doesn't have the requirements on PHP >7.0.8, and thus it will still work. (For whatever definition of "work" is, I havn't looked into why  they bumped the version requirements.) We could just be vague and say "requires PHP 7.0 or higher" without mentioning the patch version.

**Comment by daniel-de-wit** [comment]
@sisve If you look at the example link you can see the requirement for `"php": "^5.5.9|>=7.0.8"` was set in symfony/console v3.3.7 which will be installed if you clean composer caches and create a new Laravel 5.5 application.

Take a look at the (current) latest Laravel release 5.5.20 composer requirement for symphony/console: https://github.com/laravel/framework/blob/v5.5.20/composer.json#L31
`"symfony/console": "~3.3",`

Which basically means: `>=3.3.0,<4.0.0`, right?

That means a cache-less composer install will use v3.3.7 or higher.

**Comment by laurencei** [comment]
Wont composer see you have PHP7.0.0 - then resolve that `symfony/console` can only install 3.3.6?

**Comment by laurencei** [comment]
I'm going to close this issue.

If you are running PHP 7.0, then Composer will detect this, and only install up to `symfony/console 3.3.6`.

If anyone can prove otherwise, please open a new ticket with a detailed composer install error, and we can investigate further. But at this stage it should work as expected.
