### ISSUE TITLE
Multiple middlewares: shouldn't it be an array of middlewares?

### ISSUE THREAD

**Issue by m-nachtigal** [laravel/docs#3767]
In the docs for middlewares it states, that mutliple middlewares can be applied
[https://laravel.com/docs/5.5/middleware](url)

`->middleware('first', 'second');`

That didn't work for me, an array of middleware name did, so I think this should be an array:
`->middleware(['first', 'second']);`

**Comment by jakebathman** [comment]
As of just a few days ago, it only supported an array of parameters. 

Mohamed added support for this syntax and it was released in `5.5.15`
