### ISSUE TITLE
Validation sample code is a little inaccurate? 5.5

### ISSUE THREAD

**Issue by juliomarcos** [laravel/docs#3784]
To be completely honest I'm not entirely sure but I couldn't make the sample code to work.

```
 $request->validate([
        ...
    ]);
```

What actually worked was 
`$this->validate($request, [...]);`

Maybe I'm missing to use a trait?

**Comment by stuartmccord** [comment]
Can't find where in the docs you are referring to but you are supposed to insert your validation rules between the ``[]``.  This is the example taken from the [laravel docs](https://laravel.com/docs/5.5/validation)

```php
    $validatedData = $request->validate([
        'title' => 'required|unique:posts|max:255',
        'body' => 'required',
    ]);
```

**Comment by juliomarcos** [comment]
Right, and I'm doing that in both cases. The difference is that the validate method can't be found in the request method but only in the Controller (via $this). 

Here's the link to the piece of documentation I'm referring to https://laravel.com/docs/5.5/validation#custom-validation-rules

**Comment by quickliketurtle** [comment]
@juliomarcos Are you accepting the request in your method? If not I'd expect an 'undefined variable' exception.
```php
public function store(Request $request)
{
    $request->validate([
        ...
    ]);
}
```

**Comment by juliomarcos** [comment]
I am so sorry... I've misused composer, I thought the install command behaved like npm install, although it's listed 5.5 in composer.json I've just learned that my installation is using 5.4 opening Application.php.
