### ISSUE TITLE
Typo in 'Pad' method link from collection's available methods

### ISSUE THREAD

**Issue by ivangan2307** [laravel/docs#3820]
Hi, I found a typo in the uri for the 'Pad' available method here:
[https://laravel.com/docs/5.5/eloquent-collections#available-methods](https://laravel.com/docs/5.5/eloquent-collections#available-methods)

It links to: https://laravel.com/docs/5.5/docs/5.5/collections#method-pad instead of [https://laravel.com/docs/5.5/collections#method-pad](https://laravel.com/docs/5.5/collections#method-pad)

**Comment by paulofreitas** [comment]
@ivangan2307 This was fixed in #3821. Could you please close this issue to mark it as resolved? Thanks for reporting! 👍   😉
