### ISSUE TITLE
Closure validation documentation

### ISSUE THREAD

**Issue by KKSzymanowski** [laravel/docs#3879]
I cannot find any documentation on closure validation, but from I remember something like this has been added in Laravel 5.5 and it appears to work.

```php
public function rules()
{
    return [
        'name' => [
            'required',
            function($name, $value, $fail) {
                if($value == 'foo') {
                    $fail('Name cannot be foo');
                }
            },
        ],
    ];
}

**Comment by carusogabriel** [comment]
You can find it in [`Complex Conditional Validation` sub topic](https://laravel.com/docs/5.5/validation#conditionally-adding-rules) :smile:

**Comment by KKSzymanowski** [comment]
That, I think, is a completely different topic.
In the chapter you linked there's only mention of the `sometimes` validation rule which uses the closure to determine whether or not to apply specific rules.

In my question I was referring to using an inline closure instead of extending the Validator instance to add a new rule on the fly.
