### ISSUE TITLE
Expose all posible option values for resource controller method

### ISSUE THREAD

**Issue by lunfel** [laravel/docs#3892]
I suggest we should expose all posible available keys in the `$options` array for the `Route::resource` method.

So far, in the docs, we can figure those out:
only, except, name and parameters

Is there other supported options that aren't documented? Can I add "middleware" in the options? Can anyone confirm the available options?

[Resources Controllers](https://github.com/laravel/docs/blob/5.5/controllers.md#resource-controllers)

**Comment by carusogabriel** [comment]
So far we have examples of what you said: `only`, `except`, `name` and `parameters`. Only missing `middleware`, as you said.

All the options can be found in [`PendingResourceRegistration`](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/PendingResourceRegistration.php) class.

**Comment by lunfel** [comment]
Thanks!
