### ISSUE TITLE
The homestead installation docs were not playtested

### ISSUE THREAD

**Issue by ftrotter** [laravel/docs#3897]
As far as I can tell, laravel is not actually installed when the "install" portion has ended and the "daily usage" section begins.

The setup of the ssh keys is missing from instructions. 

The whole thing needs to be playtested once on a fresh (i.e. no vagrant installed, no ssh keys already generated) computer by someone who knows what they are doing, but does not have artififacts already in place. The current instructions are clearly made by someone who already had things setup, like having a laravel instance in the ~/code directory for instance. 

I hate to leave a bug for something rather than a pull request for a fix, but I just do not know enough about the correct installation process here.

-FT

**Comment by svpernova09** [comment]
Hi! Thanks for the feedback!

The Homestead docs assume you already have a Laravel project installed somewhere since you can't map a folder into the virtual machine if it hasn't already been created.
