### ISSUE TITLE
Nginx config sample in deployment section

### ISSUE THREAD

**Issue by Virp** [laravel/docs#3898]
Not specified parameter in PHP-FPM section of config. Parameter **SCRIPT_FILENAME** not included in default fastcgi_params file (nginx installed from official ubuntu/debian repository).
Must be:
```
location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
```

**Comment by laurencei** [comment]
@fideloper - as the server expert; are you able to help comment on this? Should we update the docs, or are they ok as they are?

**Comment by fideloper** [comment]
From every server I've checked, he's wrong. It's included in `fastcgi_params` and the secondary `fastcgi.conf` file included with Debian/Ubuntu Nginx.

**Comment by Virp** [comment]
Default fastcgi_params file
`fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;`
from _deb http://nginx.org/packages/ubuntu/ xenial nginx_
nginx version: nginx/1.12.2

**Comment by laurencei** [comment]
Yeah, every install I've ever had worked as well.

I'm going to close this ticket for now. It is impossible to list every config option for all server builds. It is plausable that everyone will need to tweak some settings depending on how it is built.
