### ISSUE TITLE
Eloquent Events missing example

### ISSUE THREAD

**Issue by garyross** [laravel/docs#3915]
In the[ Eloquent > Events documentation](https://laravel.com/docs/5.5/eloquent#events) the following code is given:

```
protected $dispatchesEvents = [
        'saved' => UserSaved::class,
        'deleted' => UserDeleted::class,
    ];
```

At this point the documentation should have an example `UserSaved::class`. Instead, it sends you to the https://laravel.com/docs/5.5/events page which is a very detailed explanation of Laravel Events. Using artisan as so:
`php artisan make:event UserSaved `
 creates

```
namespace App\Events;

use Illuminate\Broadcasting\Channel;
..
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class UserSaved
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

 
    public function __construct()
    {
        //
    }

    public function broadcastOn()
    {
        return new PrivateChannel('channel-name');
    }
}
```

but the purpose of the `broadcastOn` doesn't appear anywhere.

**Comment by laurencei** [comment]
Hi @garyross - what exactly do you think can be improved here?

From what I can see - you can create a `UserSaved` event. Then in the events section, you can see the options about how to respond to that event?

**Comment by garyross** [comment]
Hi @laurencei 
Thanks for your response.
Well, crucially the docs don't show that the UserSaved event receives an instance of the model itself through the constructor, and without that knowledge it's not easy to see how to make the UserSaved class respond to the event:

```
class UserSaved{
    public function __construct($user)      // not in docs as far as I can see
    {
        $this->user = $user;
    }
}
```

The docs, which in general are excellent, here seem to be very helpful provided you are familiar with events as opposed to the user who's coming to it from scratch. A simple example of a UserSaved event doing something practical (such as saving a hashId) would help a lot for people coming to this page with no knowledge of events.

**Comment by laurencei** [comment]
I think it is covere by this part: https://laravel.com/docs/5.6/events#defining-events

> An event class is a data container which holds the information related to the event. For example, let's assume our generated OrderShipped event receives an Eloquent ORM object:

Does that clarify the situation? Or do you have an idea how it could be made clearer perhaps?

**Comment by garyross** [comment]
Hi @laurencei,
I think the problem is the disconnect between the example in https://laravel.com/docs/5.5/eloquent#events page, and the example in the https://laravel.com/docs/5.5/events#defining-events page.

I think it would be improved by making both examples the same. i.e. in the https://laravel.com/docs/5.5/eloquent#events page 
it should be the OrderShipped example rather than the UserSaved example. Or simply add the UserSaved example to the Events page. 

It certainly needs to be more explicit that the User instance is automatically injected. In my case, I find the Events documentation very useful *now that I understand it fully*. However, for someone trying to put these two things together it's not all that easy.

tbh, I think a User example as opposed to a Order example would improve things. As the User class is such a familiar item. In the example as presented, the docs are talking about an OrderShipped event without mentioning an Order class except in passing further down the document.

**Comment by laurencei** [comment]
Ok - I've submitted a PR to update the Eloquent examples first to be the single `Flight` example used.

**Comment by laurencei** [comment]
@garyross - as you can see, Taylor closed the PR. As mentioned in the PR, he doesnt think it is confusing.

I'm going to close the issue here as a result.

If you have a different way the docs could be improved then if you want to submit a PR with some of the changes, and Taylor can review that.

**Comment by garyross** [comment]
@laurencei 
Fair enough. Although I think that was my point - it's clear if it's already clear, and who doesn't know more about Laravel than Taylor :-)

**Comment by robjbrain** [comment]
I've just found this page after getting confused and Googling. The docs definitely need to be updated (and i'm not sure your PR actually solved the issue @laurencei)

The docs say to use either use an observer or something like this: (in my case I realised the observer didn't get used if you extended the User class, so I wanted something that would be on the User class itself).

So I wound up with this from the docs:

```php
protected $dispatchesEvents = [
    'saving' => UserSaving::class
];
```

But it gives no indication what the UserSaving class should look like and like @garyross said it just links to the Events page which is pretty unrelated.

If you generate an event you're given what @garyross posted in the first message, which doesn't look that relevant.

If you were using an observer it might look something like this:

```php
class UsersObserver
{
    public function saving(User $user){
        if (!$user->group_id) {
            $user->group_id = config('auth.default_group_id');
        }
    }
}
```

But what is the UserSaving class meant to look like?

```php
class UserSaving
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        if (!$user->group_id) {
            $user->group_id = config('auth.default_group_id');
        }
    }
}
```

eww that doesn't look right. Just a __construct() with everything happening in that? It can't possibly be right, but the docs don't suggest anything different? Is there a fire() or handle() method or something? No idea? What's with BroadcastOn() that doesn't look relevant to observing changes to a Eloquent model.

**Comment by laurencei** [comment]
Thanks @robjbrain.

I'll look at this again tomorrow.

Lets see if we can nut this out between the 3 of us and do a solid PR for Taylor to merge in.

**Comment by garyross** [comment]
@laurencei 
Thank you very much.

@robjbrain 
Precisely. I went through this thought process when I first came across this. 


I think [this quote by Steven Pinker](https://www.cnbc.com/2018/02/20/harvard-psychologist-steven-pinker-shares-no-1-communication-mistake.html) is relevant here!

> when you know something, it's extraordinarily difficult to know what it's like not to know it

Taylor as the genius who made Laravel perhaps struggles to understand that these connections are very far from obvious.

It might help if the 

php artisan make:event UserSaved 

itself was a bit more helpful. i.e. had a comment to the effect that the instance will be injected. 

I'm still not sure of significance of BroadcastOn

**Comment by laurencei** [comment]
`BroadcastOn` is when you want to broadcast your events.

That is covered here: https://laravel.com/docs/5.6/broadcasting

**Comment by Jossnaz** [comment]
I have no clue how to use events, the laravel docs do not explain it. A new event system was introduced, but not explained. Now I am here, still don't understand how to use it.

I want to delete a file on "deleting" this used to be very easy and very clear. Sorry my ignorance, but no, I don't get it at all

**Comment by Jossnaz** [comment]
can you just maybe provide a _simple_ example of say deleting or pretty much _any_ event class that does something simple on an event?

**Comment by Jossnaz** [comment]
soooo... I think I figured it out, what an unnecessary journey. Don't get me wrong, you guys usually do a great job, and I love laravel. Hope taylor is fine! read his twitter statement, am very worried.


So it seems the constructor is the place to put the event handling


so what I recommend:


On https://laravel.com/docs/5.5/eloquent#events
Below

```
...
    protected $dispatchesEvents = [
        'saved' => UserSaved::class,
        'deleted' => UserDeleted::class,
    ];
```

add

`php artisan make:event UserSaved`

```
class UserSaved
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public function __construct(User $u)
    {
        // DO STUFF YOU WANT TO DO ON USER SAVED
    }
}
```

that should solve all questions

**Comment by driesvints** [comment]
Made a PR for this with two smaller changes who should hopefully make this more clear for newer users ^
