### ISSUE TITLE
Code Example for Removing Anonymous Global Scopes

### ISSUE THREAD

**Issue by mint-ws** [laravel/docs#3916]
Perhaps this is too obvious for serious coders but it would help noobs like me if we provide an example of how to remove an anonymous global scope here:

https://github.com/laravel/docs/blob/5.5/eloquent.md#removing-global-scopes

The example in the docs does not remove an anonymous global scope (at least for me with L5.5.24):
`User::withoutGlobalScope(AgeScope::class)->get();`

Whereas this does:
`User::withoutGlobalScope('age')->get();`

**Comment by emilv** [comment]
Of course you can't remove an *anonymous* global scope by referring to an unrelated class name. Your second example is how it is supposed to be done. You can send in a PR with your suggested update!
