### ISSUE TITLE
Passport migrations not exporting under homestead and in other contexts

### ISSUE THREAD

**Issue by TimOgilvy** [laravel/docs#3921]
Following the default instructions for passport does not result in migrations being generated.

https://github.com/laravel/passport/issues/197 

Some additional guidance would be good.  Currently destroying my homestead box to rebuild and see if that addresses the issue.

**Comment by TimOgilvy** [comment]
Destroying the vagrant box worked. This could be easier, and clearer in the doc.

**Comment by laurencei** [comment]
@TimOgilvy - are you able to expand on what the problem was, or what you think the documentation should be clearer on?

Thanks

**Comment by laurencei** [comment]
Closing this issue, as reviewing the linked Passport issue, it was resolved there.

**Comment by TimOgilvy** [comment]
@laurencei Sorry for the late reply, I couldn't reproduce the error. Should be fine. Thanks :)
