### ISSUE TITLE
Markdown V5.4 - Not handled

### ISSUE THREAD

**Issue by tanguc** [laravel/docs#3928]
Hi,

It seems that in the version 5.4 of Laravel the markdown system is not implemented yet : https://laravel.com/docs/5.4/notifications#markdown-mail-notifications

**Comment by carusogabriel** [comment]
What do you mean? Email Markdown [was added](https://github.com/laravel/framework/blob/5.4/CHANGELOG-5.4.md#mail) at `Laravel 5.4` :thinking:
