### ISSUE TITLE
Laravel 5.5 Documentation - Database: Seeding

### ISSUE THREAD

**Issue by marcnewton** [laravel/docs#3935]
Hello Laravellers.

In https://laravel.com/docs/5.5/seeding

#### 1) Wrong use model stated

After paragraph:

> As an example, let's modify the default DatabaseSeeder class and add a database insert statement to the run method:

```use Illuminate\Database\Eloquent\Model;``` should be ```use Illuminate\Support\Facades\DB;```

#### 2) Missing instruction

There is nothing stating that ```composer du``` should be run after creating a new seeder in order for the seeder to work, this is required otherwise the following error will occur:

> In Container.php line 752: Class UsersTableSeeder does not exist

I can confirm the following file content functions correctly when the two steps above are applied:

#### DatabaseSeeder.php

```php
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call([
            UsersTableSeeder::class
        ]);
    }
}
```

#### UsersTableSeeder.php

```php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
             'name' => 'Mr Example', 'email' => 'example@example.com', 'password' => bcrypt('secret'),
        ]);
    }
}
```

Following the current published instructions as is leads to an error and requires search 3rd party websites for an answer.

Originally I posted this issue on laracasts before I knew to come here, if you want to see some additional comments on usage confirmation: 
https://laracasts.com/discuss/channels/laravel/laravel-55-docuentation-database-seeding

**Comment by michaeldyrynda** [comment]
You can submit a PR to the docs repository with your changes 👍🏻
