### ISSUE TITLE
decodeResponseJson() and other helpful methods for testing are not mentioned in the docs

### ISSUE THREAD

**Issue by sushchyk** [laravel/docs#3937]
When you write feature tests for your API, you often need to decode JSON responses in to make assertions for returned data (some assertions cannot be written just with `assertJson*` methods). For last project i was had to write `decodeResponseJson() `by own hand because i didn't know  it is already exists.
Can anyone add mention about [` decodeResponseJson()`](https://laravel.com/api/5.5/Illuminate/Foundation/Testing/TestResponse.html#method_decodeResponseJson) to [ HTTP Tests](https://github.com/laravel/docs/blob/5.5/http-tests.md) section or just add link to the API for [`TestResponse`](https://laravel.com/api/5.5/Illuminate/Foundation/Testing/TestResponse.html) class where also other not documented helpful methods ( [`dump()`](https://laravel.com/api/5.5/Illuminate/Foundation/Testing/TestResponse.html#method_dump) ,[ `getCookie()`](https://laravel.com/api/5.5/Illuminate/Foundation/Testing/TestResponse.html#method_getCookie)) could be found in order to save precious minutes for other developers during writing tests ?)
Methods `assertValidationErrors()` and `assertJsonCount()` that [were added in 5.5.20 ](https://github.com/laravel/framework/pull/21917)version not documented as well.
I'd could to do it myself, but my English is not so perfect as to write documentation for Laravel.

**Comment by jmfederico** [comment]
Documentation for  assertJsonCount() is still missing.
