### ISSUE TITLE
Do you have any plans to translate the documentation?

### ISSUE THREAD

**Issue by MammutAlex** [laravel/docs#3946]
For example, the documentation vue has translations, if there are any plans I will be happy to join the translation

**Comment by decadence** [comment]
I think there are no such plans. Otherwise documentation would be translated long time ago.
Main reason is that docs changes very often so translations will be always out of date IMHO.
You should find your country Laravel community.

**Comment by MammutAlex** [comment]
@decadence thanks for the answer
