### ISSUE TITLE
Error on switching docs to 5.1 for configuration from latest version

### ISSUE THREAD

**Issue by ajitbohra** [laravel/docs#3952]
Steps to reproduce
1.  Visit https://laravel.com/docs/5.5/configuration 
2. switch to version 5.1

![laravel](https://user-images.githubusercontent.com/1039236/34563245-e03de180-f177-11e7-8198-f3c23457e6ea.jpg)

**Comment by nathanczachur** [comment]
5.1 doesn't have a configuration file. Not sure if this is an issue really.

**Comment by ajitbohra** [comment]
@nathanczachur thank you, I am aware of that

**Comment by laurencei** [comment]
Thanks - I've submitted a PR to make docs have "better" 404's if they dont exist: https://github.com/laravel/laravel.com/pull/174
