### ISSUE TITLE
Application Testing Documentation

### ISSUE THREAD

**Issue by slillo** [laravel/docs#3961]
Looking at the [Application Testing](https://laravel.com/docs/5.2/testing#application-testing) section, seems that _visit_ and _see_ methods are integrated and avialable just extending TestCase.

I'm using laravel 5.5.28 and doing this test:

    $this->visit("testtrad")->see("Si è verificato un errore");

I get the error:
Error: Call to undefined method Tests\Feature\YourTest::visit()

I had to investigate a bit to find that this feature is part of [laracast/integrated](https://github.com/laracasts/Integrated/wiki/Installation-and-Setup) package

**Comment by gmsantos** [comment]
Please visit the documentation for Laravel 5.5 https://laravel.com/docs/5.5/http-tests

The link you posted refer to Laravel 5.2

**Comment by slillo** [comment]
my fault, I'm sorry
