### ISSUE TITLE
Laravel 5.1 compatibility with PHP 7.2

### ISSUE THREAD

**Issue by zulrang** [laravel/docs#3974]
In https://github.com/laravel/docs/pull/3889 @taylorotwell mentioned making 5.1 work with PHP 7.2.

Is there any progress on this or further discussion?

**Comment by laurencei** [comment]
@zulrang - is there any specific error you get on Laravel 5.1 with PHP7.2?

I've not seen any recent open tickets about problems with it?

**Comment by laurencei** [comment]
@zulrang - I've test Laravel 5.1 against PHP 7.2 - and all tests pass green at the moment.

I'm not aware of any outstanding issues. If you find any - feel free to submit an issue for them,

**Comment by zulrang** [comment]
The issue mentioned here: https://github.com/laravel/framework/issues/22843

**Comment by laurencei** [comment]
I know 5.2 and 5.3 do not work with PHP7.2

I'm not sure about 5.1 - that was LTS so some changes were pushed there to make it work.

In an ideal world you would just update to 5.5 anyway. But if not - if there is a specific issue for 5.1 let me know

**Comment by bdteo** [comment]
Why don'y you just add a note that Laravel 5.1 will not support php >= 7.2 ?

Laravel 5.1 has major issues with php 7.2. Failing to mention this fact in the docs is a major mistake.
