### ISSUE TITLE
Misleading .env.testing usage guidelines

### ISSUE THREAD

**Issue by IlCallo** [laravel/docs#3988]
From L5.5 docs (but it's the same in previous and following versions I guess).

> You may also create a .env.testing file. This file will override the .env file when running PHPUnit tests or executing Artisan commands with the --env=testing option.

I've recently started using a `.env.testing` file instead of the `phpunit.xml` env configuration options (aka, I removed those options from the xml files and put them into the env file).
Some of my tests started failing because of this.
I pinpointed the problem in the fact that laravel checks if it must use or not the `.env.testing` file based on content of the `APP_ENV` environment variable.
Of course, if I clean the  env variables defined into the `phpunit.xml` file, Laravel will then search the `.env` instead.

I find pretty "hacky" that to make the application use the right env file to load environment variables, you actually need to set an environment variable in another way, but maybe there is not another cleaner way (I don't know if it's possible to check in another way if the application have been called by phpunit or not).

That's not the point of this issue anyway: what could be done, if it's not possible to avoid to set the `APP_ENV` variable, is at least to notify that for the "hack" to work, there must always be at least this code in the `phpunit.xml` at the end of the file

    <php>
        <env name="APP_ENV" value="testing"/>
    </php>

**Comment by michaeldyrynda** [comment]
The `APP_ENV=testing` variable is in the default [`phpunit.xml` file](https://github.com/laravel/laravel/blob/master/phpunit.xml), though?

**Comment by IlCallo** [comment]
Yes, of course.

**Comment by laurencei** [comment]
> I find pretty "hacky" that to make the application use the right env file to load environment variables, you actually need to set an environment variable in another way

The problem is how else would Laravel know it to load the `.env.testing` is it does not know it is actually in a `testing` environment in the first place?

**Comment by laurencei** [comment]
I re-read the docs. It is mention in the https://laravel.com/docs/5.6/testing section:

> When running tests via phpunit, Laravel will automatically set the configuration environment to testing because of the environment variables defined in the phpunit.xml file
