### ISSUE TITLE
except,idColumn not documented for unique rule

### ISSUE THREAD

**Issue by pierrocknroll** [laravel/docs#4008]
Hello,
Can you please explain what is the meaning of "**except,idColumn**" in unique validation rule ?
https://laravel.com/docs/5.5/validation#rule-unique

Thanks a lot

**Comment by lagbox** [comment]
You have to go back to 5.2 to get it: https://laravel.com/docs/5.2/validation#rule-unique

**Comment by laurencei** [comment]
I believe this is resolved and now in the 5.5/5.6 docs?
