### ISSUE TITLE
Request: Shortcut to start searching

### ISSUE THREAD

**Issue by JeramyNS** [laravel/docs#4015]
When in the documentation area of the website, can we please have a shortcut to jump straight to the search bar or at the least to the top of the page?

It's really annoying to have to scroll all the way up to the top of the page just to find and go to another documentation page. Also, things are so much faster when you can use the keyboard to navigate

For example, the basic CTRL+F would work, unless you don't wanna mess with the built in page search then CTRL+SHIFT+F would be just as cool.

P.S. Not sure if this is the right place to post, as this repo doesn't really affect website functionality, but the laravel.com repo has no issue tracker.

**Comment by michaeldyrynda** [comment]
You can already hit the <kbd>/</kbd> key on your keyboard and that'll pop your cursor right in the search field. Is that what you're after?

**Comment by JeramyNS** [comment]
YASSS Thank you. 
Saved a life
