### ISSUE TITLE
[5.5] Installation Via Laravel Installer information is out of date

### ISSUE THREAD

**Issue by markdwhite** [laravel/docs#4101]
https://laravel.com/docs/5.5/installation#installing-laravel

States that "laravel new blog will create a directory named blog containing a fresh Laravel installation with all of Laravel's dependencies already installed" whereas this seems to install the current version 5.6.

**Comment by laurencei** [comment]
From what I can see in the code, the Laravel installer only installs either 'dev' or 'master'. You cant specify a specific version. If you want an older version you should use the composer install.

**Comment by markdwhite** [comment]
I know what I *can* do. I just followed the next instructions on the webpage. 

The issue is that the webpage is out of date on this particular instruction now 5.6 has been released.

Maybe I'm raising this in the wrong place? I thought this was for the docs on the website...

**Comment by michaeldyrynda** [comment]
Given the way the Laravel installer currently works, it would probably be worthwhile nuking the entire section on the Laravel installer, using `composer create-project` for all previous versions of the docs.

Alternatively, submit a PR to the installer to add the ability to specify a version.

**Comment by markdwhite** [comment]
"Given the way the Laravel installer currently works, it would probably be worthwhile nuking the entire section on the Laravel installer, using composer create-project for all previous versions of the docs."

Exactly that :-)
