### ISSUE TITLE
[5.6] Logging - Customizing Monolog

### ISSUE THREAD

**Issue by kronthto** [laravel/docs#4102]
Regarding the signature of the `__invoke` method of the Log-customizer-class (defined via `tap`): In https://github.com/laravel/docs/blob/b11f7e28fc4348a8e6647a779aee450bbc533e63/logging.md#customizing-monolog-for-channels it says: 
> This class only needs a single method: __invoke, which receives the Monolog instance  
> ```php
>         /**
>          * Customize the given Monolog instance.
>          *
>          * @param  \Monolog\Logger  $monolog
>          * @return void
>          */
>         public function __invoke($monolog)
>         {
>             foreach ($monolog->getHandlers() as $handler) {
> ```

But actually an instance of `\Illuminate\Log\Logger` is passed: https://github.com/laravel/framework/blob/b34541e1eb690964854202376c2778e1b52d41d7/src/Illuminate/Log/LogManager.php#L131-L139 
This of course contains the Monolog instance, and has a `__call` that proxies to it, but is not it.

The genius I am I typed my implementation (`__invoke(\Monolog\Logger $logger)`). Took me some time to figure out, why "it didn't work". As this takes place in the error-handler, that catches and ignores Exceptions/Errors thrown during its creation, no error (*Argument 1 passed to App\Logging\CustomizeFormatter::__invoke() must be an instance of Monolog\Logger, instance of Illuminate\Log\Logger given*) was shown.

**Comment by laurencei** [comment]
@kronthto - are you able to submit a PR with the fix?

**Comment by kronthto** [comment]
I did, see #4103
