### ISSUE TITLE
Pluralization - Localization file notes

### ISSUE THREAD

**Issue by domste** [laravel/docs#4112]
There should be a hint, that the countindex in localization files have to be preceded by the | character on laravel > 5.3.

In **laravel 5.3** following code is translated correctly:
```
[
'apples' => '
        {0}I have no apples |
        {1}I like my apple |
        {2,*}I like apples'
]
```
In **Laravel 5.5** it is mandatory that the '|' precedes the curly braces else the regex is not working
```
[
'apples' => '
        {0}I have no apples
        |{1}I like my apple
        |{2,*}I like apples'
]
```

**Comment by laurencei** [comment]
@themsaid - is that right? I've got little experience with localisation stuff, and your the expert :)

**Comment by driesvints** [comment]
If this broke and it's not in the upgrade guide, you may have stumbled upon a bug. Create a PR with a failing test to the https://github.com/laravel/framework so this can be fixed. Thanks!
