### ISSUE TITLE
Add updateOrCreate() method to Eloquent Inserting & Updating Related Models

### ISSUE THREAD

**Issue by brynj-digital** [laravel/docs#4113]
The Inserting & Updating Related Models section of the [Eloquent Relationships documentation](https://laravel.com/docs/5.6/eloquent-relationships#inserting-and-updating-related-models) would benefit from adding information about the `updateOrCreate()` method for hasMany relationships.

At the moment, it's not clear you can use this method via the relationship. For example, this is perfectly valid:

    $translation = $post->translations()->updateOrCreate([
        'language_id' => 1,
    ], [
        'content' => 'A translated blog post.',
    ]);

**Comment by laurencei** [comment]
@brynj-digital - would you be able to submit a PR with this chage?

**Comment by driesvints** [comment]
Thanks. Sent in a PR for this ^
