### ISSUE TITLE
[5.5] Missing sections on https://laravel.com/api/5.5/

### ISSUE THREAD

**Issue by markdwhite** [laravel/docs#4117]
Not sure if laravel/docs is the right place for this, but something's not right in the left pane sub-menu. 

Eg: Under Illuminate\Foundation, lots of sub-folders are missing in the left pane, where they are present on the right.

![xsnap133304](https://user-images.githubusercontent.com/292063/36581223-83a49f2e-189e-11e8-81c9-e9b3e237a36f.png)

**Comment by AkenRoberts** [comment]
Seems to be affecting most/all versions of the API docs, including 5.6. However, I built the API docs locally and everything shows up in the tree.

@taylorotwell Not sure if the API docs are built automatically, but maybe regenerating them on production will rectify this?

**Comment by driesvints** [comment]
We merged some changes that should fix this.
