### ISSUE TITLE
No information about authorizeResource() method.

### ISSUE THREAD

**Issue by NaveNO** [laravel/docs#4118]
Hello there. As I see, there is no word about awesome function authorizeResource() which can apply policy to all of the resource controller's methods automatically instead of $this->authorize() in each method. Add this to docs, please! Thank you very much :)

**Comment by NaveNO** [comment]
Added pull request with fixing authorization.md file.

**Comment by laurencei** [comment]
Thanks @NaveNO  - I'll close this issue as you've done a PR - so it'll be handled there by Taylor. Thanks!!
