### ISSUE TITLE
A 5.6 policy backward incompatible change is not documented

### ISSUE THREAD

**Issue by FinesseRus** [laravel/docs#4128]
I faced an issue in my project caused by a 5.6 backward incompatible change which is not described in [the documentation](https://laravel.com/docs/5.6/upgrade).

Consider this example:

```php
class MyPolicy
{
    public function before($user)
    {
        return $user->is_staff; // Always bool
    }

    public function leavePrison($user)
    {
        return $this->before($user) || $user->free_at <= time();
    }
}

Gate::define('leavePrison', 'MyPolicy@leavePrison');

if (Gate::allows('leavePrison')) {
    echo 'You are free';
} else {
    echo 'Nope'
}
```

In Laravel 5.5 the `before` method of a policy registered through the `define` or the `resource` method was not considered. So the result of the example above depended both on `is_staff` and `free_at`.

In Laravel 5.6 the `before` method is considered. So the result of the example above depends only on `is_staff`.

**Comment by mputkowski** [comment]
First of all you shouldn't call `before` method, it's called automatically.

> If you would like to deny all authorizations for a user you should return false from the before method. If null is returned, the authorization will fall through to the policy method.

You should return true from the `before` method **only when** `$user->is_staff` is also true, otherwise your policy will deny user to perform action.

```php
class MyPolicy
{
    public function before($user)
    {
        if ($user->is_staff)
            return true;
    }

    public function leavePrison($user)
    {
        return $user->free_at >= time();
    }
}
```

More info: [Policy filters](https://laravel.com/docs/5.6/authorization#policy-filters)

**Comment by FinesseRus** [comment]
@mputkowski

> First of all you shouldn't call before method, it's called automatically.

I agree. But Laravel 5.5 didn’t call `before` methods (in case when a policy is registered through `Gate::define`) so I had to do it manually.

Laravel 5.6 does call `before` which is great. Nevertheless this is a breaking change.

**Comment by mputkowski** [comment]
Laravel 5.6 changed nothing in authorization, change in behavior is impossible.

**Comment by FinesseRus** [comment]
@mputkowski There is a change in the `Gate` class which makes it consider `before`: https://github.com/laravel/framework/compare/v5.5.0...v5.6.0#diff-961368895033e553787b301c3be0e17aL155 (switch to the «Files Changed» tab and find the `Gate.php` file).

The policy calling code in 5.5:

```php
list($class, $method) = Str::parseCallback($callback);
 
return $this->resolvePolicy($class)->{$method}(...func_get_args());
```

The policy calling code in 5.6:

```php
list($class, $method) = Str::parseCallback($callback);
 
$policy = $this->resolvePolicy($class);

$arguments = func_get_args();

$user = array_shift($arguments);

$result = $this->callPolicyBefore(
    $policy, $user, $ability, $arguments
);

if (! is_null($result)) {
    return $result;
}

return $policy->{$method}(...func_get_args());
```

**Comment by mputkowski** [comment]
Actually it has been changed in [https://github.com/laravel/framework/releases/tag/v5.5.20](5.5.20), Gate was broken so it had to be fixed.

After these changes I checked everything and it was working correctly. I think it's your code's issue...

**Comment by FinesseRus** [comment]
@mputkowski I thought the 5.5 behavior is by design, not a bug. If it is a bug, the issue needs to be closed.

**Comment by laurencei** [comment]
According to the docs - Laravel 5.5 called `before` as well. It is documented here: https://laravel.com/docs/5.5/authorization#writing-policies

At this stage there's no obvious change - it all looks like it is working as was intended.
