### ISSUE TITLE
tl_PH il8n [Tagalog Localization]

### ISSUE THREAD

**Issue by cordeta** [laravel/docs#4140]
Good day! 

If you may I would like to make a contribution to this project by localizing the files in this branch into Tagalog 

I'm a freelance translator paid by sponsors that rewards contributors to open-source projects. 

Rest assured that my work is credible.

Hoping for your response, 

Cheers!

**Comment by laurencei** [comment]
Thanks - at this stage there are no plans to provide the docs in other languages, although the community is able to do this if they want.
