### ISSUE TITLE
[Proposal] Multilanguage in the docs

### ISSUE THREAD

**Issue by omarkdev** [laravel/docs#4144]
At the beginning of the repository was proposed in the issue #76, documentation in others languages, however, it was answered that it would be better to wait. What if we now have documentation in others languages?

We could separate into several folders, more or less like this:

```
- pt-BR/
- pt/
- ru
```

I could translate to pt-BR.

**Comment by decadence** [comment]
I think that is never going to happen because other docs will be always out of date and Taylor won't be happy with that.

**Comment by omarkdev** [comment]
Whenever you release a new version of Laravel, is the documentation updated on the fly with the new features? Or do they come up because of the weather? I believe documentation in other languages will work the same way.

In the same way that a new branch is created from the previous version to the new one and things will be outdated until someone goes there and updates them, the documentation in other languages will be the same way.

My point is, the documentation will be out of date compared to the standard version, but it will continue to serve as it is done at the beginning and over time people are translating.

**Comment by browner12** [comment]
While I agree this would be good for accessibility, I feel like it would be a maintenance nightmare.

Also, in order for this to work, Taylor would have to assign a manager for every supported language to review and merge PRs, as I'm assuming Taylor is not multilingual (just like most of the rest of us).

Curious question, people who are not native English speakers, what is it like interacting with code that is all in English? One of Laravel's defining goals is being "fluent" and writing code like you would read it. If you don't understand English that benefit may be mostly moot.

**Comment by omarkdev** [comment]
I believe we are not multilingual, but we are from different languages.

Perhaps to overcome the need of people from other languages ​​to revise, we could find communities in other languages ​​especialized in translations or Laravel. 

I see more and more people starting out in the programming world wanting to learn Laravel, do you think that for these people a documentation in your language would not help?

**Comment by laurencei** [comment]
Taylor has previously stated (just as recently as a few weeks ago) - people are able to do this yourself as a community project, but he has no plans to include this on the official docs.
