### ISSUE TITLE
Broken styling for information/note alerts

### ISSUE THREAD

**Issue by MattRogowski** [laravel/docs#4152]
I’m seeing broken icon styling in the alerts in Chrome 65 and Firefox

![image 1](https://user-images.githubusercontent.com/545339/37098413-ba37a7cc-2215-11e8-9148-ac7d7eb57ef0.png)
![image 2](https://user-images.githubusercontent.com/545339/37098421-be284a1c-2215-11e8-88ce-b18dfdf5c466.png)

**Comment by citricsquid** [comment]
This was caused by [this commit](https://github.com/laravel/laravel.com/commit/07d2d440c8b81b38edb94ecdeb3e98e10fccfe32), because the documentation uses a `.flag` class that has been declared again for the community page, but at a global level. I've submitted a PR to fix it.
