### ISSUE TITLE
Navigation links in the bottom of each article

### ISSUE THREAD

**Issue by goncalomcunha** [laravel/docs#4161]
How about having some links to the next and previous article in the bottom of each article? Every time I reach the end of an article, I have to scroll all the way up to go to the next article. 

In mobile, I have to scroll all the way up, click the hamburger, and then scroll down until I find the next article link.

Something like this would be nice:

![1](https://user-images.githubusercontent.com/9417934/37252031-787b6b2a-2512-11e8-8a1e-125290f86e00.png)

**Comment by laurencei** [comment]
This assumes you are browsing the entire document from start to finish though. Most instances would be someone looking up a specific topic.

It also creates an increased level of micro management of the docs. Anytime a new "page/topic" is created, someone would have to edit the other files.

You are welcome to submit a PR with this change though for Taylor to consider.
