### ISSUE TITLE
Add a deployment guide?

### ISSUE THREAD

**Issue by shalvah** [laravel/docs#4177]
The documentation comes with good installation instructions. However, I've realized lots of devs (especially PHP newbies) often encounter difficulties when deploying. 

To be fair, this isn't the framework's fault or responsibility. And I know that the wide variety of hosting environments out there make a comprehensive deployment guide an impossible task. However, is there any possibility we could have a guide that focuses on the important aspects that apply to the most popular hosting types (shared, VPS etc), maybe with links to more detailed guides elsewhere? The idea is to point devs in the right direction when they're done with local development.

**Comment by michaeldyrynda** [comment]
I think if anything, a how-to for Forge, but I wouldn't specifically do anything else - especially shared. Too many variables, otherwise.

**Comment by Kyslik** [comment]
https://serversforhackers.com/s/start-here is really good resource, and if you are curious enough you will find many resources for free.

**Comment by ColinLaws** [comment]
I do agree that Laravel holds your hand so much that it's pretty safe to say you're encountering a lot of people that are doing web (and php for that matter) with Laravel, and do not know how to properly roll out production code or use common production practices.

The problem with adding it to the Laravel docs is that it isn't necessarily about Laravel. You can plug Laravel into different servers using different software, and they'll all work. It's a flexible framework that is capable of being deployed in many flavors. So I don't think you'll see a definitive "this is how you deploy Laravel" doc. Though a simple example wouldn't hurt for the newcomers to web, is it Laravel's responsibility to inform developers about these practices? Probably not. 

You'd basically be writing docs for how to configure Nginx, Apache, PHP, servers, etc., which would be redundant as they have their own docs.

**Comment by laurencei** [comment]
> To be fair, this isn't the framework's fault or responsibility

Pretty much this. The scope is massive, and there are too many variables.

Laravel already promotes Forge and Envoyer as options - so if you need a hand you have official options available.
