### ISSUE TITLE
PhpRedis and the Redis Alias Note

### ISSUE THREAD

**Issue by toddstoker** [laravel/docs#4214]
From:
https://github.com/laravel/docs/blob/5.5/redis.md#phpredis
https://github.com/laravel/docs/blob/5.6/redis.md#phpredis

Regarding the following note:
> {note} If you have the PhpRedis PHP extension installed via PECL, you will need to rename the Redis alias in your config/app.php configuration file.

The note is no longer relevant, correct? It looks like (since 5.5) RedisManager correctly resolves the Predis/PhpRedis Connectors based on the driver defined in the database.php config file.

**Comment by laurencei** [comment]
@tillkruss - your the Redis expert. Thoughts?

**Comment by tillkruss** [comment]
@toddstoker: Have you tried having the alias with PhpRedis installed?

I know the facade is working fine.

**Comment by tillkruss** [comment]
Yeah, seems to be working fine with the alias.

**Comment by driesvints** [comment]
This is fixed in the meantime.
