### ISSUE TITLE
BC in 5.4 .. 'errors.404' in app/Providers/ComposerServiceProvider.php

### ISSUE THREAD

**Issue by jonnott** [laravel/docs#4216]
In upgrading an app from Laravel 5.3 to 5.4, I had a view composer configured in ComposerServiceProvider::boot() thusly:

        view()->composer(
            ['home', 'errors.404'],
            'App\Http\ViewComposers\IndividualCountComposer'
        );

..to make a variable available on both the homepage and 404 error page templates. In 5.4, I had to change this to:

        view()->composer(
            ['home', 'errors::404'],
            'App\Http\ViewComposers\IndividualCountComposer'
        );

(double colon :: rather than dot . between 'errors' and '404').

The upgrade docs for 5.4 make no reference to this whatsoever (I Googled and eventually found a Laracasts forum post with the solution), but I'd say it's a backwards-compatibility breaking change, and so should be documented.

Now, I don't have enough knowledge to know *why* this change is needed, how it now works, or indeed even know enough about view composers to document this breaking change myself, but I think it'd be a useful addition to the 5.4 upgrade docs.

**Comment by laurencei** [comment]
I've looked through the code - and I cant work out why this is breaking either.

Do you have a link to the Laracasts post where this was also mentioned?

**Comment by jonnott** [comment]
It is breaking because it changed! So it’s a breaking change ;)

**Comment by driesvints** [comment]
Since 5.4 isn't supported anymore I'm gonna close this.
