### ISSUE TITLE
Mailer::alwaysTo() and Mailler::alwaysFrom()

### ISSUE THREAD

**Issue by edenr2** [laravel/docs#4246]
These two are public methods and they are not mentioned in the docs as far as I know.
I had to look into the code to find them. Would be nice if it was in the docs aswell.

**Comment by driesvints** [comment]
I've sent in a PR for this but instead documented the fact that you can set these in the config file. Think that's a little more clear that way since the "from" one is also set this way.

Thanks for reporting 👍
