### ISSUE TITLE
[5.6] Package "nunomaduro/collision" missing from upgrade guide 

### ISSUE THREAD

**Issue by kevin-ferradj** [laravel/docs#4253]

**Comment by nunomaduro** [comment]
@kevin-ferradj Thank you for bringing that to our attention! I will work on a pull request to fix that this week. 👍

**Comment by laurencei** [comment]
@nunomaduro - how did you go with the PR?

**Comment by laurencei** [comment]
ping @nunomaduro

**Comment by driesvints** [comment]
Gonna close this but feel free to send in a PR.
