### ISSUE TITLE
Mention User primaryKey in Authentication docs.

### ISSUE THREAD

**Issue by evanernest** [laravel/docs#4255]
It might be good to mention that the primaryKey property must be set correctly on the User model when using it to authenticate. Just started a new app and used the `make:auth` scaffolding, and then spent too-long trying to figure out why it wasn't working, but wasn't complaining about bad credentials. Turns out that it was because my users table used `user_id` instead of `id` as a primary key. It was successfully authenticating my user, but not storing the id in the session to retrieve it after the redirect to /home. I set the primaryKey property, and now everything works.

Obviously, I wouldn't have gotten far with my app without setting this anyways, but it would have been helpful to have a mention in the docs, perhaps in the "Database Considerations" section.

**Comment by ahinkle** [comment]
Generally, the `primaryKey` is ignored, as it is usually set to `id`.  It's already mentioned in the [Eloquent](https://github.com/laravel/docs/blob/018ad3d2ed6988f138333345d7c782f72998c5e9/eloquent.md#primary-keys) section. No need to duplicate it once more.

**Comment by driesvints** [comment]
Heya, thanks for sending this in. This has indeed already been documented at the link @ahinkle mentions. As you say, this doesn't only affects auth but everything related to your model.
