### ISSUE TITLE
Methods sortKeys() and sortKeysByDesc() don't exist on Collection

### ISSUE THREAD

**Issue by PetrKravets** [laravel/docs#4294]
These methods sortKeys() and sortKeysByDesc() don't exist on Collection
https://laravel.com/docs/5.6/collections#method-sortkeys
https://laravel.com/docs/5.6/collections#method-sortkeysdesc

**Comment by decadence** [comment]
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/Collection.php#L1508

Ensure you're using Laravel version above 5.6.6

**Comment by PetrKravets** [comment]
Oh. Thanks. It helped.
