### ISSUE TITLE
Not all collection methods are chainable

### ISSUE THREAD

**Issue by leewillis77** [laravel/docs#4295]
The documentation on collections (https://laravel.com/docs/5.6/collections#available-methods) states the following:

> Remember, all of these methods may be chained to fluently manipulate the underlying array

However - this isn't at all accurate.

Specifically, there are some collection methods that return an item from the collection, not a collection, and hence can't be chained, e.g.
* first()
* firstWhere()
* last()
etc.

There are also a set of operations that return a value of some kind, and not a collection, e.g.
* avg()
* average()
* contains()
* containsStrict()
* count 
etc.

I'd suggest changing it to "Many of these methods return a collection, in which case you can chain operations" perhaps with an example. 

For bonus points it might be nice to separate out the chainable collection-returning methods from the reducing-to-a-value methods.

**Comment by laurencei** [comment]
Hi @leewillis77 - please feel free to submit a PR with your suggested change for Taylor to consider.
