### ISSUE TITLE
SQLite - Modifying and Dropping Columns 

### ISSUE THREAD

**Issue by johnwheal** [laravel/docs#4311]
The documentation contains the following warning in relation to database migrations (https://laravel.com/docs/5.6/migrations#creating-columns):

> Dropping or modifying multiple columns within a single migration while using a SQLite database is not supported.

This warning is in the Dropping Columns section of the documentation. The warning also applies to Modifying Columns which is an earlier section. It took me several hours to debug this issue because I was not reading the Dropping Columns section - the issue also seems to result in very cryptic messages. I think this warning should either be duplicated or moved to earlier in the documentation.

**Comment by laurencei** [comment]
Hi @johnwheal - feel free to submit a PR with a new location for the warning, and that way Taylor can consider it.
