### ISSUE TITLE
Add Blade note about use complex code on directives

### ISSUE THREAD

**Issue by eusonlito** [laravel/docs#4360]
Referrer to https://github.com/laravel/framework/issues/24734 and concrete to https://github.com/laravel/framework/issues/24734#issuecomment-402633393

I think that Blade docs should add a notice/warning about to avoid to use complex code on directives.

I could to send a PR but my english is not good enough to explain this problem :)

**Comment by driesvints** [comment]
I personally don't think we should add a warning for this. It should be pretty clear that directives aren't meant to do super complex and long things inside them. They're in the first place used to pass along compiled code to further manipulate it inside the directive.

If you still feel this should be made more clear feel free to send in a PR.
