### ISSUE TITLE
The testing page is missing 70% of the content

### ISSUE THREAD

**Issue by inquiloper** [laravel/docs#4378]
https://laravel.com/docs/5.5/testing
https://laravel.com/docs/5.6/testing

https://laravel.com/docs/5.1/testing --> working properly

**Comment by michaeldyrynda** [comment]
The single-page testing docs were split into their own section across multiple pages (Getting Started, HTTP Tests, Browser Tests, Database, Mocking).

**Comment by inquiloper** [comment]
@michaeldyrynda  Thanks, I wasn't aware of that for some reason.
