### ISSUE TITLE
Confusing example under Naming Resource Route Parameters

### ISSUE THREAD

**Issue by sebsel** [laravel/docs#4395]
On [this page](https://laravel.com/docs/5.6/controllers#resource-controllers) there is a note about naming resource route parameters, which states: 

> By default, Route::resource will create the route parameters for your resource routes based on the "singularized" version of the resource name. You can easily override this on a per resource basis by passing parameters in the options array. "

And comes up with the following example:

```php
Route::resource('user', 'AdminUserController')->parameters([
    'user' => 'admin_user'
]);
```

What confused me was the fact that, if you define a route like this: (also note the plural)
```php
Route::resource('user-roles', 'UserRolesController');
```
... it would generate a route like `user-roles/{user_role}`. However, I cannot:

```php
Route::resource('user-roles', 'UserRolesController')->parameters([
    'user_role' => 'user'
]);
```

I have to specify the resource itself:
```php
Route::resource('user-roles', 'UserRolesController')->parameters([
    'user-roles' => 'user'
]);
```

Maybe the documentation is better served by an example that reflects this? :)

**Edit:** not sure if my own example is a good one. Feels kind of hacky now that I think of it. But the plural / singular makes it confusing too.

**Comment by lagbox** [comment]
Fixed by laravel/docs#4400
