### ISSUE TITLE
Artisan console: Progress bars symfony link outdated.

### ISSUE THREAD

**Issue by dmeltzer** [laravel/docs#4396]
Hello,

in the latest (5.6) documentation for the artisan console section (https://laravel.com/docs/5.6/artisan) the progress bars section links to 
https://symfony.com/doc/2.7/components/console/helpers/progressbar.html

Clicking on that link provides a warning that symfony 2.7 is way out of date, and checking laravels composer.json a much newer version of symfony is used.  I don't know if theres an easy way of linking this to the current symfony version number, but feels like it should be updated

**Comment by decadence** [comment]
Fixed. You can close the issue.
