### ISSUE TITLE
BroadcastServiceProvider in upgrade section of doc

### ISSUE THREAD

**Issue by alessandrofuda** [laravel/docs#4398]
Hi,
in `boot()` method of `BroadcastServiceProvider` class, 
the code change 

from (L 5.5):
`Broadcast::routes();
Broadcast::channel('App.User.*', function ($user, $userId) {
   return (int) $user->id === (int) $userId;
        });`

to (L 5.6):
`Broadcast::routes();
require base_path('routes/channels.php');`

it's right ? There is'nt in upgrade guide.
Good day

**Comment by michaeldyrynda** [comment]
The end result is ultimately the same; just where it’s stored that is different (unless the `*` no longer works in 5.6?)

It’s not a breaking change, so it doesn’t _have_ to be updated.

**Comment by laurencei** [comment]
Yeah, this is an optional change. The docs refer to the fact that you should consider comparing the `laravel/laravel` with your own app for possible changes.
