### ISSUE TITLE
Multiple middleware example is wrong...

### ISSUE THREAD

**Issue by dbugit** [laravel/docs#4399]
To define multiple middleware verifications, middleware method should receive an array.

Wrong:
```
Route::get('/', function () {
    //
})->middleware('first', 'second');
```

Correct:
```
Route::get('/', function () {
    //
})->middleware(['first', 'second']);
```

**Comment by decadence** [comment]
Laravel supports both options, doesn't it?

**Comment by dbugit** [comment]
According to the documentation it's not clear...
I tried as the example and it was only "reaching" the first middleware...
When using an array it works perfectly...
Can someone confirm?
Anyway it seem more clear and logic that it takes an array instead of an
unlimited number of parameters...
Don you agree?


On 29 Jul 2018 18:01, "Victor Isadov" <notifications@github.com> wrote:

Laravel supports both options, doesn't it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/laravel/docs/issues/4399#issuecomment-408690979>, or mute
the thread

**Comment by lagbox** [comment]
```php
    /**
     * Get or set the middlewares attached to the route.
     *
     * @param  array|string|null $middleware
     * @return $this|array
     */
    public function middleware($middleware = null)
    {
        if (is_null($middleware)) {
            return (array) ($this->action['middleware'] ?? []);
        }

        if (is_string($middleware)) {
            $middleware = func_get_args();
        }

        $this->action['middleware'] = array_merge(
            (array) ($this->action['middleware'] ?? []), $middleware
        );

        return $this;
    }
```

**Comment by laurencei** [comment]
Hi - what was the outcome of this?

**Comment by dbugit** [comment]
Hi,

In fact lagbox is right, but still, the documentation should be more clear.
For it only worked when using the array as input... still do not know why..
Its a simple add to the documentation and more clear

**Comment by jonnott** [comment]
Looks like the middleware() method only accepts one argument $middleware, so multiple middlewares would need to be passed in an array, yes.

**Comment by lagbox** [comment]
First what version is this issue even about?

The `middleware` method of `Illuminate\Routing\Route` can take a "variable" amount of arguments. Hence the `func_get_args()` call.

```php
Route::get(..., ...)->middleware('one', 'two', 'three');

Route::get(..., ...)->middleware(['one', 'two', 'three']);
```

Those both work perfectly fine.

The docs for 5.6 in "Middleware" show this:

>"You may also assign multiple middleware to the route:
```php
Route::get('/', function () {
    //
})->middleware('first', 'second');
```

Which is correct and is "one" of the "two" ways to pass multiple middleware to that one method.

@jonnott Incorrect.  Do you see the `func_get_args` call?

@dbugit Incorrect. It works with a variable amount of arguments as well.

**Comment by driesvints** [comment]
Docs are correct. If you think this isn't working properly please provide a PR with a failing test to laravel/framework.
