### ISSUE TITLE
Translation docs

### ISSUE THREAD

**Issue by sr2ds** [laravel/docs#4402]
I would like to contribute with a translation of the Portuguese documentation.

Is there any path to this contribution already?

**Comment by decadence** [comment]
You can share your translation for your country community but officialy there is only english docs.

**Comment by ahinkle** [comment]
The official docs currently do not support other languages. Reason being- that they change often and will be out of date. 

Duplicate of #3946
Please take a look at this repository: https://github.com/caouecs/Laravel-lang

**Comment by laurencei** [comment]
As above - please feel free to create community versions of documentation as needed.
