### ISSUE TITLE
Eloquent model refresh documentation

### ISSUE THREAD

**Issue by stephan-v** [laravel/docs#4430]
I was wondering if there is a specific reason why this is not on the model eloquent page:

`$model->refresh()`

https://laravel.com/docs/5.6/eloquent

It seems this would be a really helpful thing to note, since when you have created a table with column defaults, these defaults will not be returned unless you have explicitly set them.

An example of this would be creating a record from request data that has a default `status` of 0 in MySQL. This `status` data is not being sent along with the form so in order to retrieve the default status of the model along with the model's filled request properties you are forced to do a refresh.

You could manually send along the status by a hidden input, explicitly setting it in an XHR request of setting this in the controller by merging the status with the current request attributes. These are all options that can cause your status to go out of sync when the default changes in MySQL.

**Comment by driesvints** [comment]
I sent in a PR for this. Thanks!
