### ISSUE TITLE
loginUsername method from src/Illuminate/Foundation/Auth/AuthenticatesUsers.php was renamed in 5.3 to username

### ISSUE THREAD

**Issue by danielghitoiu** [laravel/docs#4432]
In Laravel 5.3 method `loginUsername` was renamed to  `username` in https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php

If this method was overwritten in Laravel 5.2, the upgrade fails. 

I think this should be mentioned in the upgrade guide.

**Comment by michaeldyrynda** [comment]
Submit a pull request, no need to discuss this change.

**Comment by driesvints** [comment]
5.3 isn't supported anymore so closing this. If you really want it in the upgrade guide of 5.3, send in a PR.
