### ISSUE TITLE
Missing custom middleware in iexample for "assigning middleware to routes"

### ISSUE THREAD

**Issue by teo1978** [laravel/docs#4437]
https://laravel.com/docs/5.6/middleware#assigning-middleware-to-routes

It says:
> **To add your own, append it** to this list [the `$routeMiddleware` property in `\App\Http\Kernel`] and assign it a key of your choosing.
> **For example:**

But then the example shows the array that comes by default out of a freshly created Laravel application, with **nothing appended**.

**Comment by driesvints** [comment]
Sent in a PR for this. I ended up removing the `for example` wording which should make it more clear.
