### ISSUE TITLE
Lock release example Redis queue rate limiting

### ISSUE THREAD

**Issue by tomlankhorst** [laravel/docs#4442]
[queues.md#rate-limiting](https://github.com/laravel/docs/blob/5.6/queues.md#rate-limiting) suggests:

_If a lock can not be obtained, you should typically release the job back onto the queue so it can be retried later:_

First of all, things are typically 'put on' or 'pushed on' or 'enqueued on' a queue. Releasing in this context typically refers to unlocking.  

Then, the example demonstrates: 

```
Redis::throttle('key')->allow(10)->every(60)->then(function () {
    // Job logic...
}, function () {
    // Could not obtain lock...

    return $this->release(10);
});
```

To me this example makes little sense: logically one can't release a lock that is not obtained.
Even then, the argument of `->release` should be the lock name which is `key` in this case. 

So, what does this example actually intend to demonstrate? I hope to clarify this in a later PR.

**Comment by driesvints** [comment]
Feel free to send in a PR for this.
