### ISSUE TITLE
[5.6] Cache blockFor() method no longer exists and block() now takes timeout parameter

### ISSUE THREAD

**Issue by jamesggordon** [laravel/docs#4446]
In the Atomic Locks section of the Cache documentation the block() method is shown as having no parameters and the blockFor() method is shown as being the method to call if you want to block for a certain period of time.

https://laravel.com/docs/5.6/cache#atomic-locks

However, when I tried the blockFor() method I got the following error:

    Call to undefined method Illuminate\Cache\RedisLock::blockFor()

It looks like blockFor() has been removed in favour of adding the timeout parameter to the block() method.

**Comment by driesvints** [comment]
Should be fixed now ^
