### ISSUE TITLE
5.7 upgrade docs incomplete (email verification) 

### ISSUE THREAD

**Issue by teo1978** [laravel/docs#4447]
.

**Comment by teo1978** [comment]
Hey, the issue was actually valid. I thought I had missed it because I found it here:
https://laravel.com/docs/5.7/verification#verification-database

but it is not mentioned in the upgrade guide.
https://laravel.com/docs/5.7/upgrade

Any chance my original description can be recovered? (do you guys have access to the edit history?)

**Comment by teo1978** [comment]
It seems the docs fail to mention a number of other things about email verification.

- Apparently you need to add to  `app/Http/Kernel.php`:
```
'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
```
- In https://github.com/laravel/laravel/blob/develop/app/Http/Kernel.php this has been changed:
```
-        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
+        'auth' => \App\Http\Middleware\Authenticate::class,
```

The new file does not exist, so I guess it's created by the new version of  `make:auth`?? So what is one supposed to do about that when upgrading an existing application?

I wonder how many other things I need to figure out that are not mentioned in the docs in order to get this feature to work after upgrading.

**Comment by teo1978** [comment]
Yet another thing:
here https://laravel.com/docs/5.7/verification#verification-database it says
> To get started, verify that your App\User model implements the  Illuminate\Contracts\Auth\MustVerifyEmail contract.

No example code is provided of how to do that, neither here nor in the Migration docs where this is not mentioned.

**Comment by michaeldyrynda** [comment]
5.7 isn’t released yet and as such, I’d suggest the docs are incomplete
