### ISSUE TITLE
Authorising actions using *gates* via Middleware

### ISSUE THREAD

**Issue by teo1978** [laravel/docs#4451]
At
https://laravel.com/docs/5.6/authorization

After reading the difference between gates and policies, I knew what I was interested in was gates, which are simpler, so I read the part about gates. There it explained how to use `Gate::allows()` and `Gate::denies()`, but I was eager to learn how to use **Middleware** to authorise actions with **gates** (if at all possible).

However, the only section about middleware here is under the section 
- Authorizing Actions **Using Policies**
- - Via Middleware

and it only talks about policies, so it gives the false impression that middleware can only used to authorise actions using policies, **not gates**.

I figured out, by blindly trying, that you can indeed use middleware with gates in a pretty similar way and it works, but it should be properly documented.

**Comment by driesvints** [comment]
Please provide an example of this and preferable send it already in as a PR. Thanks!

**Comment by teo1978** [comment]
I don't understand why you close it. The description of the issue is pretty clear, there's a basic feature that is completely undocumented.

That I don't provide a fix is not a reason for closing the issue.

**Comment by driesvints** [comment]
@teo1978 can you please provide a code snippet on how this should work?

**Comment by teo1978** [comment]
>  can you please provide a code snippet on how this should work?

Well, the issue I'm reporting is that the feature is not documented, so I can't tell you how it _should_ work.

My guess is that it works as intended.
