### ISSUE TITLE
Proposal: Add "IDE in docker" instructions

### ISSUE THREAD

**Issue by arteniioleg** [laravel/docs#4456]
In all my projects I start IDE in docker via [x11docker](https://github.com/mviereck/x11docker).
It works only on Linux and there is [some progress for Windows](https://github.com/mviereck/x11docker/issues/70).

In short the workflow is like this:
1. Install `x11docker` (if this is a blocker, it can be automated)
2. Execute `PROJECT_DIR/ide-in-docker.sh ~/path/to/ide.sh`
    This script will build the image for IDE container, will start docker-compose containers (if any) and will start IDE inside a container.

Some examples:

* https://github.com/JoeyDeVries/LearnOpenGL/tree/master/docker
* https://github.com/arteniioleg/chak-chak/tree/5b9ca65dbf07cf94beb4b4e319e0e2dd6cab223a/docker
* https://github.com/arteniioleg/defacto.md/tree/5cf515badb2f9593d394c1b5405ff7ee780c2044/docker

If you are interested, I can provide more details and maybe a pull request. If not, close this issue.

**Comment by laurencei** [comment]
Thanks. While useful, this is pretty specific and not currently a supported option. Currently supported options are Homestead and Valet.
