### ISSUE TITLE
Query Logging missing from L5.1 to L5.7

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/docs#4466]
There is a Query Logging in L5.0 (https://laravel.com/docs/5.0/database#query-logging). From L5.1 and up, Query Logging section is not there anymore and there is no information about it.

**Comment by driesvints** [comment]
Feel free to send in a PR to add it again :)

**Comment by michaelnguyen547** [comment]
@driesvints can you please tell me how to send in a PR with a step by step? I am new to this. Sorry if it is a trivial request.

**Comment by driesvints** [comment]
@michaelnguyen547 heya, no problem!

Go to https://github.com/laravel/docs/blob/5.7/database.md and click on the pencil on the top right. This will fork the repo to your account and open the editor. Add the content which you wish to add in the wysiwyg and enter a commit message at the bottom of the screen. Then submit the pr to this repo under the 5.7 branch. Should be pretty straightforward. Let me know if you need more help :)
