### ISSUE TITLE
Doc: eloquent-mutators Defining An Accessor -> improvment

### ISSUE THREAD

**Issue by ChrisSantiago82** [laravel/docs#4476]
In The Documentation of defining an Accessor there is also the example how to return a "return new, computed values from existing attributes". This is very useful but I also think most people will need to know then about the "eloquent-serialization#appending-values-to-json".
In the example how to create a computed value there should be a hint or a link how to appending the value because it's not obvious to everybody:
https://laravel.com/docs/5.7/eloquent-mutators#defining-an-accessor
https://laravel.com/docs/5.7/eloquent-serialization#appending-values-to-json

**Comment by driesvints** [comment]
Thanks. Good suggestion. Sent in a PR for this ^
