### ISSUE TITLE
Upgrading To 5.7.0 From 5.6

### ISSUE THREAD

**Issue by lubimor** [laravel/docs#4514]
Hi there!

I'm currently trying to upgrade from 5.6 to 5.7 and I found out that configuration env. key for "queue" was changed from "QUEUE_DRIVER to QUEUE_CONNECTION"

It would be great to add this to the upgrade guide. I will be happy to open a pull request.

**Comment by browner12** [comment]
go ahead an make the PR.

otherwise this change is covered in our "Miscellaneous" section.
