### ISSUE TITLE
Note for regex validation: use delimiters

### ISSUE THREAD

**Issue by martenkoetsier** [laravel/docs#4518]
I was bitten by an error where my `regex` validation rule did not specify pattern delimiters.

The PHP documentation describes that [the `preg_match` function](https://secure.php.net/manual/en/function.preg-match.php) accepts a `$pattern` parameter and it is only implied in the examples that is needs delimiters. One might therefore think that the delimiters are _part of the pattern_. However, the [regexp reference on delimiters](https://secure.php.net/manual/en/regexp.reference.delimiters.php) says 

> [...] it is required that the pattern is enclosed by _delimiters_.

With this, one might think that delimiters are _not part of the pattern_.

Could the Laravel documentation include a note on this? E.g.

> **Note:** internally, this rule makes use of the PHP `preg_match` function. The pattern specified should obey the same formatting as for `preg_match` and thus also include valid delimiters. For example:
> `'email' => 'regex:/^.+@.+$/i'`

**Comment by driesvints** [comment]
Thanks. Sent in a PR for this ^
