### ISSUE TITLE
Doc : Query Builder -> chunk results

### ISSUE THREAD

**Issue by hondnl** [laravel/docs#4536]
It would be nice to put a warning or comment about using the chunk feature when updating/deleting records.

The amount of times I had to repair databases because a dev did not realize what it actually did is ridiculous.

Especially when importing data updates from temp tables for example..
Deleting can be even worse...

example of what I encountered often ;
```
DB::table('table_one')
            ->join('table_two','table_one.id','=','table_two.foreign_key')
            ->whereNull('table_two.some_column')
            ->orderBy('table_one.id')
           ->chunk(100,function($items){

               foreach($items as $item){

     
                DB::table('table_two')
                    ->where(foreign_key','=',$item->id)
                    ->update([
                        'some_column' =>$item->some_column
                    ]);


            }
        });

// It will run ... and every chunk loop we will be missing 100^chunk records.
```

Would be nice to see an addition to this and maybe show some options ( like chunkById).

Thank you

**Comment by driesvints** [comment]
Thanks. Sent in a PR for this ^

**Comment by barryvdh** [comment]
The PR only talks about updating primary/foreign keys, but usually the problem is changing a value that is used to filter. Updated the section here: https://github.com/laravel/docs/pull/4711

**Comment by driesvints** [comment]
Thanks @barryvdh!
