### ISSUE TITLE
Custom blade directive naming convention

### ISSUE THREAD

**Issue by paulcanning** [laravel/docs#4537]
So I found this out after pulling my hair out for half an hour.

Nowhere on this page, https://laravel.com/docs/5.7/blade#extending-blade, does it tell you the naming convention for new blade directives.

Turns out you cannot use hyphens and possibly other characters, I didn't check.

Can you please fix this so anytime you are allowed to define anything custom, the naming conventions are explained.

**Comment by browner12** [comment]
relevant line for why hyphens do not work.

https://github.com/laravel/framework/blob/5.7/src/Illuminate/View/Compilers/BladeCompiler.php#L310

**Comment by browner12** [comment]
fixed in #4540 

this issue can be closed.

**Comment by driesvints** [comment]
Thanks guys 👍

**Comment by browner12** [comment]
in 5.8 we will also be throwing an exception now when declaring invalid directives.

https://github.com/laravel/framework/blob/master/src/Illuminate/View/Compilers/BladeCompiler.php#L478
