### ISSUE TITLE
[Upgrade 5.6 -> 5.7] testing artisan command modifying the database

### ISSUE THREAD

**Issue by oliverpool** [laravel/docs#4548]
I just fought for a couple of hours with the following scenario:
- we have a command which inserts some stuff in the database
- this command is tested using
```php
$returnCode =  $this->artisan('cmd');
$this->assertEquals($returnCode, 0);
```

It stopped working with the upgrade to 5.7.

We then figured out, that the `$this->artisan` method returns an object, on which we could check the exit code: 
```php
$this->artisan('cmd')->assertExitCode(0);
```

But the next test checking that the database was updated, then failed (table was empty!).

After searching a lot, it turns out, that the command is delayed until the end of the test, before being run!

And the correct way to do it is:

```php
$returnCode =  $this->artisan('cmd')->run(); // call run!
$this->assertEquals($returnCode, 0);
```

---

# Suggestions:

* Indicate in the [upgrade guide](https://laravel.com/docs/5.7/upgrade), that `$this->artisan(...);` must be replaced with `$this->artisan(...)->run();`
* Indicate that the artisan command are run on destruction, expect if `->run()` is called in https://laravel.com/docs/5.7/console-tests#expecting-input-and-output

Thanks !

**Comment by canvural** [comment]
Console output mocking is enabled by default.

Better way to do what you are doing is like this I guess, `$this->withoutMockingConsoleOutput()->artisan(...)`

So, I think it should be noted that mocking the output is on by default. So if you are not interested in the output but rather in the exit code, you should call `withoutMockingConsoleOutput` first. And maybe this should be in the 5.7 upgrade guide.

**Comment by oliverpool** [comment]
Just calling `->run()` on the artisan command is nicer I think (the problem is not the output mocking, but the delayed execution)

**Comment by driesvints** [comment]
Yeah I can see how this behavioral change can be in the upgrade guide. Feel free to send in a PR.
