### ISSUE TITLE
Upgrade guide: Hash:check should be medium impact

### ISSUE THREAD

**Issue by jopapo** [laravel/docs#4550]
Upgrade guide: Hash:check should be changed from low to medium ou high.

Bcrypt hashes starting with something diferent than $2y fails. Even if it can be verified correctly. So authentication will fail to a big audience.

The problem is with php function password_get_info from php 7.2.

Details here: https://laracasts.com/discuss/channels/laravel/laravel-socialite-login-this-password-does-not-use-the-bcrypt-algorithm

**Comment by driesvints** [comment]
This is now fixed with https://github.com/laravel/framework/pull/25468 so I believe the priority can stay to low. Feel free to give extra thoughts about this if you think it should still be changed.
