### ISSUE TITLE
[5.7] Route::fallback lacking information

### ISSUE THREAD

**Issue by TivoSoho** [laravel/docs#4572]
As I started using this the main article that comes up is this news: https://laravel-news.com/laravel-v5-5-5 The official documentation however only shows Closure as an example (https://laravel.com/docs/5.7/routing#fallback-routes), giving the impression that's the only one supported.

Furthermore, as I started using it based on the news article, it turned out I need to specifically say I am returning a 404 HTTP status code with my response. It did not fallback to an actual 404, which it should have giving the context. For this reason there should be documentation using it with a view response and with the fact that it will not automatically return a 404.

**Comment by driesvints** [comment]
Heya. There's quite a bit undocumented things and hidden gems in Laravel. If you ever spot anything which you think should be in the docs feel free to send in a PR.

**Comment by TivoSoho** [comment]
So this is the place to report issues with documentation and any reports you ignore if the person is not qualified enough to do a PR? What is the point of this then?

**Comment by driesvints** [comment]
@TivoSoho ow, happy to help you out with explaining how to do a PR:

1. Go to the https://github.com/laravel/docs page
2. Click on the page you want to edit
3. Click on the pencil on the right above to edit the document (the repo will be forked to your account)
4. Submit your changes with a commit (below your editor)
5. You'll now be prompted to submit a PR

Hope this helps. Not ignoring you btw, just trying to point out that we can't include every single small thing of the framework but we're open to suggestions if you can submit a PR.
