### ISSUE TITLE
PSR-7 Requests

### ISSUE THREAD

**Issue by uphlewis** [laravel/docs#4593]
# The Issue
Following the instructions in the [Request documentation](https://laravel.com/docs/5.7/requests#psr7-requests) to require the 2 packages required for psr-7 requests i.e.:
```
composer require symfony/psr-http-message-bridge
composer require zendframework/zend-diactoros
```

... causes an 'undefined method' fatal error when type hinting for a psr-7 request as documented (`Psr\Http\Message\ServerRequestInterface`).

**TLDR; As of right now, following the documentation to the letter leads to a version conflict error**

# The Error
`Call to undefined method Zend\Diactoros\ServerRequestFactory::normalizeServer()`

# The Cause
Latest version of `symfony/psr-http-message-bridge` (v1.1.0) is attempting to call a method in `/vendor/symfony/psr-http-message-bridge/Factory/DiactorosFactory.php:46` which I believe was deprecated in v1.8 of `zendframework/zend-diactoros`. Currently doing a 'dumb' `composer require` on the above 2 packages yields v1.1 and v2.0 respectively.

# Workaround
Instead of `composer require zendframework/zend-diactoros` do `composer require zendframework/zend-diactoros ^1.8` to get the version compatible with `symfony/psr-http-message-bridge`

# Solution
I'll submit a pull request to symfony/psr-http-message-bridge v1.1

**Comment by uphlewis** [comment]
PR: https://github.com/symfony/psr-http-message-bridge/pull/54

**Comment by driesvints** [comment]
I realize that the docs are currently pointing to a faulty release but this is more of an issue on the Symfony repo and changing the docs now temporarily isn't the way to go tbh. Judging from the issue linked this will be solved soon enough so I'm going to close this issue. People can still use this as a reference.

Thanks for reporting.

**Comment by nsn0x01** [comment]
I have the same issue..
