### ISSUE TITLE
Upgrade from laravel 5.6.* to 5.7.* wont add the laravel dev-dependencies 

### ISSUE THREAD

**Issue by ankitjain28may** [laravel/docs#4633]
As laravel-dump-server is added as a dev-dependency in laravel 5.7.* but on upgrading it from 5.6.* won't add this dependency as it is a part of `laravel/laravel` and not a part of `laravel/framework`, so it would be better to add this in the upgrade section of the docs so people can use this feature of laravel 5.7.*

**Comment by driesvints** [comment]
This isn't anything major or breaking when upgrading so that's why it's not added. In fresh Laravel installs it'll be included.

**Comment by ankitjain28may** [comment]
@driesvints Yes, This isn't anything that is major, but it would be good to be added in the docs.
