### ISSUE TITLE
Stripe's billing database default column types

### ISSUE THREAD

**Issue by slashome** [laravel/docs#4641]
Just wondering why do you not specify types for stripes columns here :
```php
$table->string('card_brand')->nullable();
$table->string('card_last_four')->nullable();
```

where it could be :
```php
$table->string('card_last_four', 4)->nullable();
```

and "brand" type could a Many2One or a varchar(16)

[stripe doc](https://stripe.com/docs/api#retrieve_event)

**Comment by driesvints** [comment]
You're correct. Feel free to send in a PR or otherwise I'll pick this up later. I wouldn't change change the value for `card_brand` as you don't always know how long these will be. You do know that `card_last_four` will always be 4 digits.

**Comment by slashome** [comment]
> You're correct. Feel free to send in a PR or otherwise I'll pick this up later. I wouldn't change change the value for `card_brand` as you don't always know how long these will be. You do know that `card_last_four` will always be 4 digits.

done ;)
