### ISSUE TITLE
Mail documentation make it seem like you can use vendor default html for html emails

### ISSUE THREAD

**Issue by octoxan** [laravel/docs#4667]
https://laravel.com/docs/5.7/mail#configuring-the-view

The documentation says you can run the following artisan command:

`php artisan vendor:publish --tag=laravel-mail`

Then it goes on to explain "This command will publish the Markdown mail components to the  resources/views/vendor/mail directory. The mail directory will contain a html and a  markdown directory, each containing their respective representations of every available component. The components in the html directory are used to generate the HTML version of your email, and their counterparts in the markdown directory are used to generate the plain-text version."

This makes it sound like you can use these if you're using html for your emails with `->view()` but it seems you can only extend these layouts if you're using `->markdown()`. If this is the case, should there be a warning block somewhere in the "Configuring The View" section that mentions you can't use the HTML templates provided by Laravel, and must build your own completely from scratch.

The docs currently are very unclear as to how to customize HTML emails. Spent a while trying to get components and slots to work in a html/view email, only to realize I had to just build a new layout completely from scratch.

The vendor/mail/html directory still calls Markdown functions, while the paragraph describing that the vendor directory was published says the html directory is used to generate the html version of your email. Doesn't say "html version of your email, generated from markdown".

**Comment by driesvints** [comment]
Heya, thanks. You're free to send in a PR with suggested changes on how to make this more clear.
