### ISSUE TITLE
Provide a multilingual environment for the Doc

### ISSUE THREAD

**Issue by armanatory** [laravel/docs#4709]
Dear guys, I think it would be an obstacle for many people around the world that they don't have an access to an official and reliable documentation in their own language. Furthermore, there are lots of guys who will help the translation and keeping files up to date. What if you provide a multilingual one? What's your opinion?

**Comment by azdanov** [comment]
This has been discussed before:
* https://github.com/laravel/docs/issues/4402
* https://github.com/laravel/docs/issues/3946

**Comment by driesvints** [comment]
You're free to create, host and maintain community translated versions of the documentation. This is not something we're going to maintain ourselves, sorry.
