### ISSUE TITLE
middleware

### ISSUE THREAD

**Issue by unstoppablecarl** [laravel/docs#4742]
I was recently answering some questions about middleware and realized a few things not clear in the docs that I am proposing be added.

1) middleware is processed in the following order
 - global middleware
 - group middleware
 - single route middleware
 - controller middleware

(the last 2 I'm only 90% sure of the order, correct me if I'm wrong)

2) In the `App\Http\Kernel.php` file the `$middlewarePriority` array comment says "This forces the listed middleware to always be in the given order.". It appears that only group middleware is ever sorted though. 

I wanted to get feedback and confirm these details before making a PR.

**Comment by unstoppablecarl** [comment]
I tinkered a little more and found some new discoveries. It looks like all middleware is put into 2 lists global and everything else. It appears that the global is never stored so it is just run in the order defined in `Kernel.php`. All other middleware is merged and sorted using  `$middlewarePriority`. It is still a little unclear that the middleware is run in 2 chunks. 

I propose the comment be updated to say something like "This forces non-global middleware to always be in the given order."  Also, a short section in the docs explaining this 2 chunk process.

**Comment by driesvints** [comment]
We've merged your PRs now.
