### ISSUE TITLE
Upgrade instructions missing for 5.6.30

### ISSUE THREAD

**Issue by Shifterovich** [laravel/docs#4746]
https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30

Composer instructions for the actual upgrade are missing here (similar to #2564). There should be instructions like for the [5.5-5.6.0 upgrade](https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0).

I'd just add `composer update` there.

**Comment by driesvints** [comment]
Since 5.6 is no longer supported I'm going to close this.
