### ISSUE TITLE
horizon requires failed_jobs database table

### ISSUE THREAD

**Issue by ankurk91** [laravel/docs#4782]
Hi, @driesvints 

Laravel Horizon will try to save failed jobs in a database table.
Read https://github.com/laravel/horizon/issues/88#issuecomment-321781755

If the table does not exists, it will throw exception and it will get reported to services like Bugsnag.

This should be mentioned in **horizon** docs that user need to publish the `failed_jobs` db table and migrate even though horizon uses redis
```
php artisan queue:failed-table
php artisan migrate
```

Some users has already reported issues like -
https://github.com/laravel/horizon/issues/243

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/docs/pull/4784
