### ISSUE TITLE
Document TransformsRequest in the Middleware page

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/docs#4797]
I think the Illuminate\Foundation\Http\Middleware\TransformsRequest is an amazing undocumented feature.

It would be great if this feature is documented like "You can extend the TransformsRequest middleware and override transform($key, $value) method to create a custom middleware that preprocess your request".

**Comment by driesvints** [comment]
I don't really believe this should be in the docs really. It's a pretty specific middleware used by to trim strings and convert empty strings. If you still feel it should be added, feel free to send in a PR to see if it'll get accepted.
