### ISSUE TITLE
Scout: searchable() could use some clarification

### ISSUE THREAD

**Issue by chamby** [laravel/docs#4813]
https://github.com/laravel/docs/blob/1fc008fa4560a3af9883d6e5c7f92d3506f530c0/scout.md#L215-L224

The above snippet of the Scout documentation could be clarified to explain a subtle but important difference when calling this method on different types of classes.

```
// shouldBeSearchable() is not used to filter models.
// All models will be made searchable.
$model->searchable();
$collection->searchable();

// shouldBeSearchable() is used to filter models.
// Models will be made searchable depending on the return value of shouldBeSearchable()
$model->relationship()->searchable();
$query->searchable();
```

**Comment by driesvints** [comment]
I still don't understand how this could happen. All models should pass the `SearchableScope`. If this isn't the case I think this is a bug rather than expected behavior.

**Comment by driesvints** [comment]
After some further research I've found out that this should indeed be clarified somehow. I'll try to send in a PR.

**Comment by driesvints** [comment]
Sent in a PR: https://github.com/laravel/docs/pull/4820
