### ISSUE TITLE
[Question/Suggestion] Why api 'token' driver (TokenGuard) is not documented? 

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/docs#4822]
I cannot found the api 'token' driver (TokenGuard class) on the documentation or nothing about the 'api_token'. I think it should be documented since it provides a simple way to authenticate users without the need of complex infrastructure like passport (It is ideal for simple REST apis for example for a mobile app backend). I actually use this guard in a 2 years old project but now I can't find any official documentation. 

Link about the 'api_token' and token guard: 
https://gistlog.co/JacobBennett/090369fbab0b31130b51?fbclid=IwAR090ivjT_dytD0zaGvsipgGBpMTr_OjobVJcddCvJVrjRs4dOVA2qVk8MA

TokenGuard class:
https://github.com/laravel/framework/blob/master/src/Illuminate/Auth/TokenGuard.php

Please correct me if this is documented somewhere.

**Comment by driesvints** [comment]
This is because we push for using Laravel Passport for API authentication: https://laravel.com/docs/5.7/passport

If you'd like to use something else you can use great articles like Jacob's article on the api_token.

**Comment by jhm-ciberman** [comment]
Oh. I understand. I think is not worth migrating a 2 years old app to passport. But I will try to use it in the future. Thanks for the answer.
