### ISSUE TITLE
[Suggestion] Move factories to it's own page for easier access. 

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/docs#4823]
I think it should be great to have all the content related to factories inside his own page. 
Actually it's located in 'Database testing'. And that is not as useful for SEO as 'Factories'.

Also, the "Generating Factories" and "Resetting Database after each test" are on the same page and they have nothing in common. 

I suggest the following refactor:

**Before:** 

database_testing.md

    Introduction
    Generating Factories
    Resetting The Database After Each Test
    Writing Factories
        Factory States
        Factory Callbacks
    Using Factories
        Creating Models
        Persisting Models
    Relationships
    Available Assertions

**After:**

database_testing.md (original file) or testing.md (merge into)

This can be in the file called database_testing.md, but in my opinion, it should be merged with the "Testing > Getting Started", because almost every feature test in laravel use the database reset trait.
Also, normally as a developer, you don't check this documentation often as the "factories" documentation.  

    Introduction (Use the actual introduction here)
    Resetting The Database After Each Test
    Available Assertions

factories.md (new file) 

    Introduction (New: explain a little about factories and it's relation with testing and seeding)
    Generating Factories
    Writing Factories
        Factory States
        Factory Callbacks
    Using Factories
        Creating Models
        Persisting Models
        Relationships

...And maybe two sections called "Testing with Factories" and "Seeding with Factories" showing two little examples of use cases.

**Comment by driesvints** [comment]
Heya, thanks for suggesting this. I think it's fine as it is at the moment though. If we were to move everything to a new page all the hyperlinks to these sections would break as well.

**Comment by jhm-ciberman** [comment]
Well. It's a shame if the reason is only for the hyperlinks, since the task is a simple global search and replace. I can help with that if it's a matter. 

Anyway, thanks for the quick response.
