### ISSUE TITLE
Suggestion: Blade callable class

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel/docs#4863]
Since the the `directive()` method accepts a `callable` as second argument, it would be very handy to point out that rather than cloger up the `boot()` method of a Service Provider, call a callable class:

---

As you can see, we will chain the `format` method onto whatever expression is passed into the directive. So, in this example, the final PHP generated by this directive will be:

    <?php echo ($var)->format('m/d/Y H:i'); ?>

Since the second argument of `directive()` accepts a `callable`, you can use a class that implements the `__invoke` method to handle all the logic, keeping your Service Provider clean. 

    <?php

    namespace App\Providers;

    use Illuminate\Support\Facades\Blade;
    use Illuminate\Support\ServiceProvider;
    use App\Blade\Directives\DatetimeDirective;

    class AppServiceProvider extends ServiceProvider
    {
        /**
         * Perform post-registration booting of services.
         *
         * @return void
         */
        public function boot()
        {
            Blade::directive('datetime', new DatetimeDirective($expression));
        }

        /**
         * Register bindings in the container.
         *
         * @return void
         */
        public function register()
        {
            //
        }
    }

> {note} After updating the logic of a Blade directive, you will need to delete all of the cached Blade views. The cached Blade views may be removed using the `view:clear` Artisan command.

**Comment by driesvints** [comment]
I was writing the docs for this and got to this:

```
An alternative approach would be to create an invokable class which can contain all of the logic. This allows you to prevent clogging up your service provider with large directives:

    <?php

    namespace App\Views\Blade;

    class DateTimeDirective
    {
        public function __invoke($expression)
        {
            return "<?php echo ($expression)->format('m/d/Y H:i'); ?>";
        }
    }

And then register the directive:

    Blade::directive('datetime', new DatetimeDirective());
```

But it feels like I'm here explaining invokable classes more than an alternative Blade directive registration. I feel like it should be common PHP knowledge that you can use invokable classes here instead. So I don't think this adds that much value to the docs themselves. 

You may try to send this in yourself if you like. Feel free to use the above code.

Ps. you don't need to pass the `$expression` as a constructor param since it's passed to the `__invoke` method.
