### ISSUE TITLE
Query builder paginate() method - Incorrect @return type

### ISSUE THREAD

**Issue by Naveen1895** [laravel/docs#4866]
In Query builder class, **paginate()** method returns **\Illuminate\Pagination\LengthAwarePaginator**  but the PHP documentation contains \Illuminate\Contracts\Pagination\LengthAwarePaginator.

**Comment by staudenmeir** [comment]
This is correct. The `LengthAwarePaginator` class implements the `LengthAwarePaginator` interface/contract.

**Comment by driesvints** [comment]
This isn't an issue for the docs repo. Please submit a PR if you feel that something is wrong.
