### ISSUE TITLE
Cookie documentation somewhat unclear

### ISSUE THREAD

**Issue by garyross** [laravel/docs#4903]
[quote]
Generally, [these arguments have the same purpose and meaning](https://laravel.com/docs/5.7/requests#cookies) as the arguments that would be given to PHP's native setcookie method:

```
return response('Hello World')->cookie(
 'name', 'value', $minutes, $path, $domain, $secure, $httpOnly
);
```
[/quote]

So is the 3rd argument, $minutes, minutes from now? What does 'generally' mean in this context? All the arguments except the 3rd or something else? 

Thanks.

**Comment by kennith** [comment]
@garyross actually I think the paragraph above that already stated `$minutes` is 

> number of minutes the cookie should be considered valid

see https://github.com/laravel/docs/blob/5.7/requests.md#attaching-cookies-to-responses

**Comment by driesvints** [comment]
@kennith thanks for pointing that out.

**Comment by garyross** [comment]
@kennith @driesvints 
Thanks. Sorry about that. Not sure how I missed it!
