### ISSUE TITLE
Homestead sites config could be less vague

### ISSUE THREAD

**Issue by dansgithubuser** [laravel/docs#4905]
Here,
https://laravel.com/docs/5.7/homestead
the docs introduce the sites Homestead.yaml configuration:
```
sites:
    - map: homestead.test
      to: /home/vagrant/code/Laravel/public
```

I got hung up when I configured my own like so:
```
sites:
    - map: homestead.test
      to: /home/vagrant/code/my-laravel-project
```

I'm coming at this with very little PHP/Laravel/Homestead context. I've worked with web frameworks, vagrant, and virtualbox before. But it wasn't clear to me that "Laravel" was supposed to be the name of a Laravel-created project. I figured it wasn't actually naming the framework itself, and wrote it, and the `/public`, off as "example gibberish".

Suggested solution is simple. Change instances like this to `my-laravel-project`. I can submit a PR, but wanted to establish sanity first.

**Comment by roberto-aguilar** [comment]
The purpose of the public directory [is documented](https://laravel.com/docs/5.7/structure#the-public-directory) as:

> the entry point for all requests entering your application.

So yeah, it is well know for laravel developers.

Your idea about allowing not to pass `/public` and sanitize the entry is not bad, but given how the homestead nginx script works, i'm afraid that the benefits doesn't outweigh the cons of more complicated readability and maintenance.

Also, the `/public` directory is already empathized with a different color in the documentation:

<img width="883" alt="screen shot 2019-01-13 at 9 36 13 pm" src="https://user-images.githubusercontent.com/5356595/51095561-4fdfe400-177b-11e9-8a52-8b205a9e7b30.png">

**Comment by dansgithubuser** [comment]
Sure these are all ways to figure out what the meaning is here, but why has `Laravel` been chosen as the example name of a Laravel project?

The exact change I'm suggesting.
from
```
sites:
    - map: homestead.test
      to: /home/vagrant/code/Laravel/public
```
to
```
sites:
    - map: homestead.test
      to: /home/vagrant/code/my-laravel-project/public
```

**Comment by roberto-aguilar** [comment]
Oh, sorry for my misunderstanding, @dansgithubuser.

I don't know the reason behind the naming, Taylor choose it since 65c262ecd6a53108caf78f986ecc9d69d74ed24f.

Given that your suggestion is pretty straightforward, i suggest you to give a try with directly with a PR to get more immediate feedback.

**Comment by driesvints** [comment]
Is this the global Homestead one? Because I see the default `Homestead.yaml` to be a little different: https://github.com/laravel/homestead/blob/master/resources/Homestead.yaml

@svpernova09 Is there a different default one for the global Homestead.yaml? Otherwise I think we could just update the docs with the current template?

**Comment by svpernova09** [comment]
@driesvints Not sure I'm understanding the question. There is only that one instance of `Homestead.yaml` in the repo.

IMHO:

We should use this:

```
sites:
    - map: homestead.test
      to: /home/vagrant/code/my-project/public
```

Since Homestead isn't Laravel specific.

**Comment by dansgithubuser** [comment]
@driesvints Looks like in the link you have "code" means "your project folder" whereas in the docs I'm referencing it means "the folder containing all your projects". I actually took "code" to mean either one of these, is that not the intent of giving it such a general name?

I'm liking @svpernova09's suggestion. I'll leave some settling time and then make a PR.

**Comment by svpernova09** [comment]
@dansgithubuser,

FWIW we can even leave off the `/code/` part of the path making it `/home/vagrant/my-project/public`.

This may be confusing for some people so not a huge deal if we don't implement it this way.

**Comment by dansgithubuser** [comment]
I could just go ahead and explain the meaning of the different parts of the path, rather than figuring the optimal example to give. I'll put that in the PR, it'll be easier to make suggestions and choose to keep or omit.
