### ISSUE TITLE
Missing information about Blade::include directive

### ISSUE THREAD

**Issue by andrewgorpenko** [laravel/docs#4919]
Hello. I've noticed that Laravel Docs is missing information about Blade::include directive. That is strange, because it was added in 5.6 and still not documented.

**Comment by andrewgorpenko** [comment]
It isn’t. I meant Blade::include method to create custom Blade components-includes without slots and @end prefix. One day Laravel News wrote about this new feature, but it was not documented. But the same day components were released and they are documented.

**Comment by driesvints** [comment]
Aha found it: https://laravel-news.com/blade-component-include-aliases

You're correct. I'll send something in for this.
