### ISSUE TITLE
Upgrade Guide - To 5.7.0 From 5.6, Cache: new data directory

### ISSUE THREAD

**Issue by r-pascal** [laravel/docs#4925]
The section stating that a new data directory has been added to `storage/framework/cache` recommends to create the new directory and add a .gitignore file.

What is missing is the info that the `/config/cache.php` file should be updated as well.
Store type `file=>path` should be changed to `storage_path('framework/cache/data')`

If not updated, artisan command `cache:clear` will delete the newly created `storage/framework/cache/data` folder again.

**Comment by driesvints** [comment]
This has been like this since 5.4: https://github.com/laravel/laravel/blob/5.4/config/cache.php
