### ISSUE TITLE
[5.5] Basic auth exception not documented in upgrade guides

### ISSUE THREAD

**Issue by marius321967** [laravel/docs#4936]
`SessionGuard::failedBasicResponse()` used to generate responses for unauthenticated Basic auth requests.

Since Laravel 5.5, this method's signature has been changed ([20673](https://github.com/laravel/framework/pull/20673)) and it now throws an exception which the application is supposed to handle. For example, my middleware now has to catch the exception from `basic()` instead of checking if the returned value is non-null. This change was not mentioned in the [upgrade guide](https://laravel.com/docs/5.5/upgrade).

**Comment by driesvints** [comment]
5.5 is closed for bug fixes only. You may still send in a pr if you feel anything is missing.
