### ISSUE TITLE
Missing documentation for queued closures

### ISSUE THREAD

**Issue by fitztrev** [laravel/docs#4947]
This was added back to Laravel via laravel/framework#25777.

It's no longer necessary to have a job class:

```php
dispatch(new BackgroundJob);
```

You can now pass an anonymous function:

```
dispatch(function () {
    // Any code here will be executed by the queue worker
});
```

Here is the section from the 5.0 docs back when it was included: https://github.com/laravel/docs/blob/5.0/queues.md#queueing-closures

**Comment by driesvints** [comment]
Gonna close this as the pr was already sent in.
