### ISSUE TITLE
[Breaking]FormRequest validated do not return merged data to the request 

### ISSUE THREAD

**Issue by raftalks** [laravel/docs#4968]
Upgrade from 5.6 to 5.7 noticed following breaking change not been documented.

When using FormRequest instance within a route, where if the request instance gets merged with additional data, the request validated method do not return the result of the merged data. 

I was able to solve this problem by adding an extra method called on the request. 
See the example below:

Laravel 5.6
-----------
$request->merge(['item_id' => 11]);
$request->validated(); // returns ['item_id' => 11, ...]

Laravel 5.7
----------
$request->merge(['item_id' => 11]);
$request->validated(); // returns [ ...] and doesn't include item_id key that was merged

Solution I am using:
$request->merge(['item_id' => 11]);
$request->validateResolved();
$request->validated(); // returns ['item_id' => 11, ...]

**Comment by driesvints** [comment]
The behavior was changed after the release of 5.7. I agree that this may be confusing but looking at your code it's actually never meant to work this way. `validated` returns the data that was validated during the resolving of the form request object. It doesn't actually performs the validation itself. It's best that you merge the data with the validated **after** you retrieved the validated data.

```php
$data = $request->validated();
array_merge($data, ['item_id' => 11]);
```
