### ISSUE TITLE
Docs rendered with Fira Code on laravel.com may be confusing

### ISSUE THREAD

**Issue by nickroeker** [laravel/docs#4977]
On laravel.com/docs/, the code sections can be rendered with Fira Code if the viewer has it installed.

```
  font-family: "Operator Mono", "Fira Code", Consolas, Monaco, "Andale Mono", monospace;
```
Unfortunately this can display the ligatures for Fira Code, losing clarity on what the user should actually type. For example, see below for how `===` is rendered.

![screenshot_2019-02-13-09 37 59](https://user-images.githubusercontent.com/22895294/52732662-9a6ca000-2f75-11e9-9740-ab6e10aa38e4.png)

My keyboard doesn't have a `≡` key, nor would it work as expected if I managed to insert it somehow.

Apologies as this is likely in the wrong repo, but I could not create an issue for laravel.com itself or find any way to report the issue on the website. If this is not appropriate to file here please close and I'll do a more rigorous search on how to file this issue appropriately.

**Comment by gpressutto5** [comment]
Well, I think we can assume that if the user has Fira Code installed they know what font ligatures are.

**Comment by driesvints** [comment]
I agree with @gpressutto5
