### ISSUE TITLE
PHP templates

### ISSUE THREAD

**Issue by jimgwhit** [laravel/docs#4980]
I don't use blade, and currently I use the following technique:

Controller code:
```
public function indexnp()
    {

        $dogs = DB::table('dc_dogs')->where('adopted', '=', 0)->paginate(5);
        $title = 'test';
        $view = 'dog/index';
        $header = View::make(ViewLayout::getPartial('headertp'));
        $layout = ViewLayout::getLayout('dog/indextp');
        $content = View::make($view)
                ->with('dogs', $dogs);
        return view($layout, compact('header', 'content', 'title'));
        
    }
```

php template (layout)
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?= $title; ?></title>
        <link href="<?php echo asset('assets/css/style.css'); ?>" rel="stylesheet">
        <link href="<?php echo asset('assets/css/paging.css'); ?>" rel="stylesheet">
        <script type="text/javascript" src="<?php echo asset('assets/js/jquery.js'); ?>"></script>

    </head>
    <body>
        <?php echo $header; ?>

        <?php echo $content; ?>
    </body>
</html>
```
So this same layout is re-usable depending on what I send from controller.

This part
```
        $header = View::make(ViewLayout::getPartial('headertp'));
        $layout = ViewLayout::getLayout('dog/indextp');
```
Just custom methods to make it easier.

I basically use view:: make to replace section and pass as needed.

This all works, also see:
https://laracasts.com/discuss/channels/laravel/difference-in-section-and-render

It would just be nice if the docs had a little on php layout for someone who wasn't using blade.

What I came up with works for me, but I am sure Taylor would come up with something better.

Thanks.

**Comment by browner12** [comment]
I don't think it's the responsibility of the Laravel Docs to explain generic PHP.  People could go about this many ways, so I think it's outside the scope of our docs.

**Comment by jimgwhit** [comment]
You are not explaining php, it would be examples like any framework provides, cake, yii2 has examples of layouts.  Currently laravel has view examples, but no real examples of layouts using php, laravel layouts are all explained with blade in mind. 

I'm not saying use my code, rather it was just an example of how I came up with a solution.

**Comment by jimgwhit** [comment]
Discovered I could have a PHP View and still have a blade Master layout so all good.
