### ISSUE TITLE
Idea for new {tip} (a kind of error to avoid really) for eloquent-mutators

### ISSUE THREAD

**Issue by mikew1** [laravel/docs#5004]
I recently fell into the error of using Eloquent accessor methods when I should really have been using a normal function. I was using it to return a value which was not derived in any way from the underlying active record's fields, and I've concluded I was overusing this feature and should have been using a normal function instead.  (discover exciting new possibility, so... over use it... you know the pattern). 

Do you think it could be useful to add a tip on the eloquent-mutators doc page, e.g. as follows 
(if you indeed agree my understanding is now correct, that is):

"tip" or "warning"
> Accessors should only be used only to return either transformations of values which actually exist on the underlying active record, or combinations thereof. If your aim is to do neither of these things, you should probably be using a normal function instead.

If you like the above, I'd be happy to submit a pull request. Thanks.

**Comment by browner12** [comment]
I don't think this is necessarily true. I think it can be valid to create accessors for a wide range of things, especially if you want to `append` them to your model's JSON output.

**Comment by driesvints** [comment]
Honestly, please just send in a PR to see if it gets accepted or not by Taylor. It's really as much work as creating an issue.
