### ISSUE TITLE
Collection::add() is undocumented

### ISSUE THREAD

**Issue by drweissbrot** [laravel/docs#5017]
The `add` method (https://github.com/laravel/framework/blob/bd867702793d489950b5fd9bfdb944a94ca6ab62/src/Illuminate/Support/Collection.php#L1899) that was added in Laravel 5.8 is not mentioned in the docs. I assume it should be mentioned in the docs for Collections and Eloquent Collections.

In my case, this actually ended up being a breaking change because I already had added an `add` method via macro, so maybe it should also be mentioned in the Upgrade Guide.

**Comment by driesvints** [comment]
Just send in a PR please.
