### ISSUE TITLE
Homestead setup directions a little unclear

### ISSUE THREAD

**Issue by kevinfoley** [laravel/docs#5028]
In the Homestead setup directions, there is a section "Installing Homestead", which opens like this:

> You may install Homestead by cloning the repository. Consider cloning the repository into a Homestead folder within your "home" directory, as the Homestead box will serve as the host to all of your Laravel projects

It is unclear whether we are supposed to clone the repository into the Home directory of the _host_ machine, or _inside_ the Vagrant box (virtual machine)

**Comment by browner12** [comment]
Homestead *builds* the virtual machine, so you should install it in the *host* machine.

Please submit a PR if you have a suggestion for clearing up the wording.
